import { FakePreferenceCardTables } from '../__fixtures__/fake-preference-card-tables'
import {
  MODIFIER_REVISION_ACTION_ID,
  MODIFIER_REVISION_DEPENDENCY_RULE,
  MODIFIER_REVISION_MODIFIER_CODE,
  MODIFIER_REVISION_NEW_RELEASE_ID,
  MODIFIER_REVISION_OLD_RELEASE_ID,
  MODIFIER_REVISION_REQUIREMENT_KEY,
  createModifierRevisionFixture,
} from '../__fixtures__/release-bundle-fixtures'
import {
  defaultBuildInput,
  getLiveRecipeVersions,
  getReleaseDefinitionSources,
  recipeForRecipeVersionId,
} from '../data/demo-context.server'
import {
  buildReleaseContext,
  getCurrentReleaseBundleForScenario,
  getReleaseImpactReports,
  getReleasePointers,
  resolveReleaseDefinitions,
} from '../data/release-bundles.server'
import { expandRecipeComposition } from '../domain/expand-recipe-composition'
import { diffReleaseBundles } from '../domain/release-bundle'
import { parsePersistedSnapshot } from '../schemas/persisted-snapshot'
import { modifierActionTypes } from '../domain/types'
import type {
  ModifierAction,
  ModifierDefinition,
  RecipeModuleVersion,
  RecipeSlot,
  RecipeVersion,
  ResolvedCard,
  ResolvedCardItem,
} from '../domain/types'
import {
  BUILDER_INPUTS_SCHEMA_VERSION,
  saveCardRequestSchema,
  type SaveCardRequest,
} from '../schemas/saved-card'

jest.mock('@/lib/supabase/server', () => ({
  supabaseServer: jest.fn(),
}))

const { supabaseServer } = jest.requireMock('@/lib/supabase/server') as {
  supabaseServer: jest.Mock
}

const { duplicateUserCard, loadUserCard, resolveForSave, saveUserCard } = jest.requireActual(
  '../server/user-cards',
) as typeof import('../server/user-cards')

/**
 * Regressions for the 2026-08-10 post-Codex correction pass on the 2026-08-09 governed-data
 * corrections (PR #91): findings P91-C1, P91-C2, and P91-C3.
 *
 * - **P91-C1** — F-04 must reach *current custom cards*: the six owner-named sampling
 *   instruments resolved to specimen_station / specimen_handling through the real
 *   server-side save path when a custom card selected their modules, because the custom
 *   composition had no action channel. It now carries authored per-slot actions
 *   (`seed/custom-composition.json`) applied by the same canonical evaluator as the
 *   procedure recipes.
 * - **P91-C2** — the F-05 section-level re-phase over-reached on two MED_THORACOSCOPY
 *   *insertable devices* that share the Drainage section; per-slot actions place them at
 *   their governed home-procedure precedents' zone/phase.
 * - **P91-C3** — the release-impact report diffed raw module slots, so action-borne changes
 *   (all six F-04 corrections) never appeared in the canonical artifact. It now diffs the
 *   final effective recipes and reports authored modifier-effect changes generically.
 *
 * Everything here drives real committed data through the real resolution paths — the save
 * path a custom card is stored through, the pinned-release reconstruction a saved card
 * reopens through, and the release diff the canonical artifact is generated by.
 */

const CONTRACT = { version: 'test', implementationHash: 'test' }

const CUSTOM_SCENARIO = 'custom-composition'
const CURRENT_CUSTOM_RELEASE = 'release-custom-composition-v1-2'
const PRIOR_CUSTOM_RELEASE = 'release-custom-composition-v1-1'
const CURRENT_CUSTOM_RECIPE = 'recipe-custom-composition-v1-2'
const PRIOR_CUSTOM_RECIPE = 'recipe-custom-composition-v1-1'

const EBUS_SPECIFIC_MODULE = 'module-ebus-tbna-specific-v1-0'
const THERAPEUTIC_SPECIFIC_MODULE = 'module-therapeutic-bronch-specific-v1-1'
const CHEST_TUBE_SPECIFIC_MODULE = 'module-chest-tube-specific-v1-1'
const MED_THORACOSCOPY_SPECIFIC_MODULE = 'module-med-thoracoscopy-specific-v1-1'

/** The six owner-named F-04 sampling-instrument slots, by procedure-specific module. */
const EBUS_INSTRUMENT_SLOTS = [
  'SLOT-1AF4BEFE3B', // EBUS-TBNA FNA needle
  'SLOT-B83EBD2FBB', // EBUS FNB needle
  'SLOT-D08C74941A', // Intranodal mini-forceps
  'SLOT-E8F0B48B49', // Vacuum-locking syringe
]
const THERAPEUTIC_INSTRUMENT_SLOTS = [
  'SLOT-D2974FC11B', // Flexible biopsy forceps
  'SLOT-FDF73730B0', // BAL kit
]
const ALL_SIX_INSTRUMENT_SLOTS = [...EBUS_INSTRUMENT_SLOTS, ...THERAPEUTIC_INSTRUMENT_SLOTS]

/** The two P91-C2 MED_THORACOSCOPY insertable devices, and the intended F-05 drainage move. */
const THORACOSCOPY_CHEST_TUBE_SLOT = 'SLOT-57CA4B1298'
const THORACOSCOPY_IPC_KIT_SLOT = 'SLOT-9A1C0491F9'
const THORACOSCOPY_DRAINAGE_UNIT_SLOT = 'SLOT-AA3C2EAA6D'

const tables = new FakePreferenceCardTables()

beforeEach(() => {
  tables.reset('user-owner')
  supabaseServer.mockResolvedValue(tables.client())
})

function customCardRequest(options: {
  selectedModuleVersionIds: string[]
  releaseBundleId?: string
  recipeVersionId?: string
  title?: string
}): SaveCardRequest {
  return saveCardRequestSchema.parse({
    schemaVersion: BUILDER_INPUTS_SCHEMA_VERSION,
    releaseBundleId: options.releaseBundleId ?? CURRENT_CUSTOM_RELEASE,
    scenarioId: CUSTOM_SCENARIO,
    title: options.title ?? 'Custom card',
    physicianName: null,
    status: 'draft',
    catalogPicks: [],
    familyPicks: [],
    customItems: [],
    equipmentSets: [],
    input: {
      ...defaultBuildInput(CUSTOM_SCENARIO, {
        selectedModuleVersionIds: options.selectedModuleVersionIds,
      }),
      recipeVersionId: options.recipeVersionId ?? CURRENT_CUSTOM_RECIPE,
      selectedModuleVersionIds: options.selectedModuleVersionIds,
    },
  })
}

/** The real server-side save resolution — the exact path `saveUserCard` stores through. */
function resolveCustomCard(options: {
  selectedModuleVersionIds: string[]
  releaseBundleId?: string
  recipeVersionId?: string
}): ResolvedCard {
  const resolved = resolveForSave(customCardRequest(options), '2026-08-10T12:00:00.000Z')
  expect(resolved.ok).toBe(true)
  if (!resolved.ok) throw new Error(resolved.error)
  return resolved.card
}

function itemBySourceSlot(card: ResolvedCard, sourceSlotId: string): ResolvedCardItem {
  const item = card.items.find(
    (candidate) => candidate.sourceSlotId === sourceSlotId || candidate.id === sourceSlotId,
  )
  if (!item) throw new Error(`Expected slot ${sourceSlotId} on the resolved card.`)
  return item
}

function placement(card: ResolvedCard, sourceSlotId: string) {
  const item = itemBySourceSlot(card, sourceSlotId)
  return { id: sourceSlotId, zone: item.setupZone, phase: item.proceduralPhase }
}

describe('P91-C1 — F-04 reaches current custom cards through the real save path', () => {
  it('A: a current custom card with the EBUS-specific module resolves all four EBUS instruments to back_table / diagnostic', () => {
    const card = resolveCustomCard({ selectedModuleVersionIds: [EBUS_SPECIFIC_MODULE] })
    for (const sourceSlotId of EBUS_INSTRUMENT_SLOTS) {
      expect(placement(card, sourceSlotId)).toEqual({
        id: sourceSlotId,
        zone: 'back_table',
        phase: 'diagnostic',
      })
    }
  })

  it('B: a current custom card with the therapeutic-specific module resolves both instruments to back_table / diagnostic', () => {
    const card = resolveCustomCard({ selectedModuleVersionIds: [THERAPEUTIC_SPECIFIC_MODULE] })
    for (const sourceSlotId of THERAPEUTIC_INSTRUMENT_SLOTS) {
      expect(placement(card, sourceSlotId)).toEqual({
        id: sourceSlotId,
        zone: 'back_table',
        phase: 'diagnostic',
      })
    }
  })

  it('C: with both modules, all six resolve correctly and each appears exactly once', () => {
    const card = resolveCustomCard({
      selectedModuleVersionIds: [EBUS_SPECIFIC_MODULE, THERAPEUTIC_SPECIFIC_MODULE],
    })
    for (const sourceSlotId of ALL_SIX_INSTRUMENT_SLOTS) {
      expect(
        card.items.filter((item) => item.sourceSlotId === sourceSlotId || item.id === sourceSlotId),
      ).toHaveLength(1)
      expect(placement(card, sourceSlotId)).toEqual({
        id: sourceSlotId,
        zone: 'back_table',
        phase: 'diagnostic',
      })
    }
  })

  it('D: a custom card without either module carries no unmatched-action warning and no ambiguity block', () => {
    const card = resolveCustomCard({ selectedModuleVersionIds: [CHEST_TUBE_SPECIFIC_MODULE] })
    const actionMessages = card.warnings.filter(
      (warning) =>
        warning.code === 'recipe_composition_action_unmatched' ||
        warning.code === 'recipe_composition_action_ambiguous',
    )
    expect(actionMessages).toEqual([])
    for (const sourceSlotId of ALL_SIX_INSTRUMENT_SLOTS) {
      expect(
        card.items.some((item) => item.sourceSlotId === sourceSlotId || item.id === sourceSlotId),
      ).toBe(false)
    }
  })

  it('E: a card pinned to the prior custom release still resolves the six instruments at the specimen station', () => {
    // The historical guarantee: the correction is a forward release, and a card saved before
    // it re-resolves against the definitions its author reviewed — pre-correction zones and
    // all — through the retained recipe in the composition ledger.
    const card = resolveCustomCard({
      releaseBundleId: PRIOR_CUSTOM_RELEASE,
      recipeVersionId: PRIOR_CUSTOM_RECIPE,
      selectedModuleVersionIds: [EBUS_SPECIFIC_MODULE, THERAPEUTIC_SPECIFIC_MODULE],
    })
    for (const sourceSlotId of ALL_SIX_INSTRUMENT_SLOTS) {
      expect(placement(card, sourceSlotId)).toEqual({
        id: sourceSlotId,
        zone: 'specimen_station',
        phase: 'specimen_handling',
      })
    }
  })

  it('applies the P91-C2 insertable-device placements on a custom card selecting the thoracoscopy module', () => {
    // The same save-path proof as A/B/C, for the two MED_THORACOSCOPY per-slot overrides the
    // custom composition carries: the insertables sit at the sterile field while the actual
    // drainage-preparation hardware keeps the intended F-05 pre-induction placement.
    const card = resolveCustomCard({
      selectedModuleVersionIds: [MED_THORACOSCOPY_SPECIFIC_MODULE],
    })
    for (const sourceSlotId of [THORACOSCOPY_CHEST_TUBE_SLOT, THORACOSCOPY_IPC_KIT_SLOT]) {
      expect(placement(card, sourceSlotId)).toEqual({
        id: sourceSlotId,
        zone: 'sterile_field',
        phase: 'therapeutic',
      })
    }
    expect(placement(card, THORACOSCOPY_DRAINAGE_UNIT_SLOT)).toEqual({
      id: THORACOSCOPY_DRAINAGE_UNIT_SLOT,
      zone: 'equipment_tower',
      phase: 'pre_induction_or_sedation',
    })
  })

  it('F: negative controls — specimen handling stays at the bench, correct accessories stay put, dressing stays post-procedure', () => {
    const card = resolveCustomCard({
      selectedModuleVersionIds: [
        EBUS_SPECIFIC_MODULE,
        THERAPEUTIC_SPECIFIC_MODULE,
        CHEST_TUBE_SPECIFIC_MODULE,
      ],
    })
    // Specimen receptacles, slides/cell-block/formalin, and the airway wash/BAL trap the
    // owner explicitly kept at the bench.
    for (const sourceSlotId of ['SLOT-12ACA27E54', 'SLOT-76F4405D68', 'SLOT-0F8FA96C28']) {
      expect(placement(card, sourceSlotId)).toEqual({
        id: sourceSlotId,
        zone: 'specimen_station',
        phase: 'specimen_handling',
      })
    }
    // EBUS balloon and needle adapter were already correct at back_table / diagnostic.
    for (const sourceSlotId of ['SLOT-93655BF7C4', 'SLOT-CD12842559']) {
      expect(placement(card, sourceSlotId)).toEqual({
        id: sourceSlotId,
        zone: 'back_table',
        phase: 'diagnostic',
      })
    }
    // Chest-tube dressing/securement stays post-procedure.
    expect(itemBySourceSlot(card, 'SLOT-4BE1D79D6C').proceduralPhase).toBe('post_procedure')
  })

  it('G: a newly saved custom card serializes the corrected placements and reopens identically', async () => {
    const request = customCardRequest({
      selectedModuleVersionIds: [EBUS_SPECIFIC_MODULE, THERAPEUTIC_SPECIFIC_MODULE],
      title: 'Corrected custom card',
    })
    const saved = await saveUserCard(request)
    expect(saved.ok).toBe(true)

    const record = await loadUserCard(saved.data as string)
    expect(record).not.toBeNull()
    // The stored snapshot itself carries the corrected values…
    for (const sourceSlotId of ALL_SIX_INSTRUMENT_SLOTS) {
      expect(placement(record!.card, sourceSlotId)).toEqual({
        id: sourceSlotId,
        zone: 'back_table',
        phase: 'diagnostic',
      })
    }
    // …the snapshot verifies against its hash…
    const row = tables.cards.find((candidate) => candidate.id === saved.data)!
    expect(parsePersistedSnapshot(row.card_snapshot, row.snapshot_hash)).not.toBeNull()
    // …and re-resolving the stored inputs reproduces the identical snapshot hash, so a
    // reopened card is the card that was saved.
    const reResolved = resolveForSave(request, '2026-08-11T09:00:00.000Z')
    expect(reResolved.ok).toBe(true)
    if (!reResolved.ok) return
    expect(reResolved.card.snapshotHash).toBe(record!.card.snapshotHash)
  })

  it('H: the pointer advance never reaches back into a card pinned to the prior release', async () => {
    // New custom cards start from the corrected release…
    expect(getCurrentReleaseBundleForScenario(CUSTOM_SCENARIO)?.id).toBe(CURRENT_CUSTOM_RELEASE)

    // …while the prior release resolves exactly its own retained recipe, with no actions.
    const prior = resolveReleaseDefinitions(PRIOR_CUSTOM_RELEASE)
    expect(prior.ok).toBe(true)
    if (!prior.ok) return
    expect(prior.sources.recipe.id).toBe(PRIOR_CUSTOM_RECIPE)
    expect(prior.sources.recipe.compositionActions).toEqual([])

    const context = buildReleaseContext(PRIOR_CUSTOM_RELEASE)
    expect(context.ok).toBe(true)
    if (!context.ok) return
    expect(context.context.recipe.id).toBe(PRIOR_CUSTOM_RECIPE)

    // Duplicating a v1-1-pinned card copies its stored inputs verbatim — the duplicate stays
    // pinned to the prior release rather than being silently re-pinned to the new one.
    const saved = await saveUserCard(
      customCardRequest({
        releaseBundleId: PRIOR_CUSTOM_RELEASE,
        recipeVersionId: PRIOR_CUSTOM_RECIPE,
        selectedModuleVersionIds: [EBUS_SPECIFIC_MODULE],
        title: 'Prior-release custom card',
      }),
    )
    expect(saved.ok).toBe(true)
    const duplicated = await duplicateUserCard(saved.data as string, 'Copy of prior-release card')
    expect(duplicated.ok).toBe(true)
    const copy = await loadUserCard(duplicated.data as string)
    expect(copy).not.toBeNull()
    expect(copy!.builderInputs?.releaseBundleId).toBe(PRIOR_CUSTOM_RELEASE)
    expect(copy!.builderInputs?.input.recipeVersionId).toBe(PRIOR_CUSTOM_RECIPE)
  })
})

describe('the optional-target action semantics the custom correction rides on', () => {
  const baseModule = {
    id: 'module-test-v1-0',
    code: 'TEST_MODULE',
    name: 'Test module',
    description: 'Synthetic.',
    version: '1.0',
    kind: 'procedure_specific' as const,
    governanceState: 'draft' as const,
    clinicalOwner: null,
    operationalOwner: null,
    catalogImportId: 'test',
    slots: [] as RecipeSlot[],
  }

  function slot(id: string, requirementKey: string): RecipeSlot {
    return {
      id,
      sourceSlotId: id,
      requirementKey,
      roleCode: 'TEST_ROLE',
      label: `Requirement ${id}`,
      genericRequirement: 'Synthetic.',
      requiredness: 'required',
      dependencyRule: null,
      quantityExpression: { op: 'literal', value: 1 },
      selectionMode: 'single',
      setupZone: 'back_table',
      proceduralPhase: 'diagnostic',
      setupSequence: 1,
      openHoldStatus: 'open_or_set_up_now',
      responsibleRole: null,
      sterileStatus: null,
      allowCustom: false,
      notes: null,
      includedBy: 'Included by Test module v1.0',
    }
  }

  function expand(input: {
    recipe?: Partial<RecipeVersion>
    modules?: RecipeModuleVersion[]
    selectedModuleVersionIds?: string[]
  }) {
    return expandRecipeComposition({
      recipe: {
        id: 'recipe-test-v1-0',
        sourceProcedureCode: 'TEST',
        sourceTemplateVersion: '1.0',
        name: 'Test recipe',
        version: '1.0',
        governanceState: 'draft',
        clinicalOwner: null,
        operationalOwner: null,
        catalogImportId: 'test',
        slots: [],
        allowedModifierCodes: [],
        moduleReferences: [
          { moduleVersionId: baseModule.id, selectionBehavior: 'optional', sequence: 10 },
        ],
        compositionActions: [],
        requirementSequences: {},
        ...input.recipe,
      },
      modules: input.modules ?? [{ ...baseModule, slots: [slot('SLOT-TEST-1', 'SLOT-TEST-1')] }],
      selectedModuleVersionIds: input.selectedModuleVersionIds ?? [],
      startSequence: 1,
    })
  }

  const zoneAction = (overrides: Record<string, unknown>) => ({
    id: 'test-action',
    sequence: 10,
    actionType: 'set_setup_zone' as const,
    targetSlotId: 'SLOT-TEST-1',
    payload: { value: 'mayo_stand' },
    ...overrides,
  })

  it('silently skips an optional-target action whose target module is not selected', () => {
    const result = expand({
      recipe: { compositionActions: [zoneAction({ optionalTarget: true })] } as never,
      selectedModuleVersionIds: [],
    })
    expect(result.messages).toEqual([])
    expect(result.trace.filter((event) => event.message.includes('test-action'))).toEqual([])
  })

  it('applies the same action when the target module is selected', () => {
    const result = expand({
      recipe: { compositionActions: [zoneAction({ optionalTarget: true })] } as never,
      selectedModuleVersionIds: [baseModule.id],
    })
    expect(result.messages).toEqual([])
    expect(result.slots[0].setupZone).toBe('mayo_stand')
  })

  it('still warns on an unmatched action that does NOT declare an optional target', () => {
    const result = expand({
      recipe: { compositionActions: [zoneAction({})] } as never,
      selectedModuleVersionIds: [],
    })
    expect(result.messages.map((message) => message.code)).toEqual([
      'recipe_composition_action_unmatched',
    ])
  })

  it('blocks loudly when an optional-target action matches more than one requirement', () => {
    const ambiguous = expand({
      recipe: {
        compositionActions: [
          zoneAction({
            optionalTarget: true,
            targetRoleCode: 'TEST_ROLE',
            targetSlotId: undefined,
          }),
        ],
      } as never,
      modules: [
        {
          ...baseModule,
          slots: [slot('SLOT-TEST-1', 'SLOT-TEST-1'), slot('SLOT-TEST-2', 'SLOT-TEST-2')],
        },
      ],
      selectedModuleVersionIds: [baseModule.id],
    })
    const blocking = ambiguous.messages.filter((message) => message.severity === 'blocking')
    expect(blocking.map((message) => message.code)).toEqual(['recipe_composition_action_ambiguous'])
    // Neither slot was modified: an ambiguous statement is refused, not half-applied.
    expect(ambiguous.slots.map((candidate) => candidate.setupZone)).toEqual([
      'back_table',
      'back_table',
    ])
  })
})

describe('P91-C2 — the MED_THORACOSCOPY insertable devices leave the over-broad F-05 re-phase', () => {
  function expandedSlots(recipeVersionId: string): RecipeSlot[] {
    const sources = getReleaseDefinitionSources(recipeVersionId, CONTRACT)
    if (!sources) throw new Error(`Recipe version ${recipeVersionId} did not resolve.`)
    const result = expandRecipeComposition({
      recipe: sources.recipe,
      modules: sources.modules,
      selectedModuleVersionIds: sources.recipe.moduleReferences.map(
        (reference) => reference.moduleVersionId,
      ),
      startSequence: 1,
    })
    expect(result.messages.filter((message) => message.severity === 'blocking')).toEqual([])
    return result.slots
  }

  function bySourceSlotId(slots: RecipeSlot[], sourceSlotId: string): RecipeSlot {
    const hit = slots.find((candidate) => candidate.sourceSlotId === sourceSlotId)
    if (!hit) throw new Error(`Expected slot ${sourceSlotId} in the expansion.`)
    return hit
  }

  it('B/C: both insertable devices resolve to sterile_field / therapeutic on the current recipe', () => {
    const slots = expandedSlots('recipe-med-thoracoscopy-v0-3')
    for (const sourceSlotId of [THORACOSCOPY_CHEST_TUBE_SLOT, THORACOSCOPY_IPC_KIT_SLOT]) {
      const slot = bySourceSlotId(slots, sourceSlotId)
      expect({ id: sourceSlotId, zone: slot.setupZone, phase: slot.proceduralPhase }).toEqual({
        id: sourceSlotId,
        zone: 'sterile_field',
        phase: 'therapeutic',
      })
    }
  })

  it('A: the intended F-05 move stands — actual drainage preparation stays pre-induction', () => {
    const slots = expandedSlots('recipe-med-thoracoscopy-v0-3')
    const drainageUnit = bySourceSlotId(slots, THORACOSCOPY_DRAINAGE_UNIT_SLOT)
    expect(drainageUnit.setupZone).toBe('equipment_tower')
    expect(drainageUnit.proceduralPhase).toBe('pre_induction_or_sedation')
  })

  it('the cited governed precedents actually hold on their home procedures', () => {
    // The two overrides are copied from these rows, not derived from general clinical
    // knowledge. If either precedent moves, this correction must be re-reviewed.
    const chestTube = bySourceSlotId(expandedSlots('recipe-chest-tube-v0-2'), 'SLOT-708736B8C2')
    expect(chestTube.roleCode).toBe('CHEST_TUBE_SMALL_BORE')
    expect(chestTube.setupZone).toBe('sterile_field')
    expect(chestTube.proceduralPhase).toBe('therapeutic')

    const ipcKit = bySourceSlotId(expandedSlots('recipe-ipc-placement-v0-2'), 'SLOT-1BCF3D0702')
    expect(ipcKit.roleCode).toBe('IPC_INSERTION_KIT')
    expect(ipcKit.setupZone).toBe('sterile_field')
    expect(ipcKit.proceduralPhase).toBe('therapeutic')
  })

  it('D/F/H: v0-3 differs from v0-2 by exactly the two slots, and on those by exactly zone and phase', () => {
    const before = new Map(expandedSlots('recipe-med-thoracoscopy-v0-2').map((s) => [s.id, s]))
    const after = new Map(expandedSlots('recipe-med-thoracoscopy-v0-3').map((s) => [s.id, s]))
    expect([...after.keys()].sort()).toEqual([...before.keys()].sort())

    const overridden = new Set([THORACOSCOPY_CHEST_TUBE_SLOT, THORACOSCOPY_IPC_KIT_SLOT])
    for (const [id, slotAfter] of after) {
      const slotBefore = before.get(id)!
      const strip = (candidate: RecipeSlot) => {
        // `includedBy` narrates the applied actions and the recipe name; identity and
        // provenance aside, every authored field must be compared.
        const rest: Partial<RecipeSlot> = { ...candidate }
        delete rest.includedBy
        return rest
      }
      if (overridden.has(slotBefore.sourceSlotId as string)) {
        expect(slotAfter.setupZone).toBe('sterile_field')
        expect(slotAfter.proceduralPhase).toBe('therapeutic')
        expect(strip(slotAfter)).toEqual({
          ...strip(slotBefore),
          setupZone: 'sterile_field',
          proceduralPhase: 'therapeutic',
        })
        // Dependency rule, requiredness, label, role, options untouched — stated explicitly.
        expect(slotAfter.dependencyRule).toBe(slotBefore.dependencyRule)
        expect(slotAfter.requiredness).toBe(slotBefore.requiredness)
        expect(slotAfter.label).toBe(slotBefore.label)
        expect(slotAfter.roleCode).toBe(slotBefore.roleCode)
      } else {
        expect(strip(slotAfter)).toEqual(strip(slotBefore))
      }
    }
  })

  it('E: dressing has no MED_THORACOSCOPY row, and the pleural dressing rows stay post-procedure', () => {
    // MED_THORACOSCOPY's template has no Dressing-section row of its own; the governed
    // dressing rows live on CHEST_TUBE and IPC_PLACEMENT and must stay post-procedure.
    const chestTubeDressing = bySourceSlotId(
      expandedSlots('recipe-chest-tube-v0-2'),
      'SLOT-4BE1D79D6C',
    )
    expect(chestTubeDressing.proceduralPhase).toBe('post_procedure')
    const ipcDressing = bySourceSlotId(
      expandedSlots('recipe-ipc-placement-v0-2'),
      'SLOT-01010CB364',
    )
    expect(ipcDressing.proceduralPhase).toBe('post_procedure')
  })

  it('G: the superseded v0-2 recipe still reconstructs the over-broad placement it published', () => {
    const slots = expandedSlots('recipe-med-thoracoscopy-v0-2')
    for (const sourceSlotId of [
      THORACOSCOPY_CHEST_TUBE_SLOT,
      THORACOSCOPY_IPC_KIT_SLOT,
      THORACOSCOPY_DRAINAGE_UNIT_SLOT,
    ]) {
      const slot = bySourceSlotId(slots, sourceSlotId)
      expect(slot.setupZone).toBe('equipment_tower')
      expect(slot.proceduralPhase).toBe('pre_induction_or_sedation')
    }
  })

  it('H: the release diff for v1-1 → v1-2 is exactly the two slot overrides', () => {
    const previous = resolveReleaseDefinitions('release-med-thoracoscopy-v1-1')
    const next = resolveReleaseDefinitions('release-med-thoracoscopy-v1-2')
    expect(previous.ok && next.ok).toBe(true)
    if (!previous.ok || !next.ok) return

    const report = diffReleaseBundles(
      { bundle: previous.bundle, sources: previous.sources },
      { bundle: next.bundle, sources: next.sources },
    )
    expect(report.requirementChanges).toEqual([
      {
        requirementKey: THORACOSCOPY_CHEST_TUBE_SLOT,
        kind: 'changed',
        moduleVersionIds: [MED_THORACOSCOPY_SPECIFIC_MODULE],
        changedFields: ['setupZone', 'proceduralPhase'],
      },
      {
        requirementKey: THORACOSCOPY_IPC_KIT_SLOT,
        kind: 'changed',
        moduleVersionIds: [MED_THORACOSCOPY_SPECIFIC_MODULE],
        changedFields: ['setupZone', 'proceduralPhase'],
      },
    ])
    expect(report.modifierEffectChanges).toEqual([])
    // Only the recipe pin moves; the module pins and the four set pins are unchanged.
    expect(report.pinChanges.map((change) => change.pin).sort()).toEqual([
      'recipe:recipe-med-thoracoscopy-v0-2',
      'recipe:recipe-med-thoracoscopy-v0-3',
    ])
  })
})

describe('P91-C3 — the canonical release-impact report diffs the final effective recipes', () => {
  const reportsById = new Map(
    getReleaseImpactReports().map((report) => [report.nextReleaseBundleId, report]),
  )

  it('names all six F-04 corrections in the procedure supersession rows', () => {
    const ebus = reportsById.get('release-ebus-tbna-v1-1')!
    for (const sourceSlotId of EBUS_INSTRUMENT_SLOTS) {
      expect(ebus.requirementChanges).toContainEqual(
        expect.objectContaining({
          requirementKey: sourceSlotId,
          kind: 'changed',
          changedFields: ['setupZone', 'proceduralPhase'],
        }),
      )
    }
    const therapeutic = reportsById.get('release-therapeutic-bronch-v1-1')!
    for (const sourceSlotId of THERAPEUTIC_INSTRUMENT_SLOTS) {
      expect(therapeutic.requirementChanges).toContainEqual(
        expect.objectContaining({
          requirementKey: sourceSlotId,
          kind: 'changed',
          changedFields: ['setupZone', 'proceduralPhase'],
        }),
      )
    }
  })

  it('names all six F-04 corrections and both P91-C2 overrides in the custom supersession row', () => {
    const custom = reportsById.get(CURRENT_CUSTOM_RELEASE)!
    expect(custom.previousReleaseBundleId).toBe(PRIOR_CUSTOM_RELEASE)
    for (const sourceSlotId of [
      ...ALL_SIX_INSTRUMENT_SLOTS,
      THORACOSCOPY_CHEST_TUBE_SLOT,
      THORACOSCOPY_IPC_KIT_SLOT,
    ]) {
      expect(custom.requirementChanges).toContainEqual(
        expect.objectContaining({
          requirementKey: sourceSlotId,
          kind: 'changed',
          changedFields: ['setupZone', 'proceduralPhase'],
        }),
      )
    }
    expect(custom.requirementChanges).toHaveLength(8)
  })

  it('reproduces the committed artifact from the live domain diff (generator faithfulness)', () => {
    const previous = resolveReleaseDefinitions('release-ebus-tbna-v1-0')
    const next = resolveReleaseDefinitions('release-ebus-tbna-v1-1')
    expect(previous.ok && next.ok).toBe(true)
    if (!previous.ok || !next.ok) return
    const fresh = diffReleaseBundles(
      { bundle: previous.bundle, sources: previous.sources },
      { bundle: next.bundle, sources: next.sources },
    )
    expect(fresh).toEqual(reportsById.get('release-ebus-tbna-v1-1'))
  })

  it('keeps the six corrected instruments out of the v1-0 → v1-1 custom row, where nothing changed them', () => {
    // Both v1-0 and v1-1 custom recipes carry no actions, so the six instruments were
    // identical across that supersession; they must appear only where they actually changed.
    const custom = reportsById.get(PRIOR_CUSTOM_RELEASE)!
    for (const sourceSlotId of ALL_SIX_INSTRUMENT_SLOTS) {
      expect(
        custom.requirementChanges.some((change) => change.requirementKey === sourceSlotId),
      ).toBe(false)
    }
  })

  it('reports a composition-action-only revision as a requirement change (effective boundary proof)', () => {
    // Two synthetic sources over the SAME module content, differing only by one
    // set_setup_zone action — the exact shape the raw-slot diff was blind to.
    const sources = getReleaseDefinitionSources('recipe-med-thoracoscopy-v0-2', CONTRACT)!
    const previous = resolveReleaseDefinitions('release-med-thoracoscopy-v1-1')
    expect(previous.ok).toBe(true)
    if (!previous.ok) return
    const revised = {
      ...sources,
      recipe: {
        ...sources.recipe,
        compositionActions: [
          {
            id: 'synthetic-zone-move',
            sequence: 10,
            actionType: 'set_setup_zone' as const,
            targetSlotId: THORACOSCOPY_DRAINAGE_UNIT_SLOT,
            payload: { value: 'back_table' },
          },
        ],
      },
    }
    const report = diffReleaseBundles(
      { bundle: previous.bundle, sources: previous.sources },
      { bundle: previous.bundle, sources: revised },
    )
    expect(report.requirementChanges).toEqual([
      {
        requirementKey: THORACOSCOPY_DRAINAGE_UNIT_SLOT,
        kind: 'changed',
        moduleVersionIds: [MED_THORACOSCOPY_SPECIFIC_MODULE],
        changedFields: ['setupZone'],
      },
    ])
  })
})

describe('P91-C3 — authored modifier-effect changes are reported, not just a set-pin hash', () => {
  it('reports the modifier-added requirement going required → conditional with its dependency rule', () => {
    const fixture = createModifierRevisionFixture()
    const report = diffReleaseBundles(fixture.previous, fixture.next)

    // The base recipe is untouched — the change lives entirely in the modifier set…
    expect(report.requirementChanges).toEqual([])
    expect(report.pinChanges.map((change) => change.pin)).toEqual(['definition-set-modifiers'])
    // …and the report still names the requirement-level effect instead of only the hash.
    expect(report.identical).toBe(false)
    expect(report.modifierEffectChanges).toEqual([
      expect.objectContaining({
        sourceKind: 'modifier',
        modifierCode: MODIFIER_REVISION_MODIFIER_CODE,
        actionId: MODIFIER_REVISION_ACTION_ID,
        actionType: 'add_slot',
        kind: 'changed',
        requirementKey: MODIFIER_REVISION_REQUIREMENT_KEY,
        changedFields: ['dependencyRule', 'requiredness'],
        before: expect.objectContaining({ requiredness: 'required', dependencyRule: null }),
        after: expect.objectContaining({
          requiredness: 'conditional',
          dependencyRule: MODIFIER_REVISION_DEPENDENCY_RULE,
        }),
      }),
    ])
    expect(report.previousReleaseBundleId).toBe(MODIFIER_REVISION_OLD_RELEASE_ID)
    expect(report.nextReleaseBundleId).toBe(MODIFIER_REVISION_NEW_RELEASE_ID)
  })

  it('reports a modifier leaving the selectable offer as a first-class row, even with zero actions', () => {
    // Withdrawing a modifier from `allowedModifierCodes` must never read as a bare pin move
    // (zero-action modifiers) or as its actions being deleted from the set (acting ones).
    const fixture = createModifierRevisionFixture()
    const next = {
      bundle: fixture.next.bundle,
      sources: {
        ...fixture.next.sources,
        recipe: {
          ...fixture.next.sources.recipe,
          allowedModifierCodes: fixture.next.sources.recipe.allowedModifierCodes.filter(
            (code) => code !== MODIFIER_REVISION_MODIFIER_CODE,
          ),
        },
      },
    }
    const report = diffReleaseBundles(fixture.previous, next)
    expect(report.modifierEffectChanges).toContainEqual(
      expect.objectContaining({
        sourceKind: 'modifier',
        modifierCode: MODIFIER_REVISION_MODIFIER_CODE,
        actionId: null,
        kind: 'removed',
        changedFields: ['offered'],
        before: { offered: true, actionCount: 1 },
        after: null,
      }),
    )
  })

  it('scopes the modifier layer to modifiers the procedure offers', () => {
    const fixture = createModifierRevisionFixture()
    const withoutOffer = (candidate: typeof fixture.previous) => ({
      bundle: candidate.bundle,
      sources: {
        ...candidate.sources,
        recipe: {
          ...candidate.sources.recipe,
          allowedModifierCodes: candidate.sources.recipe.allowedModifierCodes.filter(
            (code) => code !== MODIFIER_REVISION_MODIFIER_CODE,
          ),
        },
      },
    })
    const report = diffReleaseBundles(withoutOffer(fixture.previous), withoutOffer(fixture.next))
    // The set pin still moves — nothing is hidden — but there is no authored effect to
    // report for a modifier no card of this procedure may select.
    expect(report.pinChanges.map((change) => change.pin)).toEqual(['definition-set-modifiers'])
    expect(report.modifierEffectChanges).toEqual([])
  })

  it('carries an empty modifier layer on every committed report today, because the sets are identical', () => {
    // The current data has one modifier set shared by every release, so any non-empty entry
    // here would be an invented change. The layer becomes populated when a release genuinely
    // revises the set — the PR #92 F-09 shape the fixture above mirrors.
    for (const report of getReleaseImpactReports()) {
      expect(report.modifierEffectChanges).toEqual([])
    }
  })
})

describe('P91-C4b — no governed expansion carries a blank dependency rule', () => {
  it('every live recipe, expanded with every offered module, yields only meaningful rules', () => {
    // The schema-level proof is the throw at every boundary; this is the data-level proof
    // over the committed governed content itself: a conditional requirement whose condition
    // is whitespace can neither be authored (the loaders refuse it) nor already exist here.
    const live = getLiveRecipeVersions()
    expect(live.size).toBeGreaterThan(0)
    for (const recipe of live.values()) {
      const sources = getReleaseDefinitionSources(recipe.id, CONTRACT)
      expect(sources).not.toBeNull()
      const { slots } = expandRecipeComposition({
        recipe: sources!.recipe,
        modules: sources!.modules,
        selectedModuleVersionIds: sources!.modules.map((moduleVersion) => moduleVersion.id),
        startSequence: 1,
      })
      expect(slots.length).toBeGreaterThan(0)
      for (const slot of slots) {
        if (slot.dependencyRule !== null) {
          expect(slot.dependencyRule.trim()).not.toBe('')
        }
      }
    }
  })
})

describe('P91-C5 — an unknown modifier action type fails release impact loudly, never partially', () => {
  /** The fixture side with the revision modifier's actions swapped for `actions`. */
  function withRevisionModifierActions(
    side: ReturnType<typeof createModifierRevisionFixture>['next'],
    actions: ModifierAction[],
  ) {
    return {
      bundle: side.bundle,
      sources: {
        ...side.sources,
        modifiers: side.sources.modifiers.map(
          (definition): ModifierDefinition =>
            definition.code === MODIFIER_REVISION_MODIFIER_CODE
              ? { ...definition, actions }
              : definition,
        ),
      },
    }
  }

  it('diffReleaseBundles throws and names the action, its modifier, and the operation', () => {
    // The compile-time never-check used to *return* the unknown string at runtime, so a
    // set carrying an action type the summary does not know produced malformed
    // release-impact data instead of failing. Cast in, exactly as untrusted data would
    // arrive — the TypeScript union is not weakened.
    const fixture = createModifierRevisionFixture()
    const revisionModifier = fixture.next.sources.modifiers.find(
      (definition) => definition.code === MODIFIER_REVISION_MODIFIER_CODE,
    ) as ModifierDefinition
    const poisoned = withRevisionModifierActions(
      fixture.next,
      revisionModifier.actions.map((action) => ({
        ...action,
        actionType: 'future_unknown_action' as ModifierAction['actionType'],
      })),
    )
    // A throw is also the proof that no modifierEffectChanges rows are returned: the report
    // is never constructed.
    expect(() => diffReleaseBundles(fixture.previous, poisoned)).toThrow(
      `Unknown modifier action type "future_unknown_action" in action "${MODIFIER_REVISION_ACTION_ID}" ` +
        `while building release-impact evidence for modifier "${MODIFIER_REVISION_MODIFIER_CODE}".`,
    )
  })

  it('every current ModifierActionType routes through the effect summary — none reaches the default', () => {
    // Fourteen actions, one per authored type, changed only in `sequence` between the two
    // sides: the diff must summarize every one of them on both sides and report fourteen
    // changed rows. A type falling into the fail-loud default would abort the diff instead.
    const fixture = createModifierRevisionFixture()
    const actionsAt = (sequenceBase: number): ModifierAction[] =>
      modifierActionTypes.map((actionType, index) => ({
        id: `coverage-${actionType}`,
        modifierCode: MODIFIER_REVISION_MODIFIER_CODE,
        sequence: sequenceBase + index,
        actionType,
        targetSlotId: 'SLOT-COVERAGE',
        payload: {},
      }))
    const report = diffReleaseBundles(
      withRevisionModifierActions(fixture.previous, actionsAt(100)),
      withRevisionModifierActions(fixture.next, actionsAt(200)),
    )
    const coverageRows = report.modifierEffectChanges.filter(
      (change) => change.actionId?.startsWith('coverage-') ?? false,
    )
    expect(coverageRows).toHaveLength(modifierActionTypes.length)
    expect(new Set(coverageRows.map((change) => change.actionType))).toEqual(
      new Set(modifierActionTypes),
    )
    for (const row of coverageRows) {
      expect(row.kind).toBe('changed')
      expect(row.changedFields).toContain('sequence')
    }
  })
})

describe('publication integrity of the correction pass', () => {
  it('advances exactly the two intended pointers and no other', () => {
    expect(getReleasePointers()).toEqual({
      BRONCH_ABLATION: 'release-bronch-ablation-v1-0',
      CHEST_TUBE: 'release-chest-tube-v1-1',
      CUSTOM_COMPOSITION: 'release-custom-composition-v1-2',
      EBUS_TBNA: 'release-ebus-tbna-v1-1',
      EBV: 'release-ebv-v1-0',
      FLEX_DIAGNOSTIC: 'release-flex-diagnostic-v1-0',
      ICU_BRONCH: 'release-icu-bronch-v1-0',
      IPC_PLACEMENT: 'release-ipc-placement-v1-1',
      MED_THORACOSCOPY: 'release-med-thoracoscopy-v1-2',
      PERC_TRACH: 'release-perc-trach-v1-0',
      PHOTODYNAMIC_THERAPY: 'release-photodynamic-therapy-v1-0',
      RIGID_BRONCH: 'release-rigid-bronch-v1-0',
      TB_RULEOUT: 'release-tb-ruleout-v1-0',
      THERAPEUTIC_BRONCH: 'release-therapeutic-bronch-v1-1',
      THORACENTESIS: 'release-thoracentesis-v1-1',
      WLL: 'release-wll-v1-0',
    })
  })

  it('retains every superseded custom and MED_THORACOSCOPY recipe verbatim', () => {
    for (const recipeVersionId of [
      'recipe-custom-composition-v1-0',
      PRIOR_CUSTOM_RECIPE,
      'recipe-med-thoracoscopy-v0-1',
      'recipe-med-thoracoscopy-v0-2',
    ]) {
      expect(recipeForRecipeVersionId(recipeVersionId)).not.toBeNull()
    }
  })
})
