#!/usr/bin/env python3
"""Build the CT-derived, web-optimized animated cardiac teaching GLB.

Run with Blender:
  /Applications/Blender.app/Contents/MacOS/Blender --background --factory-startup \
    --python scripts/cardiac-assets/build-ct-heart.py

The Slicer source is in LPS millimetres. Geometry is baked into the same normalized,
Y-up web frame generated by build-ct-centerlines.mjs. The animation is an educational
global cardiac-cycle deformation, not a patient-specific motion reconstruction.
"""

from __future__ import annotations

import json
import shutil
import struct
import subprocess
import tempfile
from pathlib import Path
from typing import Iterable, Sequence

import bpy
from mathutils import Vector


ROOT = Path(__file__).resolve().parents[2]
SCRIPT_DIRECTORY = Path(__file__).resolve().parent
CONFIG = json.loads((SCRIPT_DIRECTORY / "cardiac-ct-config.json").read_text())
SOURCE_PATH = ROOT / CONFIG["sourceModel"]
DETAILED_SEGMENTATION_PATH = ROOT / CONFIG["sourceDetailedSegmentation"]
VALVE_EXTRACTOR_PATH = SCRIPT_DIRECTORY / "extract-aortic-cusps.py"
OUTPUT_DIRECTORY = ROOT / "public" / "models" / "cardiac"
OUTPUT_PATH = OUTPUT_DIRECTORY / "heart-ct-animated-v1.glb"
COMPATIBILITY_ALIAS_PATH = OUTPUT_DIRECTORY / "heart-ct-animated.glb"
MANIFEST_PATH = OUTPUT_DIRECTORY / "ct-asset-manifest.json"

CENTER_LPS = Vector(CONFIG["centerLpsMm"])
WEB_UNITS_PER_MM = float(CONFIG["webUnitsPerMm"])


NODE_NAMES = {
    "brachiocephalic trunk": "CT_Aorta_Brachiocephalic",
    "left subclavian artery": "CT_Aorta_LeftSubclavian",
    "left common carotid artery": "CT_Aorta_LeftCarotid",
    "left brachiocephalic vein": "CT_LeftBrachiocephalicVein",
    "superior vena cava": "CT_SVC",
    "inferior vena cava": "CT_IVC",
    "aorta": "CT_Aorta",
    "left atrium": "CT_LA_Cavity",
    "left ventricle": "CT_LV_Cavity",
    "right atrium": "CT_RA_Cavity",
    "right ventricle": "CT_RV_Cavity",
    "Valve_Aortic": "CT_Valve_Aortic",
    "left_ventricular_outflow_tract": "CT_LVOT",
    "LV wall": "CT_LV_Myocardium",
    "Pulmonary Artery": "CT_PulmonaryArteries",
    "Right pulmonary vein": "CT_RightPulmonaryVeins",
    "Left pulmonary vein": "CT_LeftPulmonaryVeins",
    "Valve_Mitral": "CT_Landmark_MitralOrifice",
    "Valve_Tricuspid": "CT_Landmark_TricuspidOrifice",
    "Valve_Pulmonic": "CT_Landmark_PulmonicOrifice",
}


MATERIAL_SPECS = {
    "arterial": ((0.66, 0.075, 0.045, 0.62), 0.48, 0.02),
    "venous": ((0.035, 0.19, 0.48, 0.56), 0.5, 0.01),
    "left_chamber": ((0.76, 0.11, 0.075, 0.24), 0.36, 0.0),
    "right_chamber": ((0.045, 0.28, 0.66, 0.25), 0.38, 0.0),
    "myocardium": ((0.46, 0.035, 0.025, 0.48), 0.54, 0.0),
    "valve": ((0.92, 0.78, 0.49, 0.84), 0.42, 0.0),
    "lvot": ((0.88, 0.35, 0.22, 0.28), 0.42, 0.0),
}


OBJECT_MATERIAL = {
    "CT_Aorta_Brachiocephalic": "arterial",
    "CT_Aorta_LeftSubclavian": "arterial",
    "CT_Aorta_LeftCarotid": "arterial",
    "CT_Aorta": "arterial",
    "CT_RightPulmonaryVeins": "arterial",
    "CT_LeftPulmonaryVeins": "arterial",
    "CT_LeftBrachiocephalicVein": "venous",
    "CT_SVC": "venous",
    "CT_IVC": "venous",
    "CT_PulmonaryArteries": "venous",
    "CT_LA_Cavity": "left_chamber",
    "CT_LV_Cavity": "left_chamber",
    "CT_RA_Cavity": "right_chamber",
    "CT_RV_Cavity": "right_chamber",
    "CT_LV_Myocardium": "myocardium",
    "CT_LVOT": "lvot",
    "CT_Valve_Aortic": "valve",
}


# These three supplied segments locate their orifices but are not complete leaflet morphology.
# Their centroids remain as route-validation anchors; the surfaces are not learner-facing anatomy.
LOCATION_PROXY_SOURCE_NAMES = {"Valve_Mitral", "Valve_Tricuspid", "Valve_Pulmonic"}
EXCLUDED_SOURCE_NAMES = LOCATION_PROXY_SOURCE_NAMES | {
    "Valve_Aortic",
    "left brachiocephalic vein",
}

AORTIC_CUSP_FILES = {
    "CT_Valve_Aortic_RCC": "aortic-cusp-rcc.ply",
    "CT_Valve_Aortic_NCC": "aortic-cusp-ncc.ply",
    "CT_Valve_Aortic_LCC": "aortic-cusp-lcc.ply",
}


def clear_scene() -> None:
    bpy.ops.wm.read_factory_settings(use_empty=True)


def source_lps_from_imported_world(
    coordinate: Vector, millimetres_per_imported_unit: float
) -> Vector:
    """Convert an imported world coordinate back to source LPS millimetres."""

    return coordinate * millimetres_per_imported_unit


def normalized_blender_from_lps(point: Sequence[float]) -> Vector:
    """Return Blender Z-up coordinates that export as normalized web [L, S, -P]."""

    return (Vector(point) - CENTER_LPS) * WEB_UNITS_PER_MM


def bake_normalized_coordinates(
    mesh_object: bpy.types.Object, *, millimetres_per_imported_unit: float = 1000
) -> None:
    matrix = mesh_object.matrix_world.copy()
    normalized = []
    for vertex in mesh_object.data.vertices:
        source_lps = source_lps_from_imported_world(
            matrix @ vertex.co, millimetres_per_imported_unit
        )
        normalized.append(normalized_blender_from_lps(source_lps))
    mesh_object.parent = None
    mesh_object.matrix_world.identity()
    for vertex, coordinate in zip(mesh_object.data.vertices, normalized, strict=True):
        vertex.co = coordinate
    mesh_object.data.update()


def set_principled_input(node: bpy.types.Node, names: Iterable[str], value) -> None:
    for name in names:
        input_ = node.inputs.get(name)
        if input_ is not None:
            input_.default_value = value
            return


def make_material(name: str, spec_name: str) -> bpy.types.Material:
    color, roughness, metallic = MATERIAL_SPECS[spec_name]
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    material.diffuse_color = color
    principled = next(
        node for node in material.node_tree.nodes if node.type == "BSDF_PRINCIPLED"
    )
    set_principled_input(principled, ("Base Color",), color)
    set_principled_input(principled, ("Roughness",), roughness)
    set_principled_input(principled, ("Metallic IOR Level", "Metallic"), metallic)
    set_principled_input(principled, ("Alpha",), color[3])
    set_principled_input(principled, ("Coat Weight", "Clearcoat"), 0.12)
    if color[3] < 1:
        if hasattr(material, "surface_render_method"):
            material.surface_render_method = "DITHERED"
        if hasattr(material, "use_transparency_overlap"):
            material.use_transparency_overlap = False
    material["cardiac_tissue_class"] = spec_name
    return material


def apply_decimation(mesh_object: bpy.types.Object) -> None:
    triangles = len(mesh_object.data.polygons)
    if triangles < 2_500:
        return
    if mesh_object.name.startswith("CT_Valve_Aortic_"):
        ratio = 0.36
    elif mesh_object.name.startswith("CT_Valve_"):
        ratio = 0.82
    elif mesh_object.name in {"CT_LV_Myocardium", "CT_Aorta", "CT_PulmonaryArteries"}:
        ratio = 0.48
    elif triangles > 12_000:
        ratio = 0.52
    else:
        ratio = 0.62
    modifier = mesh_object.modifiers.new("Web topology budget", "DECIMATE")
    modifier.ratio = ratio
    modifier.use_collapse_triangulate = True
    bpy.context.view_layer.objects.active = mesh_object
    mesh_object.select_set(True)
    bpy.ops.object.modifier_apply(modifier=modifier.name)
    mesh_object.select_set(False)


def add_shape_key(
    mesh_object: bpy.types.Object,
    key_name: str,
    center_lps: Sequence[float],
    factors_lps: Sequence[float],
    frames: Sequence[tuple[int, float]],
) -> None:
    center = normalized_blender_from_lps(center_lps)
    mesh_object.shape_key_add(name="Basis")
    target = mesh_object.shape_key_add(name=key_name)
    factors = Vector(factors_lps)
    for source, destination in zip(mesh_object.data.vertices, target.data, strict=True):
        offset = source.co - center
        destination.co = center + Vector(
            (offset.x * factors.x, offset.y * factors.y, offset.z * factors.z)
        )
    target.value = 0

    shape_keys = mesh_object.data.shape_keys
    shape_keys.animation_data_create()
    action = bpy.data.actions.new(f"{mesh_object.name}_{key_name}")
    shape_keys.animation_data.action = action
    for frame, value in frames:
        target.value = value
        target.keyframe_insert(data_path="value", frame=frame, group=mesh_object.name)
    track = shape_keys.animation_data.nla_tracks.new()
    track.name = "CardiacCycle"
    track.strips.new(action.name, 0, action)
    shape_keys.animation_data.action = None


def add_cardiac_cycle(meshes: dict[str, bpy.types.Object]) -> None:
    ventricular_frames = (
        (0, 0.0),
        (3, 0.25),
        (6, 0.92),
        (10, 1.0),
        (17, 0.28),
        (23, 0.0),
        (48, 0.0),
    )
    atrial_frames = ((0, 0.0), (35, 0.0), (40, 0.25), (43, 1.0), (46, 0.18), (48, 0.0))
    arterial_frames = ((0, 0.0), (5, 0.0), (10, 1.0), (17, 0.2), (23, 0.0), (48, 0.0))

    deformation_specs = {
        "CT_LV_Cavity": (
            "Systole",
            (17.36, -191.6, -221.4),
            (0.975, 0.98, 0.992),
            ventricular_frames,
        ),
        "CT_RV_Cavity": (
            "Systole",
            (-2.95, -209.7, -209.7),
            (0.98, 0.982, 0.993),
            ventricular_frames,
        ),
        "CT_LV_Myocardium": (
            "Systole",
            (19.49, -191.7, -222.5),
            (0.985, 0.988, 0.995),
            ventricular_frames,
        ),
        "CT_LVOT": (
            "Systole",
            (-0.55, -174.7, -181.4),
            (0.99, 0.99, 0.996),
            ventricular_frames,
        ),
        "CT_LA_Cavity": (
            "AtrialKick",
            (-7.63, -148.0, -193.7),
            (0.985, 0.988, 0.988),
            atrial_frames,
        ),
        "CT_RA_Cavity": (
            "AtrialKick",
            (-27.96, -174.7, -196.5),
            (0.988, 0.985, 0.988),
            atrial_frames,
        ),
        "CT_Aorta": (
            "ArterialPulse",
            (-2.1, -169.0, -175.0),
            (1.003, 1.003, 1.001),
            arterial_frames,
        ),
        "CT_PulmonaryArteries": (
            "ArterialPulse",
            (6.0, -181.0, -157.0),
            (1.003, 1.003, 1.001),
            arterial_frames,
        ),
    }
    for object_name, (key_name, center, factors, frames) in deformation_specs.items():
        mesh_object = meshes.get(object_name)
        if mesh_object is not None:
            add_shape_key(mesh_object, key_name, center, factors, frames)

    valve_center = normalized_blender_from_lps((-3.407, -175.301, -176.114))
    valve_axis = (
        normalized_blender_from_lps((-8.277, -175.771, -165.869))
        - normalized_blender_from_lps((1.427, -176.975, -178.220))
    ).normalized()
    valve_frames = (
        (0, 0.0),
        (3, 0.0),
        (6, 0.82),
        (8, 1.0),
        (15, 0.96),
        (19, 0.12),
        (23, 0.0),
        (48, 0.0),
    )
    for object_name in AORTIC_CUSP_FILES:
        mesh_object = meshes.get(object_name)
        if mesh_object is None:
            continue
        mesh_object.shape_key_add(name="Basis")
        target = mesh_object.shape_key_add(name="ValveOpen")
        radial_offsets = []
        for vertex in mesh_object.data.vertices:
            offset = vertex.co - valve_center
            axial = valve_axis * offset.dot(valve_axis)
            radial_offsets.append((offset - axial).length)
        sorted_radii = sorted(radial_offsets)
        free_edge_radius = sorted_radii[round((len(sorted_radii) - 1) * 0.2)]
        attachment_radius = sorted_radii[round((len(sorted_radii) - 1) * 0.75)]
        radial_span = max(attachment_radius - free_edge_radius, 1e-6)
        for source, destination in zip(
            mesh_object.data.vertices, target.data, strict=True
        ):
            offset = source.co - valve_center
            axial = valve_axis * offset.dot(valve_axis)
            radial = offset - axial
            # The central free edge folds toward the sinus while the outer annular and
            # commissural attachment band remains fixed. This is coordinated illustrative
            # motion applied to the segmented static cusp, not patient-specific 4D motion.
            attachment_weight = max(
                0.0,
                min(1.0, (attachment_radius - radial.length) / radial_span),
            )
            attachment_weight = (
                attachment_weight * attachment_weight * (3.0 - 2.0 * attachment_weight)
            )
            opening_direction = radial.normalized() if radial.length > 1e-6 else radial
            destination.co = source.co + opening_direction * (0.14 * attachment_weight)
        target.value = 0
        shape_keys = mesh_object.data.shape_keys
        shape_keys.animation_data_create()
        action = bpy.data.actions.new(f"{mesh_object.name}_ValveOpen")
        shape_keys.animation_data.action = action
        for frame, value in valve_frames:
            target.value = value
            target.keyframe_insert(
                data_path="value", frame=frame, group=mesh_object.name
            )
        track = shape_keys.animation_data.nla_tracks.new()
        track.name = "CardiacCycle"
        track.strips.new(action.name, 0, action)
        shape_keys.animation_data.action = None


def import_segmented_aortic_cusps(
    material: bpy.types.Material,
) -> dict[str, bpy.types.Object]:
    if not DETAILED_SEGMENTATION_PATH.exists():
        raise FileNotFoundError(
            f"Missing detailed aortic-valve segmentation: {DETAILED_SEGMENTATION_PATH}"
        )
    python = shutil.which("python3")
    if python is None:
        raise RuntimeError("python3 is required to extract detailed aortic cusps")
    imported: dict[str, bpy.types.Object] = {}
    with tempfile.TemporaryDirectory(prefix="cardiac-aortic-cusps-") as temporary:
        temporary_path = Path(temporary)
        subprocess.run(
            [
                python,
                str(VALVE_EXTRACTOR_PATH),
                "--source",
                str(DETAILED_SEGMENTATION_PATH),
                "--output-dir",
                str(temporary_path),
            ],
            check=True,
        )
        for object_name, filename in AORTIC_CUSP_FILES.items():
            bpy.ops.wm.ply_import(filepath=str(temporary_path / filename))
            mesh_object = bpy.context.selected_objects[0]
            mesh_object.name = object_name
            mesh_object.data.name = f"{object_name}_Mesh"
            bake_normalized_coordinates(mesh_object, millimetres_per_imported_unit=1)
            apply_decimation(mesh_object)
            for polygon in mesh_object.data.polygons:
                polygon.use_smooth = True
            mesh_object.data.materials.clear()
            mesh_object.data.materials.append(material)
            mesh_object["source_structure"] = object_name.removeprefix(
                "CT_Valve_Aortic_"
            )
            mesh_object["source_coordinate_system"] = "LPS"
            mesh_object["source_segmentation"] = str(
                CONFIG["sourceDetailedSegmentation"]
            )
            imported[object_name] = mesh_object
    return imported


def add_landmark(
    name: str, point_lps: Sequence[float], parent: bpy.types.Object
) -> None:
    landmark = bpy.data.objects.new(name, None)
    landmark.empty_display_type = "SPHERE"
    landmark.empty_display_size = 0.055
    landmark.location = normalized_blender_from_lps(point_lps)
    landmark["cardiac_anchor"] = True
    bpy.context.collection.objects.link(landmark)
    landmark.parent = parent


def build_scene() -> None:
    clear_scene()
    if not SOURCE_PATH.exists():
        raise FileNotFoundError(f"Missing Slicer source model: {SOURCE_PATH}")
    bpy.ops.import_scene.gltf(filepath=str(SOURCE_PATH))

    for object_ in list(bpy.context.scene.objects):
        if object_.type == "MESH" and (
            object_.name.lower().startswith("trachea")
            or object_.name in EXCLUDED_SOURCE_NAMES
        ):
            bpy.data.objects.remove(object_, do_unlink=True)

    meshes: dict[str, bpy.types.Object] = {}
    materials = {
        spec_name: make_material(f"CT {spec_name.replace('_', ' ').title()}", spec_name)
        for spec_name in MATERIAL_SPECS
    }
    for object_ in [
        candidate for candidate in bpy.context.scene.objects if candidate.type == "MESH"
    ]:
        source_name = object_.name
        object_.name = NODE_NAMES.get(
            source_name, f"CT_{source_name.replace(' ', '_')}"
        )
        object_.data.name = f"{object_.name}_Mesh"
        bake_normalized_coordinates(object_)
        apply_decimation(object_)
        for polygon in object_.data.polygons:
            polygon.use_smooth = True
        object_.data.materials.clear()
        object_.data.materials.append(materials[OBJECT_MATERIAL[object_.name]])
        object_["source_structure"] = source_name
        object_["source_coordinate_system"] = "LPS"
        meshes[object_.name] = object_

    meshes.update(import_segmented_aortic_cusps(materials["valve"]))

    add_cardiac_cycle(meshes)

    root = bpy.data.objects.new("CT_Heart_Root", None)
    root["source"] = str(CONFIG["sourceModel"])
    root["source_units"] = "mm"
    root["source_coordinate_system"] = "LPS"
    root["animation_note"] = (
        "Educational cardiac-cycle deformation; not patient-specific motion"
    )
    root["valve_morphology_note"] = (
        "Right, non-coronary, and left aortic cusps come from separate complete segmentations; "
        "other valve source segments are location proxies and are excluded from displayed anatomy"
    )
    root["web_units_per_mm"] = WEB_UNITS_PER_MM
    root["center_lps_mm"] = list(CENTER_LPS)
    bpy.context.collection.objects.link(root)
    for mesh_object in meshes.values():
        mesh_object.parent = root

    landmarks = {
        "Anchor_AorticValve": (-3.407, -175.301, -176.114),
        "Anchor_TricuspidOrifice": (-19.26, -200.407, -227.198),
        "Anchor_PulmonicOrifice": (10.117, -203.881, -179.557),
        "Anchor_SVC_RA": (-34.027, -165.959, -172.227),
        "Anchor_IVC_RA": (-30.326, -157.543, -218.727),
        "Anchor_ImpellaInlet35mm": (14.297, -178.828, -205.5),
    }
    for name, point in landmarks.items():
        add_landmark(name, point, root)

    scene = bpy.context.scene
    scene.render.fps = 24
    scene.frame_start = 0
    scene.frame_end = 48
    scene.frame_set(0)


def read_glb_json(path: Path) -> dict:
    data = path.read_bytes()
    if data[:4] != b"glTF":
        raise ValueError(f"Not a GLB: {path}")
    offset = 12
    while offset < len(data):
        chunk_length, chunk_type = struct.unpack_from("<II", data, offset)
        if chunk_type == 0x4E4F534A:
            chunk = data[offset + 8 : offset + 8 + chunk_length]
            return json.loads(chunk.rstrip(b" \x00").decode("utf-8"))
        offset += 8 + chunk_length
    raise ValueError(f"No JSON chunk in {path}")


def export_runtime_asset() -> None:
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    bpy.ops.export_scene.gltf(
        filepath=str(OUTPUT_PATH),
        export_format="GLB",
        export_yup=True,
        export_morph=True,
        export_morph_animation=True,
        export_morph_normal=False,
        export_animations=True,
        export_animation_mode="NLA_TRACKS",
        export_merge_animation="NLA_TRACK",
        export_frame_range=True,
        export_extras=True,
        export_cameras=False,
        export_lights=False,
        export_draco_mesh_compression_enable=True,
        export_draco_mesh_compression_level=6,
        export_draco_position_quantization=14,
        export_draco_normal_quantization=10,
    )
    shutil.copy2(OUTPUT_PATH, COMPATIBILITY_ALIAS_PATH)

    document = read_glb_json(OUTPUT_PATH)
    accessors = document.get("accessors", [])
    triangles = sum(
        accessors[primitive["indices"]]["count"] // 3
        for mesh in document.get("meshes", [])
        for primitive in mesh.get("primitives", [])
        if primitive.get("mode", 4) == 4 and "indices" in primitive
    )
    manifest = {
        "schemaVersion": 1,
        "generatedBy": "scripts/cardiac-assets/build-ct-heart.py",
        "asset": {
            "url": "/models/cardiac/heart-ct-animated-v1.glb",
            "compatibilityAliases": [
                "/models/cardiac/heart-ct-animated.glb"
            ],
            "source": CONFIG["sourceModel"],
            "detailedValveSource": CONFIG["sourceDetailedSegmentation"],
            "aorticCuspSegments": [
                "right_coronary_cusp",
                "non_coronary_cusp",
                "left_coronary_cusp",
            ],
            "bytes": OUTPUT_PATH.stat().st_size,
            "triangles": triangles,
            "nodes": [
                node.get("name")
                for node in document.get("nodes", [])
                if node.get("name")
            ],
            "animations": [
                animation.get("name") for animation in document.get("animations", [])
            ],
            "dracoCompressed": "KHR_draco_mesh_compression"
            in document.get("extensionsUsed", []),
            "limits": {"bytes": 4_000_000, "triangles": 125_000},
        },
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")
    print(
        f"Built {OUTPUT_PATH.relative_to(ROOT)}: {triangles:,} triangles, "
        f"{OUTPUT_PATH.stat().st_size / 1_000_000:.2f} MB, "
        f"animations={manifest['asset']['animations']}"
    )


def main() -> None:
    build_scene()
    export_runtime_asset()


if __name__ == "__main__":
    main()
