import type { StentExplorerControl, StentExplorerStationId } from './types'

const qualitativeRange = (
  definition: Omit<
    Extract<StentExplorerControl, { kind: 'range' }>,
    'min' | 'max' | 'step' | 'valueLabels'
  > & {
    middleLabel: string
  },
) => {
  const { middleLabel, ...control } = definition
  return {
    ...control,
    min: 0,
    max: 1,
    step: 0.25,
    valueLabels: [
      { value: 0, label: control.minLabel },
      { value: 0.5, label: middleLabel },
      { value: 1, label: control.maxLabel },
    ],
  } satisfies StentExplorerControl
}

export const stentExplorerControlsByStation = {
  'architecture-lumen': [
    qualitativeRange({
      id: 'wall-occupancy',
      kind: 'range',
      label: 'Modeled wall occupancy',
      description:
        'Vary how much of one fixed outer envelope is occupied by generic construction material.',
      defaultValue: 0.75,
      minLabel: 'Lower occupancy',
      middleLabel: 'Intermediate occupancy',
      maxLabel: 'Greater occupancy',
      modifiers: [{ id: 'wallOccupancy' }],
    }),
    {
      id: 'comparison-reveal',
      kind: 'toggle',
      label: 'True-scale comparison',
      description: 'Place the same-outer-envelope cross-sections beside one another.',
      defaultValue: true,
      offLabel: 'Single cross-section',
      onLabel: 'Side-by-side comparison',
      modifiers: [{ id: 'comparisonReveal' }],
    },
  ],
  'metal-architecture': [
    {
      id: 'constraint-pathway',
      kind: 'preset',
      label: 'Imposed constraint',
      description:
        'Apply the same qualitative displacement pathway while keeping force and tissue pressure unmodeled.',
      defaultValue: 'diameter-change',
      options: [
        {
          id: 'diameter-change',
          label: 'Diameter change and release',
          description: 'Follow radial reconfiguration, length coupling, and recovery.',
          modifiers: { radialConstraint: 1 },
        },
        {
          id: 'curve-bending',
          label: 'Curved-airway bending',
          description: 'Follow crossing motion, loop opening, or connector hinging along a curve.',
          modifiers: { bendConstraint: 1 },
        },
        {
          id: 'eccentric-constraint',
          label: 'Eccentric constraint',
          description: 'Follow ovalization and local load-path redistribution.',
          modifiers: { ovalConstraint: 1 },
        },
      ],
    },
    qualitativeRange({
      id: 'constraint-amplitude',
      kind: 'range',
      label: 'Visible displacement',
      description:
        'Change the amplified geometric displacement without converting it into force, stiffness, or collapse pressure.',
      defaultValue: 0.75,
      minLabel: 'Subtle displacement',
      middleLabel: 'Visible displacement',
      maxLabel: 'Amplified displacement',
      modifiers: [{ id: 'constraintAmplitude' }],
    }),
    {
      architectureIds: [
        'hook-cross-covered',
        'laser-cut-covered',
        'single-wire-knit-partial-cover',
      ],
      id: 'cover-inspection',
      kind: 'toggle',
      label: 'Show covering layer',
      description:
        'Reveal or hide the generic cover for inspection; hiding it does not change the selected device configuration.',
      defaultValue: true,
      offLabel: 'Scaffold inspection',
      onLabel: 'Cover visible',
      modifiers: [{ id: 'coverInspection' }],
    },
    {
      id: 'load-path-markers',
      kind: 'toggle',
      label: 'Load-path markers',
      description:
        'Mark crossings, connectors, or strand transitions without predicting a failure location.',
      defaultValue: true,
      offLabel: 'Markers hidden',
      onLabel: 'Markers visible',
      modifiers: [{ id: 'structuralHotspot' }],
    },
  ],
  'cough-motion': [
    qualitativeRange({
      id: 'motion-amplitude',
      kind: 'range',
      label: 'Amplified displacement',
      description:
        'Change the visible displacement pulse to compare motion paths; this is not a measured cough force.',
      defaultValue: 0.5,
      minLabel: 'Subtle motion',
      middleLabel: 'Visible motion',
      maxLabel: 'Amplified motion',
      modifiers: [{ id: 'motionAmplitude' }],
    }),
    qualitativeRange({
      id: 'airway-curvature',
      kind: 'range',
      label: 'Airway curve',
      description:
        'Compare the selected architecture across a straighter or more curved schematic segment.',
      defaultValue: 0.5,
      minLabel: 'Straighter segment',
      middleLabel: 'Moderate curve',
      maxLabel: 'Greater curve',
      modifiers: [{ id: 'curvature' }],
    }),
    {
      id: 'end-tracking',
      kind: 'toggle',
      label: 'Track device ends',
      description: 'Keep fixed airway markers visible while the device moves.',
      defaultValue: true,
      offLabel: 'Markers hidden',
      onLabel: 'Markers visible',
      modifiers: [{ id: 'endTracking' }],
    },
  ],
  'curve-buckle': [
    qualitativeRange({
      id: 'airway-curvature',
      kind: 'range',
      label: 'Curve constraint',
      description: 'Change the qualitative centerline mismatch between airway and straight tube.',
      defaultValue: 0.75,
      minLabel: 'Near aligned',
      middleLabel: 'Moderate mismatch',
      maxLabel: 'Greater mismatch',
      modifiers: [{ id: 'curvature' }],
    }),
    qualitativeRange({
      id: 'external-compression',
      kind: 'range',
      label: 'External constraint',
      description:
        'Add schematic airway constraint without implying a pressure or buckling threshold.',
      defaultValue: 0.25,
      minLabel: 'Minimal constraint',
      middleLabel: 'Visible constraint',
      maxLabel: 'Greater constraint',
      modifiers: [{ id: 'airwayCompression' }],
    }),
    qualitativeRange({
      id: 'branch-proximity',
      kind: 'range',
      label: 'Branch proximity',
      description: 'Move a generic adjacent branch closer to the distal device relationship.',
      defaultValue: 0.5,
      minLabel: 'More separation',
      middleLabel: 'Near the end',
      maxLabel: 'Crowded relationship',
      modifiers: [{ id: 'branchProximity' }],
    }),
    {
      id: 'contact-overlay',
      kind: 'toggle',
      label: 'Contact overlay',
      description: 'Reveal inner-curve contact and outer-curve gapping with non-color markers.',
      defaultValue: true,
      offLabel: 'Overlay hidden',
      onLabel: 'Overlay visible',
      modifiers: [{ id: 'focalContact' }],
    },
  ],
  migration: [
    qualitativeRange({
      id: 'apposition-loss',
      kind: 'range',
      label: 'Loss of apposition',
      description:
        'Increase the visible device-wall gap without assigning a universal sizing threshold.',
      defaultValue: 0.5,
      minLabel: 'Close apposition',
      middleLabel: 'Visible gap',
      maxLabel: 'Greater gap',
      modifiers: [{ id: 'appositionLoss' }],
    }),
    {
      id: 'displacement-direction',
      kind: 'preset',
      label: 'Displacement pathway',
      description: 'Compare the device ends with fixed landmarks in either axial direction.',
      defaultValue: 'distal',
      options: [
        {
          id: 'minimal',
          label: 'Minimal displacement',
          description: 'Keep both ends near their baseline landing-zone markers.',
          modifiers: {},
        },
        {
          id: 'proximal',
          label: 'Proximal displacement',
          description: 'Move the generic device toward the proximal landmark.',
          modifiers: { proximalDisplacement: 1 },
        },
        {
          id: 'distal',
          label: 'Distal displacement',
          description: 'Move the generic device toward the distal landmark.',
          modifiers: { distalDisplacement: 1 },
        },
      ],
    },
    {
      id: 'landmark-tracking',
      kind: 'toggle',
      label: 'Fixed landmark tracking',
      description: 'Keep landing-zone and branch markers visible while the camera changes.',
      defaultValue: true,
      offLabel: 'Landmarks hidden',
      onLabel: 'Landmarks visible',
      modifiers: [{ id: 'landmarkTracking' }],
    },
  ],
  'mucus-obstruction': [
    qualitativeRange({
      id: 'secretion-burden',
      kind: 'range',
      label: 'Visible secretion burden',
      description:
        'Progress a generic coating toward a larger retained burden without modeling a time course.',
      defaultValue: 0.5,
      minLabel: 'Surface coating',
      middleLabel: 'Retained burden',
      maxLabel: 'Large focal burden',
      modifiers: [{ id: 'secretionBurden' }],
    }),
    {
      id: 'retention-geometry',
      kind: 'preset',
      label: 'Retention geometry',
      description: 'Place the qualitative secretion pocket at a common geometric transition.',
      defaultValue: 'dependent-gap',
      options: [
        {
          id: 'smooth-lumen',
          label: 'No focal pocket',
          description: 'Show coating without a localized retention pocket.',
          modifiers: {},
        },
        {
          id: 'dependent-gap',
          label: 'Dependent gap',
          description: 'Collect secretions within a modeled dependent apposition gap.',
          modifiers: { retentionPocket: 0.75 },
        },
        {
          id: 'bifurcation-pocket',
          label: 'Bifurcation pocket',
          description: 'Collect secretions near a modeled bifurcation transition.',
          modifiers: { retentionPocket: 1 },
        },
      ],
    },
    qualitativeRange({
      id: 'obstruction-extent',
      kind: 'range',
      label: 'Modeled lumen encroachment',
      description: 'Change the visible plug extent for end-on inspection.',
      defaultValue: 0.25,
      minLabel: 'Thin coating',
      middleLabel: 'Partial obstruction',
      maxLabel: 'Marked obstruction',
      modifiers: [{ id: 'obstructionExtent' }],
    }),
  ],
  granulation: [
    qualitativeRange({
      id: 'end-contact',
      kind: 'range',
      label: 'End contact',
      description: 'Change the visible focal interface contact as one possible contributor.',
      defaultValue: 0.5,
      minLabel: 'Limited contact',
      middleLabel: 'Visible contact',
      maxLabel: 'Focal contact',
      modifiers: [{ id: 'endContact' }],
    }),
    qualitativeRange({
      id: 'relative-motion',
      kind: 'range',
      label: 'Relative interface motion',
      description:
        'Change visible tissue-device motion as one contributor, not a causal risk calculation.',
      defaultValue: 0.5,
      minLabel: 'Subtle motion',
      middleLabel: 'Visible motion',
      maxLabel: 'Greater motion',
      modifiers: [{ id: 'relativeMotion' }],
    }),
    {
      id: 'secretory-context',
      kind: 'toggle',
      label: 'Secretory or infectious context',
      description:
        'Layer retained secretions and possible infection context without diagnosing infection.',
      defaultValue: false,
      offLabel: 'Context absent',
      onLabel: 'Context layered',
      modifiers: [{ id: 'secretoryInfectiousContext' }],
    },
    qualitativeRange({
      id: 'biologic-context',
      kind: 'range',
      label: 'Time and host-response context',
      description:
        'Make the biologic and dwell-time domain more prominent without predicting individual tissue response.',
      defaultValue: 0.5,
      minLabel: 'Background context',
      middleLabel: 'Visible context',
      maxLabel: 'Prominent context',
      modifiers: [{ id: 'biologicContext' }],
    }),
  ],
  'tumor-ingrowth-overgrowth': [
    {
      id: 'tissue-pathway',
      kind: 'preset',
      label: 'Modeled tissue pathway',
      description:
        'Contrast where generic tissue enters the lumen relative to cells and device ends.',
      defaultValue: 'through-cells',
      options: [
        {
          id: 'through-cells',
          label: 'Through open cells',
          description: 'Route generic tissue through an uncovered scaffold body.',
          architectureIds: ['free-crossing-braid', 'balloon-expanded-metal'],
          modifiers: { tumorIngrowth: 1 },
        },
        {
          id: 'through-exposed-ends',
          label: 'Through partially covered end cells',
          description:
            'Route generic tissue through exposed cells beyond the covered knitted midsection.',
          architectureIds: ['single-wire-knit-partial-cover'],
          modifiers: { exposedEndIngrowth: 1 },
        },
        {
          id: 'around-end',
          label: 'Around a covered end',
          description: 'Route generic tissue around an intact covered-device end.',
          architectureIds: [
            'hook-cross-covered',
            'laser-cut-covered',
            'single-wire-knit-partial-cover',
            'solid-silicone',
          ],
          modifiers: { tumorOvergrowth: 1 },
        },
        {
          id: 'through-cover-defect',
          label: 'Through a cover defect',
          description:
            'Route generic tissue through an explicitly revealed schematic cover defect.',
          architectureIds: [
            'hook-cross-covered',
            'laser-cut-covered',
            'single-wire-knit-partial-cover',
          ],
          modifiers: { tumorIngrowth: 1 },
        },
      ],
    },
    qualitativeRange({
      id: 'tissue-extent',
      kind: 'range',
      label: 'Visible tissue extent',
      description:
        'Change generic lumen encroachment without diagnosing pathology or modeling growth rate.',
      defaultValue: 0.5,
      minLabel: 'Early encroachment',
      middleLabel: 'Visible encroachment',
      maxLabel: 'Marked encroachment',
      modifiers: [{ id: 'obstructionExtent' }],
    }),
    {
      architectureIds: [
        'hook-cross-covered',
        'laser-cut-covered',
        'single-wire-knit-partial-cover',
      ],
      id: 'cover-discontinuity',
      kind: 'toggle',
      label: 'Cover discontinuity',
      description: 'Compare an intact generic barrier with a visible schematic defect.',
      defaultValue: false,
      offLabel: 'Barrier intact',
      onLabel: 'Discontinuity visible',
      modifiers: [{ id: 'coverFailure' }],
    },
  ],
  'fracture-cover-failure': [
    qualitativeRange({
      id: 'tortuosity',
      kind: 'range',
      label: 'Airway tortuosity',
      description:
        'Change the modeled curve where architecture-specific bending localizes; this is not an individual risk estimate.',
      defaultValue: 0.75,
      minLabel: 'Straighter segment',
      middleLabel: 'Curved segment',
      maxLabel: 'Tortuous segment',
      modifiers: [{ id: 'curvature' }],
    }),
    qualitativeRange({
      id: 'repeated-loading',
      kind: 'range',
      label: 'Repeated-load emphasis',
      description:
        'Increase qualitative loading at the structural hotspot without assigning cycles or a fatigue threshold.',
      defaultValue: 0.5,
      minLabel: 'Subtle loading',
      middleLabel: 'Localized loading',
      maxLabel: 'Amplified loading',
      modifiers: [{ id: 'repeatedLoading' }],
    }),
    {
      id: 'failure-mode',
      kind: 'preset',
      label: 'Structural finding',
      description: 'Inspect wire continuity and cover continuity as distinct findings.',
      defaultValue: 'wire-discontinuity',
      options: [
        {
          id: 'intact',
          label: 'No visible failure',
          description: 'Keep the scaffold and cover visibly continuous.',
          modifiers: {},
        },
        {
          id: 'wire-discontinuity',
          label: 'Wire discontinuity',
          description: 'Reveal a focal discontinuity in the generic scaffold.',
          modifiers: { fracture: 1 },
        },
        {
          id: 'cover-tear',
          label: 'Cover tear',
          description: 'Reveal a focal discontinuity in the generic cover.',
          architectureIds: [
            'hook-cross-covered',
            'laser-cut-covered',
            'single-wire-knit-partial-cover',
          ],
          modifiers: { coverFailure: 1 },
        },
        {
          id: 'combined',
          label: 'Combined findings',
          description: 'Reveal separate scaffold and cover discontinuities.',
          architectureIds: [
            'hook-cross-covered',
            'laser-cut-covered',
            'single-wire-knit-partial-cover',
          ],
          modifiers: { fracture: 1, coverFailure: 1 },
        },
      ],
    },
    {
      id: 'structural-hotspot',
      kind: 'toggle',
      label: 'Structural hotspot overlay',
      description: 'Mark where repeated bending localizes without predicting failure.',
      defaultValue: true,
      offLabel: 'Overlay hidden',
      onLabel: 'Overlay visible',
      modifiers: [{ id: 'structuralHotspot' }],
    },
  ],
  'y-stent': [
    qualitativeRange({
      id: 'saddle-mismatch',
      kind: 'range',
      label: 'Saddle mismatch',
      description: 'Offset the generic saddle relative to the modeled carinal ridge.',
      defaultValue: 0.25,
      minLabel: 'Aligned saddle',
      middleLabel: 'Visible offset',
      maxLabel: 'Greater offset',
      modifiers: [{ id: 'saddleMismatch' }],
    }),
    qualitativeRange({
      id: 'branch-angle-mismatch',
      kind: 'range',
      label: 'Branch-angle mismatch',
      description: 'Change the relationship between generic Y limbs and modeled main bronchi.',
      defaultValue: 0.5,
      minLabel: 'Closely aligned',
      middleLabel: 'Visible mismatch',
      maxLabel: 'Greater mismatch',
      modifiers: [{ id: 'branchAngleMismatch' }],
    }),
    qualitativeRange({
      id: 'distal-orifice-crowding',
      kind: 'range',
      label: 'Distal-orifice crowding',
      description: 'Move one limb end toward a generic distal branch origin.',
      defaultValue: 0.25,
      minLabel: 'Clear orifice',
      middleLabel: 'Near the orifice',
      maxLabel: 'Crowded orifice',
      modifiers: [{ id: 'distalOrificeCompromise' }],
    }),
    qualitativeRange({
      id: 'posterior-motion',
      kind: 'range',
      label: 'Posterior-wall motion',
      description: 'Change the visible posterior-wall excursion for architecture comparison only.',
      defaultValue: 0.5,
      minLabel: 'Subtle excursion',
      middleLabel: 'Visible excursion',
      maxLabel: 'Amplified excursion',
      modifiers: [{ id: 'posteriorMotion' }],
    }),
  ],
  'deploy-rescue': [
    {
      id: 'deployment-state',
      kind: 'preset',
      label: 'Conceptual deployment state',
      description:
        'Compare constrained, partially deployed, and deployed geometry without instrument-handling steps.',
      defaultValue: 'constrained',
      options: [
        {
          id: 'constrained',
          label: 'Constrained or folded',
          description: 'Show the generic device before release or unfolding.',
          modifiers: { deployment: 0 },
        },
        {
          id: 'partial',
          label: 'Partially deployed',
          description: 'Show a qualitative intermediate geometry.',
          modifiers: { deployment: 0.5 },
        },
        {
          id: 'deployed',
          label: 'Deployed',
          description: 'Show the generic final geometry before systematic inspection.',
          modifiers: { deployment: 1 },
        },
      ],
    },
    qualitativeRange({
      id: 'incomplete-expansion',
      kind: 'range',
      label: 'Incomplete-expansion finding',
      description: 'Increase a visible fold or incomplete expansion for inspection practice.',
      defaultValue: 0.25,
      minLabel: 'Uniform expansion',
      middleLabel: 'Focal underexpansion',
      maxLabel: 'Marked underexpansion',
      modifiers: [{ id: 'incompleteExpansion' }],
    }),
    {
      id: 'response-constraint',
      kind: 'preset',
      label: 'Conceptual response constraint',
      description:
        'Compare how architecture and timing can frame response options without teaching a procedure.',
      defaultValue: 'reassess',
      options: [
        {
          id: 'reassess',
          label: 'Reassess first',
          description: 'Keep the scene focused on systematic inspection and problem definition.',
          modifiers: { repositioningConstraint: 0 },
        },
        {
          id: 'potentially-repositionable',
          label: 'Potential repositioning pathway',
          description: 'Open a conceptual pathway that remains device- and situation-dependent.',
          modifiers: { repositioningConstraint: 0.4 },
        },
        {
          id: 'limited-repositioning',
          label: 'Limited repositioning pathway',
          description: 'Emphasize specialist removal or replacement planning considerations.',
          modifiers: { repositioningConstraint: 1 },
        },
      ],
    },
    {
      id: 'inspection-overlay',
      kind: 'toggle',
      label: 'Immediate inspection overlay',
      description: 'Mark both ends, the full lumen, adjacent branches, and interface findings.',
      defaultValue: true,
      offLabel: 'Overlay hidden',
      onLabel: 'Overlay visible',
      modifiers: [{ id: 'inspectionReveal' }],
    },
  ],
} as const satisfies Readonly<Record<StentExplorerStationId, readonly StentExplorerControl[]>>
