import type { StentArchitecturePreset } from '../engine/types'

/**
 * Relative, educational calibration values. These are not device specifications,
 * Newton values, pressure thresholds, or patient-level predictions.
 */
export const stentArchitecturePresets: StentArchitecturePreset[] = [
  {
    id: 'studded-silicone',
    label: 'Studded molded silicone',
    shortLabel: 'Silicone',
    family: 'Solid-wall silicone',
    material: 'Medical-grade silicone elastomer',
    renderKind: 'silicone',
    description:
      'A removable, continuous wall whose performance is strongly shaped by wall thickness, durometer, studs, rings, and fit.',
    radialSupport: 44,
    axialStiffness: 66,
    contactConcentration: 58,
    interfaceFriction: 44,
    anchoringGeometry: 67,
    lumenRetention: 68,
    mucusBurden: 78,
    fatigueConcentration: 36,
    isCovered: true,
    isWireBased: false,
    sourceRefs: [1, 6, 8, 17, 42],
    strengths: [
      'Predictable planned removal',
      'Customizable length and openings',
      'No tumor ingrowth through the wall',
    ],
    tradeoffs: [
      'Thick wall reduces functional lumen',
      'Migration if fit is poor',
      'Mucus retention and focal stud pressure',
    ],
  },
  {
    id: 'dynamic-silicone',
    label: 'Dynamic D-shaped silicone',
    shortLabel: 'Dynamic silicone',
    family: 'Dynamic silicone',
    material: 'Medical-grade silicone elastomer',
    renderKind: 'silicone',
    description:
      'A posteriorly flattened or compliant design intended to support patency while preserving some dynamic area change.',
    radialSupport: 39,
    axialStiffness: 42,
    contactConcentration: 46,
    interfaceFriction: 48,
    anchoringGeometry: 72,
    lumenRetention: 73,
    mucusBurden: 64,
    fatigueConcentration: 34,
    isCovered: true,
    isWireBased: false,
    sourceRefs: [1, 9, 10],
    strengths: [
      'Lower designed-plane bending force',
      'Directional anchoring',
      'Preserves expiratory shape change better than a rigid circle',
    ],
    tradeoffs: [
      'Orientation-sensitive',
      'Still interrupts mucociliary transport',
      'Low support may permit ovalization under rigid compression',
    ],
  },
  {
    id: 'single-wire-knit',
    label: 'Single-wire knitted nitinol',
    shortLabel: 'Single-wire knit',
    family: 'Self-expanding metallic scaffold',
    material: 'Nitinol',
    renderKind: 'braid',
    description:
      'A continuous superelastic strand formed into loops, coupling diameter, length, cell opening, and recovery behavior.',
    radialSupport: 61,
    axialStiffness: 52,
    contactConcentration: 70,
    interfaceFriction: 54,
    anchoringGeometry: 42,
    lumenRetention: 79,
    mucusBurden: 36,
    fatigueConcentration: 61,
    isCovered: false,
    isWireBased: true,
    sourceRefs: [13, 19, 26, 43],
    strengths: [
      'Thin wall and low-profile delivery',
      'Continuous self-expansion',
      'Conforms to irregular lumens',
    ],
    tradeoffs: [
      'Tissue ingrowth if uncovered',
      'Architecture-dependent foreshortening',
      'Fracture and difficult removal after incorporation',
    ],
  },
  {
    id: 'multiwire-braid',
    label: 'Multiwire nitinol braid',
    shortLabel: 'Multiwire braid',
    family: 'Self-expanding metallic scaffold',
    material: 'Nitinol or cobalt-based alloy',
    renderKind: 'braid',
    description:
      'Crossing helical wires share load; wire count, diameter, braid angle, sliding, and friction jointly set the response.',
    radialSupport: 70,
    axialStiffness: 59,
    contactConcentration: 66,
    interfaceFriction: 60,
    anchoringGeometry: 48,
    lumenRetention: 83,
    mucusBurden: 42,
    fatigueConcentration: 68,
    isCovered: false,
    isWireBased: true,
    sourceRefs: [12, 23, 24, 33, 39],
    strengths: [
      'Tunable load sharing',
      'High lumen-to-wall ratio',
      'Redundancy across multiple wires',
    ],
    tradeoffs: [
      'Crossing friction and fretting',
      'Diameter-length coupling',
      'Axial force depends strongly on cell geometry',
    ],
  },
  {
    id: 'covered-hybrid',
    label: 'Fully covered hybrid braid',
    shortLabel: 'Covered hybrid',
    family: 'Covered self-expanding scaffold',
    material: 'Nitinol plus polymer membrane',
    renderKind: 'braid',
    description:
      'A metallic scaffold plus continuous membrane; the cover can distribute contact and prevent ingrowth while altering stiffness and friction.',
    radialSupport: 72,
    axialStiffness: 64,
    contactConcentration: 54,
    interfaceFriction: 40,
    anchoringGeometry: 58,
    lumenRetention: 86,
    mucusBurden: 72,
    fatigueConcentration: 72,
    isCovered: true,
    isWireBased: true,
    sourceRefs: [2, 20, 21, 39],
    strengths: [
      'Continuous seal and ingrowth barrier',
      'Strong apposition',
      'Thin scaffold relative to solid silicone',
    ],
    tradeoffs: [
      'Migration if the smooth cover reduces friction',
      'End loading and granulation',
      'Cover crease, abrasion, or delamination',
    ],
  },
  {
    id: 'laser-cut-sems',
    label: 'Laser-cut self-expanding lattice',
    shortLabel: 'Laser-cut SEMS',
    family: 'Segmented metallic scaffold',
    material: 'Nitinol',
    renderKind: 'laser-cut',
    description:
      'Rings and connectors permit deliberate segmental stiffness and low foreshortening, but connectors become hinges and fatigue hot spots.',
    radialSupport: 76,
    axialStiffness: 72,
    contactConcentration: 73,
    interfaceFriction: 51,
    anchoringGeometry: 52,
    lumenRetention: 88,
    mucusBurden: 40,
    fatigueConcentration: 82,
    isCovered: false,
    isWireBased: true,
    sourceRefs: [2, 13, 14, 16],
    strengths: ['Predictable cell geometry', 'Low foreshortening', 'Segment-by-segment tuning'],
    tradeoffs: [
      'Connector fatigue concentration',
      'Closed cells may straighten bends',
      'Exposed strut contact and tissue ingrowth',
    ],
  },
  {
    id: 'silicone-y',
    label: 'Molded silicone Y-stent',
    shortLabel: 'Silicone Y',
    family: 'Bifurcated silicone',
    material: 'Medical-grade silicone elastomer',
    renderKind: 'y',
    description:
      'A three-limb removable frame anchored by the carina, with branch-dependent bending, torsion, mucus, and fit tradeoffs.',
    radialSupport: 48,
    axialStiffness: 70,
    contactConcentration: 67,
    interfaceFriction: 50,
    anchoringGeometry: 91,
    lumenRetention: 71,
    mucusBurden: 88,
    fatigueConcentration: 54,
    isCovered: true,
    isWireBased: false,
    sourceRefs: [3, 6, 22, 41],
    strengths: [
      'Strong geometric fixation',
      'Planned removability',
      'Customizable limbs and fenestrations',
    ],
    tradeoffs: [
      'Carinal pressure and branch mismatch',
      'Bulky placement mechanics',
      'Mucus at saddle and limb junctions',
    ],
  },
  {
    id: 'patient-specific-silicone',
    label: 'Patient-specific silicone',
    shortLabel: 'Patient-specific',
    family: 'Anatomy-matched silicone',
    material: 'Medical-grade silicone plus radiopaque filler',
    renderKind: 'y',
    description:
      'A CT-derived molded device that substitutes matched taper, branch angle, and local diameter for indiscriminate oversizing.',
    radialSupport: 46,
    axialStiffness: 48,
    contactConcentration: 39,
    interfaceFriction: 49,
    anchoringGeometry: 88,
    lumenRetention: 80,
    mucusBurden: 75,
    fatigueConcentration: 47,
    isCovered: true,
    isWireBased: false,
    sourceRefs: [18, 27, 31],
    strengths: [
      'Matches taper and branch geometry',
      'Fit can reduce migration without maximal stiffness',
      'Predictable removability',
    ],
    tradeoffs: [
      'Design and production time',
      'Orientation and deployment burden',
      'Thin or complex branches require fatigue validation',
    ],
  },
]

export function getStentArchitecturePreset(id: StentArchitecturePreset['id']) {
  const preset = stentArchitecturePresets.find((candidate) => candidate.id === id)
  if (!preset) {
    throw new Error(`Unknown airway stent architecture: ${id}`)
  }
  return preset
}
