[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environment]
NODE_ENV = "production"
NODE_VERSION = "20.12.2"
NIXPACKS_NODE_VERSION = "20.12.2"
NPM_CONFIG_PRODUCTION = "false"
