[build]
builder = "nixpacks"

[deploy]
startCommand = "npx next start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
PORT = "3000"
NODE_VERSION = "18.18.0"
