[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environment]
NODE_ENV = "production"
NODE_VERSION = "18.20.4"
NIXPACKS_NODE_VERSION = "18.20.4"
