import type { PleuralFluidCase } from '../engine/types'

export const pleuralFluidCases: readonly PleuralFluidCase[] = [
  {
    id: 'diuresed-heart-failure',
    title: 'Diuresed heart failure',
    subtitle: 'Positive Light criteria with a systemic story',
    patient:
      'A 78-year-old with orthopnea, edema, preserved EF, bilateral anechoic effusions, and improvement after IV diuresis.',
    clinicalClues: [
      'Bilateral anechoic effusions',
      'High NT-proBNP',
      'No fever, pleuritic pain, or pleural thickening',
      'Thoracentesis performed because the left side lagged behind clinically',
    ],
    teachingFocus:
      'Recognize pseudoexudate physiology before escalating to invasive exudate workup.',
    input: {
      clinicalContext: 'heart-failure-diuresis',
      ultrasound: 'anechoic-bilateral',
      appearance: 'straw',
      serumProtein: 6.5,
      pleuralProtein: 3.3,
      serumLdh: 210,
      pleuralLdh: 145,
      serumLdhUpperLimit: 220,
      serumAlbumin: 3.8,
      pleuralAlbumin: 2.3,
      ntProBnp: 4200,
      pleuralPH: 7.48,
      pleuralGlucose: 112,
      nucleatedCells: 420,
      neutrophils: 12,
      lymphocytes: 38,
      eosinophils: 2,
      mesothelialCells: 14,
      triglycerides: 18,
      cholesterol: 38,
      ada: 8,
      amylase: 22,
      cytologyPositive: false,
      microbiologyPositive: false,
      chylomicronsPresent: false,
    },
  },
  {
    id: 'septated-pneumonia',
    title: 'Septated pneumonia effusion',
    subtitle: 'The pH/glucose/LDH branch matters more than the label',
    patient:
      'A 62-year-old with pneumonia, fever, pleuritic pain, rising oxygen need, and a complex septated right effusion on ultrasound.',
    clinicalClues: [
      'Ipsilateral pneumonia',
      'Complex septated ultrasound pattern',
      'Neutrophil-predominant fluid',
      'Low pH and low glucose',
    ],
    teachingFocus:
      'Use PFA to decide whether a parapneumonic effusion has crossed into drainage territory.',
    input: {
      clinicalContext: 'pneumonia-infection',
      ultrasound: 'septated',
      appearance: 'turbid',
      serumProtein: 6.8,
      pleuralProtein: 4.8,
      serumLdh: 210,
      pleuralLdh: 1850,
      serumLdhUpperLimit: 220,
      serumAlbumin: 3.2,
      pleuralAlbumin: 2.4,
      ntProBnp: 410,
      pleuralPH: 7.05,
      pleuralGlucose: 28,
      nucleatedCells: 65000,
      neutrophils: 92,
      lymphocytes: 4,
      eosinophils: 0,
      mesothelialCells: 1,
      triglycerides: 42,
      cholesterol: 86,
      ada: 22,
      amylase: 35,
      cytologyPositive: false,
      microbiologyPositive: true,
      chylomicronsPresent: false,
    },
  },
  {
    id: 'lymphocytic-tb-risk',
    title: 'Lymphocytic effusion after travel',
    subtitle: 'The PFA narrows; exposure history pushes',
    patient:
      'A 29-year-old with pleuritic pain, night sweats, prior work in TB-endemic regions, and unilateral anechoic effusion.',
    clinicalClues: [
      'Lymphocytes above 80%',
      'High pleural protein and LDH',
      'Exposure history matters even in a lower-prevalence region',
      'Initial stains can be negative',
    ],
    teachingFocus:
      'Pair lymphocyte-predominant exudate with travel/exposure history and biopsy strategy.',
    input: {
      clinicalContext: 'tb-exposure',
      ultrasound: 'anechoic-unilateral',
      appearance: 'serous',
      serumProtein: 6,
      pleuralProtein: 4.3,
      serumLdh: 128,
      pleuralLdh: 612,
      serumLdhUpperLimit: 220,
      serumAlbumin: 3.7,
      pleuralAlbumin: 2.6,
      ntProBnp: 180,
      pleuralPH: 7.38,
      pleuralGlucose: 59,
      nucleatedCells: 2708,
      neutrophils: 8,
      lymphocytes: 83,
      eosinophils: 1,
      mesothelialCells: 2,
      triglycerides: 35,
      cholesterol: 109,
      ada: 76,
      amylase: 40,
      cytologyPositive: false,
      microbiologyPositive: false,
      chylomicronsPresent: false,
    },
  },
  {
    id: 'malignancy-transudate-trap',
    title: 'Cancer context with bland chemistry',
    subtitle: 'A transudate label does not end the workup',
    patient:
      'A 69-year-old with weight loss, smoking history, recurrent unilateral effusion, and pleural nodularity on ultrasound.',
    clinicalClues: [
      'Recurrent unilateral effusion',
      'Pleural nodularity',
      'Cytology from the first tap was negative',
      'Concurrent renal disease could bias chemistry toward transudate',
    ],
    teachingFocus:
      'Avoid false reassurance when imaging and history keep malignant pleural disease likely.',
    input: {
      clinicalContext: 'malignancy',
      ultrasound: 'nodular-thickened',
      appearance: 'serosanguineous',
      serumProtein: 6.4,
      pleuralProtein: 2.7,
      serumLdh: 190,
      pleuralLdh: 110,
      serumLdhUpperLimit: 220,
      serumAlbumin: 3.4,
      pleuralAlbumin: 2.1,
      ntProBnp: 820,
      pleuralPH: 7.35,
      pleuralGlucose: 86,
      nucleatedCells: 1200,
      neutrophils: 18,
      lymphocytes: 62,
      eosinophils: 4,
      mesothelialCells: 6,
      triglycerides: 34,
      cholesterol: 42,
      ada: 16,
      amylase: 52,
      cytologyPositive: false,
      microbiologyPositive: false,
      chylomicronsPresent: false,
    },
  },
  {
    id: 'milky-lymphatic',
    title: 'Milky lymphatic effusion',
    subtitle: 'Appearance creates a targeted-test branch',
    patient:
      'A 76-year-old with dyspnea, lymphedema, dystrophic nails, bilateral effusions, and milky yellow fluid at thoracentesis.',
    clinicalClues: [
      'Milky fluid can be chyle or cholesterol',
      'Lymphocyte-predominant profile',
      'Triglycerides are diagnostic here',
      'Yellow-nail phenotype connects the bedside exam to PFA',
    ],
    teachingFocus:
      'Use gross appearance to order lipid studies instead of forcing every effusion through infection or malignancy.',
    input: {
      clinicalContext: 'post-procedure-lymphatic',
      ultrasound: 'anechoic-bilateral',
      appearance: 'milky',
      serumProtein: 6.1,
      pleuralProtein: 4.2,
      serumLdh: 176,
      pleuralLdh: 78,
      serumLdhUpperLimit: 220,
      serumAlbumin: 3.5,
      pleuralAlbumin: 2.4,
      ntProBnp: 620,
      pleuralPH: 7.43,
      pleuralGlucose: 96,
      nucleatedCells: 494,
      neutrophils: 14,
      lymphocytes: 66,
      eosinophils: 1,
      mesothelialCells: 8,
      triglycerides: 264,
      cholesterol: 92,
      ada: 10,
      amylase: 33,
      cytologyPositive: false,
      microbiologyPositive: false,
      chylomicronsPresent: false,
    },
  },
] as const

export const defaultPleuralFluidCase = pleuralFluidCases[0]
