import type { DiseaseProfile } from '../engine/types'

export const pleuralDiseaseProfiles: readonly DiseaseProfile[] = [
  {
    id: 'congestive-heart-failure',
    name: 'Congestive heart failure',
    rarity: 'common',
    category: 'transudate',
    family: 'Systemic transudates',
    summary: 'Bilateral or right-predominant effusions from systemic pressure physiology.',
    teachingPearl:
      "After diuresis, CHF can meet Light's criteria by a small margin; gradients and NT-proBNP rescue the interpretation.",
    nextStep:
      'Treat volume/pressure physiology and reassess; sample again only if the story breaks pattern.',
    rules: [
      {
        key: 'reconciledCategory',
        operator: 'eq',
        value: 'transudate',
        weight: 8,
        domain: 'fluid',
        evidence: 'reconciled transudative chemistry',
      },
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'heart-failure-diuresis',
        weight: 9,
        domain: 'context',
        evidence: 'heart failure or diuresis frame',
      },
      {
        key: 'ultrasound',
        operator: 'eq',
        value: 'anechoic-bilateral',
        weight: 5,
        domain: 'context',
        evidence: 'bilateral anechoic effusions',
      },
      {
        key: 'ntProBnp',
        operator: 'gte',
        value: 1500,
        weight: 9,
        domain: 'targeted',
        evidence: 'NT-proBNP above 1,500 pg/mL',
      },
      {
        key: 'albuminGradient',
        operator: 'gte',
        value: 1.2,
        weight: 6,
        domain: 'targeted',
        evidence: 'serum-pleural albumin gradient supports pseudoexudate',
      },
      {
        key: 'pleuralPH',
        operator: 'gte',
        value: 7.4,
        weight: 3,
        domain: 'fluid',
        evidence: 'alkaline pleural pH',
      },
    ],
  },
  {
    id: 'hepatic-hydrothorax',
    name: 'Hepatic hydrothorax',
    rarity: 'uncommon',
    category: 'transudate',
    family: 'Systemic transudates',
    summary: 'Pleural accumulation from ascitic flow through diaphragmatic defects.',
    teachingPearl:
      'Ascites may be subtle; right-sided or bilateral anechoic effusions can still fit.',
    nextStep: 'Look for cirrhosis, subtle ascites, and portal-hypertension physiology.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'hepatic-renal-systemic',
        weight: 8,
        domain: 'context',
        evidence: 'hepatic or systemic transudate frame',
      },
      {
        key: 'reconciledCategory',
        operator: 'eq',
        value: 'transudate',
        weight: 8,
        domain: 'fluid',
        evidence: 'transudative chemistry',
      },
      {
        key: 'pleuralProtein',
        operator: 'lte',
        value: 3,
        weight: 5,
        domain: 'fluid',
        evidence: 'low pleural protein',
      },
      {
        key: 'ultrasound',
        operator: 'oneOf',
        values: ['anechoic-unilateral', 'anechoic-bilateral'],
        weight: 4,
        domain: 'context',
        evidence: 'anechoic ultrasound pattern',
      },
    ],
  },
  {
    id: 'parapneumonic-empyema',
    name: 'Complicated parapneumonic effusion / empyema',
    rarity: 'common',
    category: 'exudate',
    family: 'Infection',
    summary: 'Inflammatory exudate from pneumonia that may require drainage.',
    teachingPearl: 'pH, glucose, LDH, ultrasound complexity, and microbiology decide urgency.',
    nextStep: 'Assess for chest tube drainage, antibiotics, and loculation strategy.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'pneumonia-infection',
        weight: 9,
        domain: 'context',
        evidence: 'pneumonia or infection frame',
      },
      {
        key: 'ultrasound',
        operator: 'oneOf',
        values: ['septated', 'complex-homogeneous'],
        weight: 7,
        domain: 'context',
        evidence: 'septated or complex ultrasound pattern',
      },
      {
        key: 'pleuralPH',
        operator: 'lte',
        value: 7.2,
        weight: 10,
        domain: 'fluid',
        evidence: 'pleural pH below 7.2',
      },
      {
        key: 'pleuralGlucose',
        operator: 'lte',
        value: 60,
        weight: 7,
        domain: 'fluid',
        evidence: 'low pleural glucose',
      },
      {
        key: 'pleuralLdh',
        operator: 'gte',
        value: 1000,
        weight: 7,
        domain: 'fluid',
        evidence: 'LDH above 1,000 U/L',
      },
      {
        key: 'neutrophils',
        operator: 'gte',
        value: 70,
        weight: 6,
        domain: 'fluid',
        evidence: 'neutrophil predominance',
      },
      {
        key: 'microbiologyPositive',
        operator: 'truthy',
        weight: 9,
        domain: 'targeted',
        evidence: 'positive microbiology',
      },
      {
        key: 'appearance',
        operator: 'oneOf',
        values: ['turbid', 'purulent'],
        weight: 5,
        domain: 'fluid',
        evidence: 'turbid or purulent fluid',
      },
    ],
  },
  {
    id: 'tuberculous-pleural-effusion',
    name: 'Tuberculous pleural effusion',
    rarity: 'uncommon',
    category: 'exudate',
    family: 'Infection',
    summary: 'Lymphocyte-predominant exudate where epidemiology changes test value.',
    teachingPearl:
      'ADA is a probability shifter; biopsy and culture matter when suspicion stays high.',
    nextStep:
      'Send mycobacterial culture and consider pleural biopsy for histology and drug susceptibility.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'tb-exposure',
        weight: 9,
        domain: 'context',
        evidence: 'TB exposure or endemic-risk context',
      },
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 5,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 80,
        weight: 8,
        domain: 'fluid',
        evidence: 'lymphocytes above 80%',
      },
      {
        key: 'ada',
        operator: 'gte',
        value: 40,
        weight: 6,
        domain: 'targeted',
        evidence: 'ADA above 40 IU/L',
      },
      {
        key: 'ada',
        operator: 'gte',
        value: 70,
        weight: 4,
        domain: 'targeted',
        evidence: 'ADA above 70 IU/L',
      },
      {
        key: 'mesothelialCells',
        operator: 'lte',
        value: 5,
        weight: 5,
        domain: 'fluid',
        evidence: 'low mesothelial cell percentage',
      },
      {
        key: 'pleuralProtein',
        operator: 'gte',
        value: 4.5,
        weight: 4,
        domain: 'fluid',
        evidence: 'high pleural protein',
      },
    ],
  },
  {
    id: 'malignant-pleural-effusion',
    name: 'Malignant pleural effusion',
    rarity: 'common',
    category: 'exudate',
    family: 'Malignancy',
    summary: 'Cancer-associated effusion, sometimes deceptively transudative.',
    teachingPearl:
      'Pleural nodularity and cancer history keep malignancy alive despite negative cytology.',
    nextStep:
      'Send adequate cytology; biopsy if cytology is negative and pretest probability remains high.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'malignancy',
        weight: 9,
        domain: 'context',
        evidence: 'malignancy context',
      },
      {
        key: 'ultrasound',
        operator: 'eq',
        value: 'nodular-thickened',
        weight: 9,
        domain: 'context',
        evidence: 'pleural nodularity or thickening',
      },
      {
        key: 'cytologyPositive',
        operator: 'truthy',
        weight: 12,
        domain: 'targeted',
        evidence: 'positive cytology',
      },
      {
        key: 'appearance',
        operator: 'oneOf',
        values: ['serosanguineous', 'bloody'],
        weight: 4,
        domain: 'fluid',
        evidence: 'bloody or serosanguineous fluid',
      },
      {
        key: 'lymphocytes',
        operator: 'between',
        min: 50,
        max: 80,
        weight: 4,
        domain: 'fluid',
        evidence: 'moderate lymphocyte predominance',
      },
    ],
  },
  {
    id: 'mesothelioma',
    name: 'Mesothelioma',
    rarity: 'rare',
    category: 'exudate',
    family: 'Malignancy',
    summary:
      'Pleural malignancy often associated with pleural thickening, nodularity, and asbestos exposure.',
    teachingPearl:
      'A massive effusion without expected mediastinal shift can fit encasing pleural disease.',
    nextStep:
      'Use pleural imaging targets and tissue biopsy rather than relying on chemistry alone.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'malignancy',
        weight: 7,
        domain: 'context',
        evidence: 'malignancy or exposure frame',
      },
      {
        key: 'ultrasound',
        operator: 'eq',
        value: 'nodular-thickened',
        weight: 10,
        domain: 'context',
        evidence: 'pleural nodularity or thickening',
      },
      {
        key: 'appearance',
        operator: 'oneOf',
        values: ['serosanguineous', 'bloody'],
        weight: 4,
        domain: 'fluid',
        evidence: 'bloody or serosanguineous fluid',
      },
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 4,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
    ],
  },
  {
    id: 'pulmonary-embolism',
    name: 'Pulmonary embolism',
    rarity: 'common',
    category: 'exudate',
    family: 'Vascular',
    summary: 'Often small, unilateral, and sometimes bloody or serosanguineous.',
    teachingPearl:
      'A small ipsilateral effusion with proven PE may not need diagnostic thoracentesis.',
    nextStep:
      'Let PE probability and imaging drive management; sample if the effusion is atypical.',
    rules: [
      {
        key: 'appearance',
        operator: 'oneOf',
        values: ['serosanguineous', 'bloody'],
        weight: 5,
        domain: 'fluid',
        evidence: 'bloody or serosanguineous fluid',
      },
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 4,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
      {
        key: 'ultrasound',
        operator: 'oneOf',
        values: ['anechoic-unilateral', 'too-small'],
        weight: 4,
        domain: 'context',
        evidence: 'small or unilateral effusion pattern',
      },
    ],
  },
  {
    id: 'rheumatoid-pleural-effusion',
    name: 'Rheumatoid pleural effusion',
    rarity: 'uncommon',
    category: 'exudate',
    family: 'Autoimmune',
    summary: 'Autoimmune pleuritis that can mimic infection biochemically.',
    teachingPearl:
      'Very low glucose and low pH can look like empyema; the joint/systemic story matters.',
    nextStep: 'Reconcile with serologies, joint findings, imaging, and negative microbiology.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'autoimmune',
        weight: 8,
        domain: 'context',
        evidence: 'autoimmune frame',
      },
      {
        key: 'pleuralGlucose',
        operator: 'lte',
        value: 40,
        weight: 8,
        domain: 'fluid',
        evidence: 'very low pleural glucose',
      },
      {
        key: 'pleuralPH',
        operator: 'lte',
        value: 7.3,
        weight: 6,
        domain: 'fluid',
        evidence: 'low pleural pH',
      },
      {
        key: 'pleuralLdh',
        operator: 'gte',
        value: 1000,
        weight: 5,
        domain: 'fluid',
        evidence: 'high LDH',
      },
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 50,
        weight: 3,
        domain: 'fluid',
        evidence: 'lymphocyte-predominant or mixed inflammation',
      },
    ],
  },
  {
    id: 'lupus-pleuritis',
    name: 'Lupus pleuritis',
    rarity: 'uncommon',
    category: 'exudate',
    family: 'Autoimmune',
    summary: 'SLE-associated inflammatory effusion, sometimes low pH and glucose.',
    teachingPearl: 'Like rheumatoid disease, lupus pleuritis can imitate infection.',
    nextStep: 'Integrate systemic lupus activity, serologies, complement, and infection exclusion.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'autoimmune',
        weight: 8,
        domain: 'context',
        evidence: 'autoimmune frame',
      },
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 5,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
      {
        key: 'pleuralPH',
        operator: 'lte',
        value: 7.3,
        weight: 4,
        domain: 'fluid',
        evidence: 'low pleural pH',
      },
      {
        key: 'nucleatedCells',
        operator: 'gte',
        value: 10000,
        weight: 3,
        domain: 'fluid',
        evidence: 'inflammatory nucleated cell count',
      },
    ],
  },
  {
    id: 'chylothorax',
    name: 'Chylothorax',
    rarity: 'uncommon',
    category: 'either',
    family: 'Lymphatic / lipid',
    summary: 'Chyle in the pleural space from lymphatic disruption or obstruction.',
    teachingPearl: 'Appearance helps, but triglycerides and chylomicrons make the diagnosis.',
    nextStep: 'Search for trauma, thoracic surgery, lymphoma, lymphatic disorders, or cirrhosis.',
    rules: [
      {
        key: 'appearance',
        operator: 'oneOf',
        values: ['milky', 'turbid'],
        weight: 6,
        domain: 'fluid',
        evidence: 'milky or turbid fluid',
      },
      {
        key: 'triglycerides',
        operator: 'gte',
        value: 110,
        weight: 12,
        domain: 'targeted',
        evidence: 'triglycerides above 110 mg/dL',
      },
      {
        key: 'chylomicronsPresent',
        operator: 'truthy',
        weight: 10,
        domain: 'targeted',
        evidence: 'chylomicrons present',
      },
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 50,
        weight: 4,
        domain: 'fluid',
        evidence: 'lymphocyte predominance',
      },
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'post-procedure-lymphatic',
        weight: 6,
        domain: 'context',
        evidence: 'lymphatic or post-procedure frame',
      },
    ],
  },
  {
    id: 'yellow-nail-syndrome',
    name: 'Yellow nail syndrome',
    rarity: 'rare',
    category: 'exudate',
    family: 'Lymphatic / lipid',
    summary:
      'Lymphatic disorder associated with yellow dystrophic nails, lymphedema, bronchiectasis, and pleural effusion.',
    teachingPearl:
      'The bedside clue is the diagnosis: nail changes plus lymphedema can explain a lymphocytic effusion.',
    nextStep:
      'Look for dystrophic slow-growing nails, lymphedema, chronic respiratory disease, and recurrent effusions.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'post-procedure-lymphatic',
        weight: 8,
        domain: 'context',
        evidence: 'lymphatic or yellow-nail phenotype frame',
      },
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 50,
        weight: 5,
        domain: 'fluid',
        evidence: 'lymphocyte predominance',
      },
      {
        key: 'appearance',
        operator: 'oneOf',
        values: ['milky', 'serous', 'straw'],
        weight: 3,
        domain: 'fluid',
        evidence: 'serous or lipid-tinged fluid',
      },
      {
        key: 'ultrasound',
        operator: 'oneOf',
        values: ['anechoic-bilateral', 'anechoic-unilateral'],
        weight: 3,
        domain: 'context',
        evidence: 'anechoic recurrent effusion pattern',
      },
    ],
  },
  {
    id: 'pseudochylothorax',
    name: 'Pseudochylothorax / cholesterol effusion',
    rarity: 'rare',
    category: 'exudate',
    family: 'Lymphatic / lipid',
    summary: 'Cholesterol-rich chronic effusion classically after TB or rheumatoid pleuritis.',
    teachingPearl: 'Milky fluid is not always chyle; cholesterol above 250 mg/dL flips the branch.',
    nextStep: 'Check cholesterol and chronic pleural history, especially TB or rheumatoid disease.',
    rules: [
      {
        key: 'appearance',
        operator: 'oneOf',
        values: ['milky', 'turbid'],
        weight: 5,
        domain: 'fluid',
        evidence: 'milky or turbid fluid',
      },
      {
        key: 'cholesterol',
        operator: 'gte',
        value: 250,
        weight: 12,
        domain: 'targeted',
        evidence: 'cholesterol above 250 mg/dL',
      },
      {
        key: 'clinicalContext',
        operator: 'oneOf',
        values: ['tb-exposure', 'autoimmune'],
        weight: 5,
        domain: 'context',
        evidence: 'chronic TB or rheumatoid context',
      },
    ],
  },
  {
    id: 'trapped-lung',
    name: 'Trapped lung',
    rarity: 'uncommon',
    category: 'transudate',
    family: 'Mechanical / chronic',
    summary: 'Chronic stable effusion from non-expandable lung physiology.',
    teachingPearl:
      'Chemistry can be bland or protein-discordant; the key is chronicity and pleural mechanics.',
    nextStep:
      'Use imaging, manometry when available, and symptom trajectory before repeated drainage.',
    rules: [
      {
        key: 'reconciledCategory',
        operator: 'eq',
        value: 'transudate',
        weight: 4,
        domain: 'fluid',
        evidence: 'transudative or bland chemistry',
      },
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 50,
        weight: 4,
        domain: 'fluid',
        evidence: 'lymphocyte-predominant chronic profile',
      },
      {
        key: 'ultrasound',
        operator: 'eq',
        value: 'anechoic-unilateral',
        weight: 4,
        domain: 'context',
        evidence: 'unilateral chronic-appearing effusion',
      },
    ],
  },
  {
    id: 'post-cabg-pcis',
    name: 'Post-CABG / post-cardiac injury syndrome',
    rarity: 'uncommon',
    category: 'exudate',
    family: 'Post-procedure',
    summary:
      'Post-cardiac procedure effusion from surgical trauma, lymphatic injury, CHF, or immune pleuropericarditis.',
    teachingPearl:
      'Post-CABG effusions can be bloody, lymphocytic, or pseudoexudative depending on timing and mechanism.',
    nextStep:
      'Use timing after surgery, pericardial findings, fever, and laterality to sort the mechanism.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'post-procedure-lymphatic',
        weight: 5,
        domain: 'context',
        evidence: 'post-procedure frame',
      },
      {
        key: 'appearance',
        operator: 'oneOf',
        values: ['bloody', 'serosanguineous', 'serous'],
        weight: 4,
        domain: 'fluid',
        evidence: 'bloody or serous post-procedure fluid',
      },
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 50,
        weight: 4,
        domain: 'fluid',
        evidence: 'lymphocyte predominance',
      },
      {
        key: 'proteinGradient',
        operator: 'gte',
        value: 3.1,
        weight: 3,
        domain: 'targeted',
        evidence: 'pseudoexudate gradient can occur after CABG',
      },
    ],
  },
  {
    id: 'uremic-pleuritis',
    name: 'Uremic pleuritis',
    rarity: 'uncommon',
    category: 'exudate',
    family: 'Systemic inflammation',
    summary: 'Inflammatory effusion in advanced renal disease.',
    teachingPearl:
      'Renal failure can produce either systemic transudates or uremic exudative pleuritis.',
    nextStep: 'Reconcile with renal trajectory, dialysis status, and exclusion of infection.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'hepatic-renal-systemic',
        weight: 7,
        domain: 'context',
        evidence: 'renal/systemic context',
      },
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 5,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 50,
        weight: 4,
        domain: 'fluid',
        evidence: 'lymphocytic inflammatory profile',
      },
    ],
  },
  {
    id: 'drug-induced-pleural-effusion',
    name: 'Drug-induced pleural effusion',
    rarity: 'rare',
    category: 'exudate',
    family: 'Medication / immune',
    summary:
      'Medication-associated effusion, including dasatinib, immune checkpoint inhibitors, and drug-induced lupus.',
    teachingPearl:
      'Temporal relationship can be delayed; eosinophilia may help but is not required.',
    nextStep: 'Audit medication timeline and look for peripheral or pleural eosinophilia.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'autoimmune',
        weight: 4,
        domain: 'context',
        evidence: 'immune/drug-like context',
      },
      {
        key: 'eosinophils',
        operator: 'gte',
        value: 10,
        weight: 7,
        domain: 'fluid',
        evidence: 'pleural eosinophilia',
      },
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 50,
        weight: 4,
        domain: 'fluid',
        evidence: 'lymphocyte predominance',
      },
    ],
  },
  {
    id: 'benign-asbestos-pleural-effusion',
    name: 'Benign asbestos pleural effusion',
    rarity: 'rare',
    category: 'exudate',
    family: 'Occupational',
    summary: 'Asbestos-associated effusion that can be hemorrhagic and eosinophilic.',
    teachingPearl: 'It is a diagnosis of context and exclusion; malignancy must remain visible.',
    nextStep:
      'Elicit occupational exposure and assess pleural plaques, thickening, and malignancy risk.',
    rules: [
      {
        key: 'appearance',
        operator: 'oneOf',
        values: ['bloody', 'serosanguineous'],
        weight: 5,
        domain: 'fluid',
        evidence: 'bloody or serosanguineous fluid',
      },
      {
        key: 'eosinophils',
        operator: 'gte',
        value: 10,
        weight: 6,
        domain: 'fluid',
        evidence: 'pleural eosinophilia',
      },
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 4,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
    ],
  },
  {
    id: 'hemothorax',
    name: 'Hemothorax',
    rarity: 'uncommon',
    category: 'exudate',
    family: 'Blood / trauma',
    summary:
      'Blood in the pleural space, usually trauma, procedure, malignancy, or anticoagulation related.',
    teachingPearl: 'The definition is pleural fluid hematocrit above 50% of blood hematocrit.',
    nextStep: 'Escalate drainage and source-control evaluation.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'trauma-hemothorax',
        weight: 8,
        domain: 'context',
        evidence: 'trauma or anticoagulation frame',
      },
      {
        key: 'appearance',
        operator: 'eq',
        value: 'bloody',
        weight: 6,
        domain: 'fluid',
        evidence: 'grossly bloody fluid',
      },
      {
        key: 'ultrasound',
        operator: 'eq',
        value: 'hematocrit-sign',
        weight: 8,
        domain: 'context',
        evidence: 'hematocrit sign on ultrasound',
      },
      {
        key: 'pleuralToBloodHematocritRatio',
        operator: 'gte',
        value: 0.5,
        weight: 12,
        domain: 'targeted',
        evidence: 'PF/blood hematocrit ratio above 0.5',
      },
    ],
  },
  {
    id: 'urinothorax',
    name: 'Urinothorax',
    rarity: 'rare',
    category: 'transudate',
    family: 'Extravascular origin',
    summary: 'Urine tracking into pleural space from obstructive uropathy or urinary tract injury.',
    teachingPearl:
      'A low-pH transudate is unusual; creatinine ratio and urine odor are the branch.',
    nextStep: 'Evaluate urinary tract obstruction or injury; fix the source or it recurs.',
    rules: [
      {
        key: 'appearance',
        operator: 'eq',
        value: 'urine-odor',
        weight: 10,
        domain: 'fluid',
        evidence: 'urine odor',
      },
      {
        key: 'pleuralToSerumCreatinineRatio',
        operator: 'gte',
        value: 1,
        weight: 12,
        domain: 'targeted',
        evidence: 'PF/serum creatinine ratio above 1',
      },
      {
        key: 'pleuralProtein',
        operator: 'lte',
        value: 1,
        weight: 4,
        domain: 'fluid',
        evidence: 'very low protein pleural fluid',
      },
      {
        key: 'pleuralPH',
        operator: 'lte',
        value: 7.3,
        weight: 4,
        domain: 'fluid',
        evidence: 'low pH despite transudative profile',
      },
    ],
  },
  {
    id: 'bilothorax',
    name: 'Bilothorax',
    rarity: 'rare',
    category: 'exudate',
    family: 'Extravascular origin',
    summary: 'Bile in the pleural space after biliary pathology or hepatobiliary surgery.',
    teachingPearl: 'Green fluid is a clue; PF/serum bilirubin ratio above 1 is decisive.',
    nextStep: 'Investigate biliary source and coordinate source control.',
    rules: [
      {
        key: 'appearance',
        operator: 'eq',
        value: 'green',
        weight: 9,
        domain: 'fluid',
        evidence: 'green pleural fluid',
      },
      {
        key: 'pleuralToSerumBilirubinRatio',
        operator: 'gte',
        value: 1,
        weight: 12,
        domain: 'targeted',
        evidence: 'PF/serum bilirubin ratio above 1',
      },
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 4,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
    ],
  },
  {
    id: 'pancreaticopleural-fistula',
    name: 'Pancreaticopleural fistula',
    rarity: 'rare',
    category: 'exudate',
    family: 'Abdominal source',
    summary: 'Pancreatic duct leak or pseudocyst communicating with the pleural space.',
    teachingPearl:
      'Very high pleural amylase is the clue; repeated taps do not solve the duct leak.',
    nextStep: 'Image pancreas and duct anatomy; coordinate pancreatic source control.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'pancreatic-esophageal',
        weight: 8,
        domain: 'context',
        evidence: 'pancreatic or esophageal frame',
      },
      {
        key: 'amylase',
        operator: 'gte',
        value: 100000,
        weight: 12,
        domain: 'targeted',
        evidence: 'amylase above 100,000 U/L',
      },
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 4,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
    ],
  },
  {
    id: 'esophageal-rupture',
    name: 'Esophageal perforation',
    rarity: 'rare',
    category: 'exudate',
    family: 'Abdominal source',
    summary:
      'Esophageal contents entering pleural space, often left hydropneumothorax after procedure or rupture.',
    teachingPearl: 'Food particles are a diagnosis in a cup.',
    nextStep: 'Escalate urgently for surgical/GI source control and broad antimicrobial coverage.',
    rules: [
      {
        key: 'appearance',
        operator: 'eq',
        value: 'food-particles',
        weight: 12,
        domain: 'fluid',
        evidence: 'food particles in pleural fluid',
      },
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'pancreatic-esophageal',
        weight: 8,
        domain: 'context',
        evidence: 'esophageal or pancreatic frame',
      },
      {
        key: 'amylase',
        operator: 'gte',
        value: 200,
        weight: 5,
        domain: 'targeted',
        evidence: 'elevated pleural amylase',
      },
      {
        key: 'pleuralPH',
        operator: 'lte',
        value: 7.2,
        weight: 5,
        domain: 'fluid',
        evidence: 'markedly acidic pleural fluid',
      },
    ],
  },
  {
    id: 'sarcoidosis-pleural-effusion',
    name: 'Sarcoidosis-associated pleural effusion',
    rarity: 'rare',
    category: 'exudate',
    family: 'Granulomatous',
    summary: 'Rare lymphocytic exudate that can resemble TB.',
    teachingPearl:
      'The distinction from TB is clinical and tissue-based more than chemistry-based.',
    nextStep:
      'Look for known sarcoidosis, hilar/mediastinal disease, and exclude TB when risk exists.',
    rules: [
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 5,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 80,
        weight: 6,
        domain: 'fluid',
        evidence: 'lymphocyte predominance',
      },
      {
        key: 'pleuralProtein',
        operator: 'gte',
        value: 4.5,
        weight: 5,
        domain: 'fluid',
        evidence: 'high protein effusion',
      },
      {
        key: 'ada',
        operator: 'lte',
        value: 40,
        weight: 3,
        domain: 'targeted',
        evidence: 'ADA not strongly supportive of TB',
      },
    ],
  },
  {
    id: 'lymphoma-effusion',
    name: 'Lymphoma / primary effusion lymphoma',
    rarity: 'rare',
    category: 'exudate',
    family: 'Malignancy',
    summary:
      'Lymphocyte-predominant malignant effusion; primary effusion lymphoma is rare and often HIV-related.',
    teachingPearl: 'Flow cytometry matters when lymphocytes dominate and cytology is unrevealing.',
    nextStep:
      'Send flow cytometry and integrate systemic symptoms, HIV status, nodes, and imaging.',
    rules: [
      {
        key: 'lymphocytes',
        operator: 'gte',
        value: 80,
        weight: 7,
        domain: 'fluid',
        evidence: 'marked lymphocyte predominance',
      },
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'malignancy',
        weight: 7,
        domain: 'context',
        evidence: 'malignancy/systemic symptom frame',
      },
      {
        key: 'lightCategory',
        operator: 'eq',
        value: 'exudate',
        weight: 5,
        domain: 'fluid',
        evidence: 'exudative chemistry',
      },
      {
        key: 'cytologyPositive',
        operator: 'truthy',
        weight: 8,
        domain: 'targeted',
        evidence: 'positive malignant-cell testing',
      },
    ],
  },
  {
    id: 'peritoneal-dialysis-effusion',
    name: 'Peritoneal dialysis-associated effusion',
    rarity: 'rare',
    category: 'transudate',
    family: 'Extravascular origin',
    summary: 'Dialysate movement into the pleural space through diaphragmatic defects.',
    teachingPearl: 'Very low protein plus unusually high pleural glucose is the clue.',
    nextStep: 'Compare pleural and serum glucose and evaluate dialysate leak.',
    rules: [
      {
        key: 'clinicalContext',
        operator: 'eq',
        value: 'hepatic-renal-systemic',
        weight: 7,
        domain: 'context',
        evidence: 'renal or dialysis frame',
      },
      {
        key: 'pleuralProtein',
        operator: 'lte',
        value: 1,
        weight: 5,
        domain: 'fluid',
        evidence: 'very low pleural protein',
      },
      {
        key: 'pleuralGlucose',
        operator: 'gte',
        value: 180,
        weight: 9,
        domain: 'targeted',
        evidence: 'very high pleural glucose',
      },
      {
        key: 'reconciledCategory',
        operator: 'eq',
        value: 'transudate',
        weight: 4,
        domain: 'fluid',
        evidence: 'transudative chemistry',
      },
    ],
  },
  {
    id: 'central-line-extravasation',
    name: 'Central line extravasation',
    rarity: 'very rare',
    category: 'transudate',
    family: 'Extravascular origin',
    summary:
      'Infusate entering the pleural space after central venous catheter malposition or migration.',
    teachingPearl: 'The pleural fluid can look like the infusate and have extremely low protein.',
    nextStep: 'Check line position and compare pleural chemistry with infused solution.',
    rules: [
      {
        key: 'pleuralProtein',
        operator: 'lte',
        value: 1,
        weight: 8,
        domain: 'fluid',
        evidence: 'protein below 1 g/dL',
      },
      {
        key: 'ultrasound',
        operator: 'eq',
        value: 'anechoic-unilateral',
        weight: 3,
        domain: 'context',
        evidence: 'ipsilateral anechoic effusion pattern',
      },
      {
        key: 'reconciledCategory',
        operator: 'eq',
        value: 'transudate',
        weight: 4,
        domain: 'fluid',
        evidence: 'transudative chemistry',
      },
    ],
  },
] as const
