import type { NormalizedLiteratureArticle } from '@/features/literature/types'

export function literatureArticleDatabaseRow(article: NormalizedLiteratureArticle) {
  return {
    pmid: article.pmid,
    doi: article.doi,
    pmcid: article.pmcid,
    title: article.title,
    abstract: article.abstract,
    abstract_display_policy: article.abstractDisplayPolicy,
    journal_id: article.journalId,
    journal_title: article.journalTitle,
    journal_abbreviation: article.journalAbbreviation,
    nlm_journal_id: article.nlmJournalId,
    issn_values: article.issnValues,
    publication_date_raw: article.publicationDateRaw,
    publication_year: article.publicationYear,
    publication_month: article.publicationMonth,
    publication_day: article.publicationDay,
    publication_date_precision: article.publicationDatePrecision,
    publication_types: article.publicationTypes,
    mesh_terms: article.meshTerms,
    author_keywords: article.authorKeywords,
    languages: article.languages,
    authors: article.authors,
    collective_authors: article.collectiveAuthors,
    affiliations: article.affiliations,
    volume: article.volume,
    issue: article.issue,
    pages: article.pages,
    article_number: article.articleNumber,
    place_of_publication: article.placeOfPublication,
    citation_source: article.citationSource,
    conflict_of_interest: article.conflictOfInterest,
    pubmed_status: article.pubmedStatus,
    pubmed_last_revised_at: article.pubmedLastRevisedAt,
    pubmed_created_at: article.pubmedCreatedAt,
    raw_nbib_tags: article.rawNbibTags,
    metadata_hash: article.metadataHash,
    normalized_title: article.normalizedTitle,
    normalized_title_hash: article.normalizedTitleHash,
    is_retracted: article.isRetracted,
    is_correction: article.isCorrection,
    is_conference_abstract: article.isConferenceAbstract,
  }
}
