import type { CrrtEngineFixture, CrrtScheduledEventDefinition, ExternalFluidRates } from '../types'

const TEST_SOURCE_ID = 'TEST-P2-001'

export const syntheticExternalFluidRates: ExternalFluidRates = {
  maintenanceInputMlHour: 60,
  medicationCarrierInputMlHour: 40,
  nutritionInputMlHour: 30,
  bloodProductInputMlHour: 0,
  bolusInputMlHour: 0,
  otherInputMlHour: 0,
  urineOutputMlHour: 20,
  drainOutputMlHour: 10,
  otherOutputMlHour: 0,
}

export function createSyntheticFixture(
  events: readonly CrrtScheduledEventDefinition[] = [],
): CrrtEngineFixture {
  return {
    id: 'phase2-synthetic-fixture',
    patient: {
      status: 'configured',
      synthetic: true,
      bodyWeightKg: 70,
      hematocritFraction: 0.3,
      intravascularReserveMl: 100,
      initialIntravascularReserveMl: 100,
      totalFluidOverloadMl: 1_000,
      vascularRefillCapacityMlHour: 80,
      urineOutputMlHour: 20,
      residualKidneyClearanceMlMin: 1,
      heartRatePerMinute: 90,
      meanArterialPressureMmHg: 70,
      vasopressorSupportIndex: 0.2,
      temperatureCelsius: 37,
      pH: 7.35,
      systemicIonizedCalciumMmolL: 1,
      totalCalciumMmolL: null,
      glucoseMgDl: null,
      hemodynamicStressIndex: 0,
      solutes: {
        potassium: {
          id: 'potassium',
          amountUnit: 'mmol',
          concentrationUnit: 'mmol/L',
          concentrationPerLiter: 5,
          distributionVolumeLiters: 40,
          productionAmountPerHour: 1,
          inputAmountPerHour: 0,
          residualClearanceMlMin: 1,
          filterPermeabilityFraction: 1,
          reviewStatus: 'pending',
          sourceIds: [TEST_SOURCE_ID],
        },
      },
      reviewStatus: 'pending',
      sourceIds: [TEST_SOURCE_ID],
    },
    access: {
      status: 'configured',
      catheterDescriptor: 'Synthetic Phase 2 access',
      nominalFlowCapacityMlMin: 250,
      accessResistanceMmHgPerMlMin: 0.2,
      returnResistanceMmHgPerMlMin: 0.1,
      positionResistanceMultiplier: 1,
      recirculationFraction: 0,
      partialThrombusFraction: 0,
      accessKinked: false,
      returnKinked: false,
      accessConnected: true,
      returnConnected: true,
      reviewStatus: 'pending',
      sourceIds: [TEST_SOURCE_ID],
    },
    prescription: {
      status: 'configured',
      modality: 'cvvhd',
      flows: {
        bloodFlowMlMin: 200,
        dialysateFlowMlHour: 1_000,
        pbpFlowMlHour: 0,
        preReplacementFlowMlHour: 0,
        postReplacementFlowMlHour: 0,
        patientFluidRemovalMlHour: 100,
        syringeFlowMlHour: 0,
        makeupFlowMlHour: 0,
      },
      anticoagulation: 'none',
      citrateRequestedButDisabled: false,
      reviewStatus: 'pending',
      sourceIds: [TEST_SOURCE_ID],
    },
    bags: [
      {
        id: 'synthetic-dialysate-bag',
        label: 'Synthetic dialysate source',
        flowTerm: 'dialysate',
        direction: 'source',
        capacityMl: 10_000,
        calculatedVolumeMl: 10_000,
        measuredVolumeMl: 10_000,
        cumulativePumpVolumeMl: 0,
        connected: true,
        scaleOpen: false,
        externalInterferenceMl: 0,
        reviewStatus: 'pending',
        sourceIds: [TEST_SOURCE_ID],
      },
      {
        id: 'synthetic-effluent-bag',
        label: 'Synthetic effluent collector',
        flowTerm: 'effluent',
        direction: 'effluent',
        capacityMl: 20_000,
        calculatedVolumeMl: 0,
        measuredVolumeMl: 0,
        cumulativePumpVolumeMl: 0,
        connected: true,
        scaleOpen: false,
        externalInterferenceMl: 0,
        reviewStatus: 'pending',
        sourceIds: [TEST_SOURCE_ID],
      },
    ],
    externalFluidRates: syntheticExternalFluidRates,
    unintendedDeviceNetGainRateMlHour: 0,
    modelConfiguration: {
      pressure: {
        accessReferencePressureMmHg: 5,
        disconnectedAccessPressureMmHg: 0,
        returnReferencePressureMmHg: 5,
        disconnectedReturnPressureMmHg: 0,
        observedEffluentPressureMmHg: -20,
        filterResistanceMmHgPerMlMin: 0.15,
        partialThrombusResistanceGainAtFullBurden: 1,
        foulingResistanceGainMmHgPerMlMinAtFullBurden: 0.1,
        clotResistanceGainMmHgPerMlMinAtFullBurden: 0.1,
        accessKinkResistanceMultiplier: 2,
        returnKinkResistanceMultiplier: 2,
        reviewStatus: 'pending',
        sourceIds: [TEST_SOURCE_ID],
      },
      filter: {
        foulingFractionPerHourAtRiskOne: 0.01,
        clotFractionPerHourAtRiskOne: 0.01,
        filtrationFractionWeight: 1,
        interruptionWeight: 1,
        lowFlowWeight: 1,
        accessDysfunctionWeight: 1,
        hematocritWeight: 1,
        procoagulantWeight: 1,
        anticoagulationProtectionFraction: { none: 0, 'systemic-concept': 0.5 },
        referenceHematocritFraction: 0.25,
        reviewStatus: 'pending',
        sourceIds: [TEST_SOURCE_ID],
      },
      hemodynamic: {
        stressGainPerExcessRemovalLiter: 1,
        stressRecoveryPerHour: 0.1,
        reviewStatus: 'pending',
        sourceIds: [TEST_SOURCE_ID],
      },
      filterInletConcentrationFraction: 1,
      filtrationFraction: 0.2,
      reviewStatus: 'pending',
      sourceIds: [TEST_SOURCE_ID],
    },
    events,
    reviewStatus: 'pending',
    sourceIds: [TEST_SOURCE_ID],
  }
}
