import type { RigidBronchoscopyAssemblyLabCopy } from './RigidBronchoscopyAssemblyLab'

export const rigidBronchoscopyAssemblyCopyKeys = [
  'accessoryInstrumentRoute',
  'accessoryInstrumentRouteDescription',
  'accessoryPortDescription',
  'accessoryPortLabel',
  'activeInterface',
  'anesthesiaCircuitPortDescription',
  'anesthesiaCircuitPortLabel',
  'animationComplete',
  'animationControlsLabel',
  'animationPaused',
  'animationPlaying',
  'animationReady',
  'animationStatusLabel',
  'ambientEntrainmentLegend',
  'assemblyMode',
  'assemblyModeDescription',
  'axialInstrumentRoute',
  'axialInstrumentRouteDescription',
  'bronchoscopePattern',
  'bronchoscopePatternDescription',
  'carinaView',
  'carinaLabel',
  'centerView',
  'commitPrediction',
  'commonScale',
  'complete',
  'controlledProximalLeak',
  'conventionalPulsePattern',
  'conventionalVentilation',
  'conventionalVentilationDescription',
  'crossSectionSafetyNote',
  'cutawayView',
  'description',
  'dragHelp',
  'egressBlocked',
  'egressBlockedDescription',
  'egressLabel',
  'egressOpen',
  'egressOpenDescription',
  'expiratoryEgressLegend',
  'eyebrow',
  'fallbackTitle',
  'highFrequencyJetPulsePattern',
  'highFrequencyJetVentilation',
  'highFrequencyJetVentilationDescription',
  'hint',
  'hubView',
  'illuminationLegend',
  'imageLegend',
  'inspiratoryFlowLegend',
  'instrumentLegend',
  'instrumentRoute',
  'instrumentRouteDescription',
  'jetVentilationPortDescription',
  'jetVentilationPortLabel',
  'labModeLabel',
  'leakEffectLabel',
  'leakEgressContrast',
  'lowFrequencyJetPulsePattern',
  'lowFrequencyJetVentilation',
  'lowFrequencyJetVentilationDescription',
  'magnifiedNotCommonScale',
  'mainAxialPortDescription',
  'mainAxialPortLabel',
  'leftMainstemLabel',
  'majorFenestrationLeak',
  'modelLabel',
  'modeledResultLabel',
  'nominalResidualLumenArea',
  'obstructionBallValve',
  'obstructionBallValveDescription',
  'obstructionFixedComplete',
  'obstructionFixedCompleteDescription',
  'obstructionOpen',
  'obstructionOpenDescription',
  'obstructionStateLabel',
  'openSystemProximalLeak',
  'opticsLight',
  'opticsLightDescription',
  'orbitView',
  'panView',
  'pairedTracheoscopePattern',
  'pairedTracheoscopePatternDescription',
  'pathSafetyNote',
  'pathwayCanvasLabel',
  'pathwayHelp',
  'pathwayMode',
  'pathwayModeDescription',
  'pathwaySelectLabel',
  'pathwayTitle',
  'pauseAnimation',
  'phaseAssist',
  'phaseExpiration',
  'phaseInspiration',
  'phasePassiveEgress',
  'phasePause',
  'placeSelected',
  'playAnimation',
  'portLayoutVariationNote',
  'portMapDistinctInterfaces',
  'portMapEyebrow',
  'positionAtCarina',
  'positionAtCarinaDescription',
  'positionMidTrachea',
  'positionMidTracheaDescription',
  'positionPastCarina',
  'positionPastCarinaDescription',
  'positionRightMainstem',
  'positionRightMainstemDescription',
  'positionLeftMainstem',
  'positionLeftMainstemDescription',
  'positionProximalTrachea',
  'positionProximalTracheaDescription',
  'predictBothBranches',
  'predictContralateralFenestrations',
  'predictMainstemOnly',
  'predictionCorrect',
  'predictionPrompt',
  'predictionReconsider',
  'predictionResetNotice',
  'predictionTitle',
  'proceduralPoseDisclaimer',
  'proximalLeakLegend',
  'pulsePatternLabel',
  'referenceAirwayLumen',
  'removeLast',
  'reset',
  'resetAnimation',
  'respiratoryCycle',
  'respiratoryPhaseLabel',
  'resultBothBranches',
  'resultContralateralFenestrations',
  'resultMainstemOnly',
  'revealModeledFlow',
  'routeTypeLabel',
  'safetyNote',
  'selectTube',
  'selectedMainstemView',
  'rightMainstemLabel',
  'safetyStopLabel',
  'sequenceTitle',
  'sideFenestrationLegend',
  'sidePortAvailable',
  'sidePortFindingLabel',
  'sidePortNotApplicable',
  'sidePortUnavailable',
  'spontaneousAssistPulsePattern',
  'spontaneousAssistVentilation',
  'spontaneousAssistVentilationDescription',
  'tipPositionLabel',
  'telescopeObjectiveLabel',
  'title',
  'toolMode',
  'toolModeDescription',
  'toolsTitle',
  'tracheoscopeMainstemCaution',
  'tracheoscopePattern',
  'tracheoscopePatternDescription',
  'trueScaleCrossSection',
  'trueScaleView',
  'tracheaLabel',
  'tubeBevelLabel',
  'scenarioPresetLabel',
  'advancedControls',
  'customValidatedConfiguration',
  'tubePatternLabel',
  'ventilationComparisonSafetyNote',
  'ventilationFlow',
  'ventilationFlowDescription',
  'ventilationLegend',
  'ventilationModeLabel',
  'ventilationScenarioIntro',
  'ventilationSourceNote',
  'viewControlsLabel',
  'viewHelp',
  'yourPredictionLabel',
  'zoomIn',
  'zoomOut',
] as const satisfies readonly (keyof RigidBronchoscopyAssemblyLabCopy)[]

type AssemblyCopyKey = (typeof rigidBronchoscopyAssemblyCopyKeys)[number]

const hasCompleteAssemblyCopyKeyCoverage: Exclude<
  keyof RigidBronchoscopyAssemblyLabCopy,
  AssemblyCopyKey
> extends never
  ? true
  : never = true

export type RigidBronchoscopyAssemblyCopyMessageKey = `practice.assembly.${AssemblyCopyKey}`

export function buildRigidBronchoscopyAssemblyCopy(
  translate: (key: RigidBronchoscopyAssemblyCopyMessageKey) => string,
): RigidBronchoscopyAssemblyLabCopy {
  void hasCompleteAssemblyCopyKeyCoverage
  return Object.fromEntries(
    rigidBronchoscopyAssemblyCopyKeys.map((key) => [key, translate(`practice.assembly.${key}`)]),
  ) as unknown as RigidBronchoscopyAssemblyLabCopy
}
