import type { RigidBronchoscopyAssemblyLabCopy } from './RigidBronchoscopyAssemblyLab'

export const rigidBronchoscopyAssemblyCopyKeys = [
  'assemblyMode',
  'assemblyModeDescription',
  'animationComplete',
  'animationControlsLabel',
  'animationPaused',
  'animationPlaying',
  'animationReady',
  'animationStatusLabel',
  'centerView',
  'commitPrediction',
  'complete',
  'controlledProximalLeak',
  'conventionalPulsePattern',
  'conventionalVentilation',
  'conventionalVentilationDescription',
  'cutawayView',
  'description',
  'dragHelp',
  'egressBlocked',
  'egressBlockedDescription',
  'egressLabel',
  'egressOpen',
  'egressOpenDescription',
  'eyebrow',
  'fallbackTitle',
  'hint',
  'illuminationLegend',
  'inspiratoryFlowLegend',
  'imageLegend',
  'instrumentLegend',
  'instrumentRoute',
  'instrumentRouteDescription',
  'labModeLabel',
  'leakEffectLabel',
  'leakEgressContrast',
  'lowFrequencyJetPulsePattern',
  'lowFrequencyJetVentilation',
  'lowFrequencyJetVentilationDescription',
  'majorFenestrationLeak',
  'modelLabel',
  'modeledResultLabel',
  'orbitView',
  'opticsLight',
  'opticsLightDescription',
  'panView',
  'pathSafetyNote',
  'pathwayCanvasLabel',
  'pathwayHelp',
  'pathwayMode',
  'pathwayModeDescription',
  'pathwaySelectLabel',
  'pathwayTitle',
  'pauseAnimation',
  'playAnimation',
  'placeSelected',
  'removeLast',
  'reset',
  'resetAnimation',
  'resultBothBranches',
  'resultContralateralFenestrations',
  'resultMainstemOnly',
  'revealModeledFlow',
  'safetyNote',
  'sideFenestrationLegend',
  'sidePortAvailable',
  'sidePortFindingLabel',
  'sidePortNotApplicable',
  'sidePortUnavailable',
  'selectTube',
  'sequenceTitle',
  'title',
  'tipPositionLabel',
  'toolMode',
  'toolModeDescription',
  'toolsTitle',
  'viewControlsLabel',
  'viewHelp',
  'ventilationFlow',
  'ventilationFlowDescription',
  'ventilationLegend',
  'ventilationModeLabel',
  'ventilationScenarioIntro',
  'ventilationComparisonSafetyNote',
  'ventilationSourceNote',
  'bronchoscopePattern',
  'bronchoscopePatternDescription',
  'tracheoscopePattern',
  'tracheoscopePatternDescription',
  'tubePatternLabel',
  'positionAtCarina',
  'positionAtCarinaDescription',
  'positionPastCarina',
  'positionPastCarinaDescription',
  'positionProximalTrachea',
  'positionProximalTracheaDescription',
  'predictionCorrect',
  'predictionPrompt',
  'predictionReconsider',
  'predictionResetNotice',
  'predictionTitle',
  'predictBothBranches',
  'predictContralateralFenestrations',
  'predictMainstemOnly',
  'proximalLeakLegend',
  'pulsePatternLabel',
  'spontaneousAssistPulsePattern',
  'spontaneousAssistVentilation',
  'spontaneousAssistVentilationDescription',
  'openSystemProximalLeak',
  'tracheoscopeMainstemCaution',
  'highFrequencyJetPulsePattern',
  'highFrequencyJetVentilation',
  'highFrequencyJetVentilationDescription',
  'expiratoryEgressLegend',
  'yourPredictionLabel',
  'zoomIn',
  'zoomOut',
] as const satisfies readonly (keyof RigidBronchoscopyAssemblyLabCopy)[]

type AssemblyCopyKey = (typeof rigidBronchoscopyAssemblyCopyKeys)[number]

const hasCompleteAssemblyCopyKeyCoverage: Exclude<
  keyof RigidBronchoscopyAssemblyLabCopy,
  AssemblyCopyKey
> extends never
  ? true
  : never = true

export type RigidBronchoscopyAssemblyCopyMessageKey = `practice.assembly.${AssemblyCopyKey}`

export function buildRigidBronchoscopyAssemblyCopy(
  translate: (key: RigidBronchoscopyAssemblyCopyMessageKey) => string,
): RigidBronchoscopyAssemblyLabCopy {
  void hasCompleteAssemblyCopyKeyCoverage
  return Object.fromEntries(
    rigidBronchoscopyAssemblyCopyKeys.map((key) => [key, translate(`practice.assembly.${key}`)]),
  ) as unknown as RigidBronchoscopyAssemblyLabCopy
}
