export const PROTECTED_V2_CATALOG_DRIFT_MATRIX_SCHEMA_VERSION =
  'literature-gold-protected-v2-catalog-drift-matrix/1.1.0' as const

/** Pure, file-only identity tuple. The executable matrix sentinel binds its live probes to this. */
export const PROTECTED_V2_CATALOG_DRIFT_PROBE_IDS = [
  'arbitrary_component_hash_with_recomputed_full_audit',
  'arbitrary_profile_identity_with_recomputed_full_audit',
  'arbitrary_full_inventory_identity_with_recomputed_full_audit',
  'local_expectation_profile_on_disposable_observation',
  'disposable_expectation_profile_on_local_observation',
  'change_single_table_owner_preserving_count',
  'change_multiple_table_owners_preserving_count',
  'disable_row_level_security',
  'change_force_row_level_security_state',
  'alter_policy_role',
  'alter_policy_using_expression',
  'alter_policy_with_check_expression',
  'same_name_policy_definition_replacement',
  'drop_required_policy',
  'grant_service_role_forbidden_update',
  'grant_service_role_forbidden_insert',
  'grant_public_forbidden_insert',
  'grant_anon_forbidden_insert',
  'grant_authenticated_forbidden_insert',
  'change_acl_grantor_preserving_count',
  'replace_privilege_preserving_acl_count',
  'substitute_acl_record_preserving_count',
  'change_column_default',
  'change_column_nullability',
  'remove_generated_expression',
  'drop_required_check_constraint',
  'replace_check_constraint_with_weaker_definition',
  'introduce_unvalidated_constraint_state',
  'drop_required_foreign_key',
  'drop_required_unique_index',
  'change_required_partial_unique_index',
  'equal_count_index_object_substitution',
  'mark_required_index_invalid',
  'disable_required_trigger',
  'redirect_required_trigger_function',
  'change_function_body',
  'change_function_volatility',
  'change_function_search_path',
  'change_function_owner',
  'broaden_function_execute_acl',
  'add_undeclared_function_overload',
  'change_function_dependency',
] as const
