import type { PneumothoraxCase } from '../engine/types'

export const pneumothoraxCases: readonly PneumothoraxCase[] = [
  {
    id: 'stable-minimal-psp',
    title: 'Stable minimally symptomatic PSP',
    type: 'psp',
    symptomBurden: 'minimal',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: false,
    persistentAirLeakDays: 0,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue: 'Size alone should not automatically drive drainage.',
  },
  {
    id: 'stable-symptomatic-psp',
    title: 'Stable symptomatic PSP',
    type: 'psp',
    symptomBurden: 'moderate',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: false,
    persistentAirLeakDays: 0,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue: 'Aspiration or ambulatory care may fit when follow-up is robust.',
  },
  {
    id: 'copd-ssp',
    title: 'COPD secondary pneumothorax',
    type: 'ssp',
    symptomBurden: 'moderate',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: true,
    persistentAirLeakDays: 1,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue: 'Secondary pneumothorax has less reserve than PSP.',
  },
  {
    id: 'unstable-tension',
    title: 'Unstable pneumothorax physiology',
    type: 'psp',
    symptomBurden: 'severe',
    hemodynamicCompromise: true,
    severeHypoxemia: true,
    underlyingLungDisease: false,
    persistentAirLeakDays: 0,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue: 'Physiology overrides all lower-risk branches.',
  },
  {
    id: 'persistent-air-leak',
    title: 'Persistent air leak on day 5',
    type: 'ssp',
    symptomBurden: 'moderate',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: true,
    persistentAirLeakDays: 5,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue: 'Escalation is time-bounded after drain and system checks.',
  },
  {
    id: 'recurrent-pilot',
    title: 'Recurrent PSP in a pilot',
    type: 'psp',
    symptomBurden: 'minimal',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: false,
    persistentAirLeakDays: 0,
    recurrence: 'ipsilateral',
    highRiskOccupation: true,
    ventilated: false,
    learningCue: 'Occupation and recurrence change prevention discussions.',
  },
]
