import type { PneumothoraxCase } from '../engine/types'

export const pneumothoraxCases: readonly PneumothoraxCase[] = [
  {
    id: 'stable-minimal-psp',
    title: 'Stable minimally symptomatic primary pneumothorax',
    type: 'psp',
    sizeCategory: 'large',
    accpVitals: {
      respiratoryRate: 18,
      heartRate: 88,
      roomAirSpo2: 96,
      bloodPressureStable: true,
      speaksFullSentences: true,
    },
    symptomBurden: 'minimal',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: false,
    persistentAirLeakDays: 0,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue:
      'Large primary spontaneous pneumothorax on imaging, but the patient is comfortable and follow-up is reliable.',
  },
  {
    id: 'stable-symptomatic-psp',
    title: 'Stable symptomatic primary pneumothorax',
    type: 'psp',
    sizeCategory: 'small',
    accpVitals: {
      respiratoryRate: 20,
      heartRate: 98,
      roomAirSpo2: 95,
      bloodPressureStable: true,
      speaksFullSentences: true,
    },
    symptomBurden: 'moderate',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: false,
    persistentAirLeakDays: 0,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue:
      'Small primary spontaneous pneumothorax, but dyspnea and chest pain are driving the encounter.',
  },
  {
    id: 'copd-ssp',
    title: 'COPD secondary pneumothorax',
    type: 'ssp',
    sizeCategory: 'small',
    accpVitals: {
      respiratoryRate: 22,
      heartRate: 104,
      roomAirSpo2: 91,
      bloodPressureStable: true,
      speaksFullSentences: true,
    },
    symptomBurden: 'moderate',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: true,
    persistentAirLeakDays: 1,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue:
      'Secondary spontaneous pneumothorax in chronic obstructive pulmonary disease with limited respiratory reserve.',
  },
  {
    id: 'unstable-tension',
    title: 'Unstable pneumothorax physiology',
    type: 'psp',
    sizeCategory: 'large',
    accpVitals: {
      respiratoryRate: 32,
      heartRate: 134,
      roomAirSpo2: 84,
      bloodPressureStable: false,
      speaksFullSentences: false,
    },
    symptomBurden: 'severe',
    hemodynamicCompromise: true,
    severeHypoxemia: true,
    underlyingLungDisease: false,
    persistentAirLeakDays: 0,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue:
      'Hypotension, severe hypoxemia, and inability to speak full sentences override lower-risk branches.',
  },
  {
    id: 'persistent-air-leak',
    title: 'Persistent air leak on day 5',
    type: 'ssp',
    sizeCategory: 'large',
    accpVitals: {
      respiratoryRate: 21,
      heartRate: 96,
      roomAirSpo2: 93,
      bloodPressureStable: true,
      speaksFullSentences: true,
    },
    symptomBurden: 'moderate',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: true,
    persistentAirLeakDays: 5,
    recurrence: 'none',
    highRiskOccupation: false,
    ventilated: false,
    learningCue:
      'Air bubbling persists after drain-position and drainage-system checks on the fifth day.',
  },
  {
    id: 'recurrent-pilot',
    title: 'Recurrent primary pneumothorax in a pilot',
    type: 'psp',
    sizeCategory: 'small',
    accpVitals: {
      respiratoryRate: 16,
      heartRate: 82,
      roomAirSpo2: 98,
      bloodPressureStable: true,
      speaksFullSentences: true,
    },
    symptomBurden: 'minimal',
    hemodynamicCompromise: false,
    severeHypoxemia: false,
    underlyingLungDisease: false,
    persistentAirLeakDays: 0,
    recurrence: 'ipsilateral',
    highRiskOccupation: true,
    ventilated: false,
    learningCue:
      'Recurrent primary spontaneous pneumothorax in a pilot changes the recurrence-prevention discussion.',
  },
]
