import type {
  IabpDeviceState,
  ImpellaDeviceState,
  LvadDeviceState,
  McsPatientState,
  McsScenarioDefinition,
} from '../engine/types'

export const defaultMcsPatient: McsPatientState = {
  heartRateBpm: 96,
  rhythm: 'sinus',
  preloadPercent: 105,
  systemicVascularResistanceDynSecCm5: 1150,
  leftVentricularContractility: 0.46,
  rightVentricularContractility: 0.85,
  pulmonaryVascularResistanceWU: 2.5,
  peepCmH2O: 5,
  aorticInsufficiencySeverity: 0,
  tamponade: false,
}

export const defaultIabpDevice: IabpDeviceState = {
  kind: 'iabp',
  running: true,
  assistRatio: 1,
  triggerSource: 'ecg',
  inflationOffsetMs: 0,
  deflationOffsetMs: 0,
}

export const defaultImpellaDevice: ImpellaDeviceState = {
  kind: 'impella',
  left: {
    enabled: true,
    variant: 'cp',
    running: true,
    performanceLevel: 5,
    position: 'correct',
    purgeState: 'normal',
  },
  right: {
    enabled: false,
    variant: 'rp',
    running: true,
    performanceLevel: 5,
    position: 'correct',
    purgeState: 'normal',
  },
}

export const defaultLvadDevice: LvadDeviceState = {
  kind: 'lvad',
  running: true,
  speedRpm: 5200,
  speedChangeAuthorized: false,
  powerConnected: true,
  controllerFault: false,
  suspectedPumpThrombosis: false,
}

function patient(overrides: Partial<McsPatientState>): McsPatientState {
  return { ...defaultMcsPatient, ...overrides }
}

function impella(
  left: Partial<ImpellaDeviceState['left']> = {},
  right: Partial<ImpellaDeviceState['right']> = {},
): ImpellaDeviceState {
  return {
    kind: 'impella',
    left: { ...defaultImpellaDevice.left, ...left },
    right: { ...defaultImpellaDevice.right, ...right },
  }
}

const commonSources = [
  'master-hemodynamics-reference',
  'ishlt-hfsa-acute-mcs-2023',
  'mcs-educational-model-v1',
] as const
const lvadSources = [
  'ishlt-durable-mcs-2023',
  'fda-heartmate3-ifu',
  'mcs-educational-model-v1',
] as const

export const mcsPracticeScenarios: readonly McsScenarioDefinition[] = [
  {
    id: 'IABP-01',
    version: '1.0.0',
    kind: 'practice',
    device: 'iabp',
    title: 'The balloon that stays inflated too long',
    shortTitle: 'Late deflation',
    presentation:
      'An LV-predominant shock patient has weak augmentation and a higher assisted end-diastolic pressure after a timing change.',
    learningObjectives: [
      'Identify late deflation on the arterial waveform.',
      'Restore pre-systolic deflation and reassess perfusion.',
    ],
    initialPatient: patient({ leftVentricularContractility: 0.42 }),
    initialDevice: { ...defaultIabpDevice, deflationOffsetMs: 150 },
    hiddenFaultIds: ['iabp-late-deflation'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'iabp:set-deflation',
      'iabp:set-inflation',
      'iabp:set-trigger',
      'iabp:set-ratio',
      'team:escalate',
    ],
    criticalErrorIds: ['iabp-late-deflation-created'],
    predictionPrompt: 'What best explains the assisted waveform?',
    predictionOptions: [
      { id: 'late-deflation', label: 'Late deflation raises effective LV afterload' },
      { id: 'underfilled', label: 'Low preload is the primary problem' },
      { id: 'low-svr', label: 'Vasoplegia explains the contour' },
    ],
    correctPredictionId: 'late-deflation',
    requiredActionIds: ['inspect:arterial', 'iabp:set-deflation'],
    successCriteria: [
      {
        metric: 'timingQualityPercent',
        operator: 'at-least',
        value: 80,
        label: 'Timing quality ≥80%',
      },
      { metric: 'mapMmHg', operator: 'at-least', value: 58, label: 'MAP ≥58 mm Hg' },
    ],
    guidedPrompt: 'Compare assisted end-diastolic pressure with the next systolic upstroke.',
    debrief: [
      'Deflation should be complete before ejection.',
      'Late deflation can worsen rather than reduce LV afterload.',
    ],
    sourceIds: [...commonSources, 'getinge-iabp-current'],
    evidenceSourceIds: [...commonSources, 'getinge-iabp-current'],
  },
  {
    id: 'IABP-02',
    version: '1.0.0',
    kind: 'practice',
    device: 'iabp',
    title: 'Irregular rhythm, unreliable trigger',
    shortTitle: 'Trigger mismatch',
    presentation:
      'A patient in atrial fibrillation has inconsistent assisted beats and variable augmentation.',
    learningObjectives: [
      'Recognize trigger unreliability in irregular rhythm.',
      'Choose the best available simulated trigger and confirm the waveform.',
    ],
    initialPatient: patient({ rhythm: 'atrial-fibrillation', heartRateBpm: 128 }),
    initialDevice: { ...defaultIabpDevice, triggerSource: 'ecg', assistRatio: 2 },
    hiddenFaultIds: ['irregular-rhythm-trigger-mismatch'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'iabp:set-trigger',
      'iabp:set-ratio',
      'iabp:set-inflation',
      'iabp:set-deflation',
      'team:escalate',
    ],
    criticalErrorIds: ['iabp-late-deflation-created'],
    predictionPrompt: 'What should be checked first?',
    predictionOptions: [
      { id: 'trigger', label: 'Trigger source and beat recognition' },
      { id: 'more-volume', label: 'Give volume without further bedside review' },
      { id: 'inflate-early', label: 'Move inflation before valve closure' },
    ],
    correctPredictionId: 'trigger',
    requiredActionIds: ['inspect:arterial', 'iabp:set-trigger', 'iabp:set-ratio'],
    successCriteria: [
      {
        metric: 'timingQualityPercent',
        operator: 'at-least',
        value: 60,
        label: 'Usable trigger/timing quality',
      },
    ],
    guidedPrompt:
      'Use the arterial contour to verify each assisted beat after changing the trigger.',
    debrief: [
      'An irregular rhythm reduces trigger reliability and time available for counterpulsation.',
      'The waveform—not the selected mode alone—confirms useful timing.',
    ],
    sourceIds: [...commonSources, 'getinge-iabp-current'],
    evidenceSourceIds: [...commonSources, 'getinge-iabp-current'],
  },
  {
    id: 'IABP-03',
    version: '1.0.0',
    kind: 'practice',
    device: 'iabp',
    title: 'Correct timing, inadequate circulation',
    shortTitle: 'Support ceiling',
    presentation:
      'Counterpulsation is well timed, but profound LV failure and poor RV delivery leave effective flow critically low.',
    learningObjectives: [
      'Recognize a technically effective device with inadequate physiologic support.',
      'Escalate by phenotype rather than repeatedly changing timing.',
    ],
    initialPatient: patient({
      leftVentricularContractility: 0.28,
      rightVentricularContractility: 0.48,
      preloadPercent: 82,
    }),
    initialDevice: { ...defaultIabpDevice },
    hiddenFaultIds: ['profound-biventricular-failure'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'iabp:set-trigger',
      'iabp:set-ratio',
      'iabp:set-inflation',
      'iabp:set-deflation',
      'patient:adjust',
      'team:escalate',
    ],
    criticalErrorIds: ['iabp-late-deflation-created'],
    predictionPrompt: 'Why does perfusion remain inadequate?',
    predictionOptions: [
      {
        id: 'support-ceiling',
        label: 'IABP cannot replace profoundly limited native biventricular output',
      },
      { id: 'late-inflation', label: 'Inflation is too late' },
      { id: 'excess-flow', label: 'The balloon is providing excessive continuous flow' },
    ],
    correctPredictionId: 'support-ceiling',
    requiredActionIds: ['inspect:preload', 'inspect:device', 'team:escalate'],
    successCriteria: [
      {
        metric: 'timingQualityPercent',
        operator: 'at-least',
        value: 80,
        label: 'Timing remains technically adequate',
      },
    ],
    guidedPrompt: 'Separate device timing from the amount of native LV and RV output available.',
    debrief: [
      'IABP provides modest support and requires native ejection.',
      'Persistent hypoperfusion should trigger shock-team reassessment.',
    ],
    sourceIds: commonSources,
    evidenceSourceIds: commonSources,
  },
  {
    id: 'IMP-01',
    version: '1.0.0',
    kind: 'practice',
    device: 'impella',
    title: 'High support, underfilled LV',
    shortTitle: 'Suction physiology',
    presentation:
      'At a high performance level, device flow falls, PCWP is low, RAP is rising, and a suction alarm appears.',
    learningObjectives: [
      'Recognize preload/RV-limited support.',
      'Reduce support temporarily and restore LV filling.',
    ],
    initialPatient: patient({
      preloadPercent: 64,
      rightVentricularContractility: 0.42,
      pulmonaryVascularResistanceWU: 5.5,
    }),
    initialDevice: impella({ performanceLevel: 8 }),
    hiddenFaultIds: ['rv-limited-lv-filling', 'impella-left-suction'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'impella:left:set-level',
      'impella:left:set-position',
      'impella:left:set-purge',
      'patient:adjust',
      'patient:set-preload',
      'patient:set-rv',
      'patient:set-pvr',
      'team:escalate',
    ],
    criticalErrorIds: ['impella-escalated-through-suction'],
    predictionPrompt: 'What most likely limits pump flow?',
    predictionOptions: [
      { id: 'rv-preload', label: 'Inadequate LV filling from RV/preload limitation' },
      { id: 'raise-level', label: 'The performance level is too low' },
      { id: 'vasoplegia', label: 'Low afterload is the main limit' },
    ],
    correctPredictionId: 'rv-preload',
    requiredActionIds: ['inspect:preload', 'impella:left:set-level', 'patient:set-preload'],
    successCriteria: [
      { metric: 'rapMmHg', operator: 'at-most', value: 18, label: 'RAP not progressively rising' },
      {
        metric: 'deviceFlowLMin',
        operator: 'at-least',
        value: 2,
        label: 'Stable device flow ≥2 L/min',
      },
    ],
    guidedPrompt:
      'Do not escalate through suction. Reconcile RAP, PCWP, RV delivery, and LV volume.',
    debrief: [
      'Suction is a cause-finding problem, not simply a low-setting problem.',
      'RV failure can be the first explanation for falling LV-device flow.',
    ],
    sourceIds: [...commonSources, 'fda-impella-cp-labeling'],
    evidenceSourceIds: [...commonSources, 'fda-impella-cp-labeling'],
  },
  {
    id: 'IMP-02',
    version: '1.0.0',
    kind: 'practice',
    device: 'impella',
    title: 'Malposition with blood-trauma risk',
    shortTitle: 'Placement signal',
    presentation:
      'Displayed flow is below expectation, the motor-current pattern is abnormal, and hemolysis risk is rising.',
    learningObjectives: [
      'Relate malposition to low effective support.',
      'Correct the simulated position before escalating flow.',
    ],
    initialPatient: patient({ preloadPercent: 105 }),
    initialDevice: impella({ position: 'too-deep', performanceLevel: 7 }),
    hiddenFaultIds: ['impella-too-deep', 'hemolysis-risk'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'impella:left:set-level',
      'impella:left:set-position',
      'impella:left:set-purge',
      'patient:adjust',
      'team:escalate',
    ],
    criticalErrorIds: ['impella-escalated-through-suction'],
    predictionPrompt: 'Which finding should drive the next action?',
    predictionOptions: [
      { id: 'malposition', label: 'Abnormal position signal with low effective flow' },
      { id: 'low-level', label: 'Performance level is inadequate' },
      { id: 'normal', label: 'This is expected at high support' },
    ],
    correctPredictionId: 'malposition',
    requiredActionIds: ['inspect:device', 'impella:left:set-position'],
    successCriteria: [
      {
        metric: 'deviceFlowLMin',
        operator: 'at-least',
        value: 2.5,
        label: 'Effective device flow restored',
      },
    ],
    guidedPrompt: 'Correct placement in the simulation before changing support.',
    debrief: [
      'Malposition can reduce flow and increase hemolysis risk.',
      'Real repositioning requires imaging and qualified operators.',
    ],
    sourceIds: [...commonSources, 'fda-impella-cp-labeling'],
    evidenceSourceIds: [...commonSources, 'fda-impella-cp-labeling'],
  },
  {
    id: 'IMP-03',
    version: '1.0.0',
    kind: 'practice',
    device: 'impella',
    title: 'Low flow across high afterload',
    shortTitle: 'Afterload + purge',
    presentation:
      'The performance level is unchanged, MAP/SVR are high, estimated flow has fallen, and purge pressure is elevated.',
    learningObjectives: [
      'Recognize afterload-sensitive pump flow.',
      'Separate patient afterload from a purge-system warning.',
    ],
    initialPatient: patient({ systemicVascularResistanceDynSecCm5: 1900 }),
    initialDevice: impella({ performanceLevel: 6, purgeState: 'high-pressure' }),
    hiddenFaultIds: ['high-systemic-afterload', 'purge-high-pressure'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'impella:left:set-level',
      'impella:left:set-position',
      'impella:left:set-purge',
      'patient:adjust',
      'patient:set-svr',
      'team:escalate',
    ],
    criticalErrorIds: ['impella-escalated-through-suction'],
    predictionPrompt: 'What combination best explains the display?',
    predictionOptions: [
      {
        id: 'afterload-purge',
        label: 'High afterload limits flow while purge pressure needs separate evaluation',
      },
      { id: 'suction-only', label: 'Isolated suction despite high filling pressure' },
      { id: 'normal', label: 'No action is needed' },
    ],
    correctPredictionId: 'afterload-purge',
    requiredActionIds: ['inspect:device', 'patient:set-svr', 'impella:left:set-purge'],
    successCriteria: [
      { metric: 'mapMmHg', operator: 'at-most', value: 100, label: 'Excess afterload reduced' },
      { metric: 'deviceFlowLMin', operator: 'at-least', value: 2.5, label: 'Pump flow improves' },
    ],
    guidedPrompt:
      'Treat the patient–pump gradient and purge warning as related observations, not one diagnosis.',
    debrief: [
      'Higher aortic pressure can reduce microaxial flow at the same setting.',
      'Purge abnormalities require current device instructions and expert support.',
    ],
    sourceIds: [...commonSources, 'fda-impella-cp-labeling'],
    evidenceSourceIds: [...commonSources, 'fda-impella-cp-labeling'],
  },
  {
    id: 'LVAD-01',
    version: '1.0.0',
    kind: 'practice',
    device: 'lvad',
    title: 'Low flow with severe hypertension',
    shortTitle: 'Afterload-limited flow',
    presentation:
      'A durable LVAD patient has a low-flow alarm, elevated MAP, high SVR, and preserved filling.',
    learningObjectives: [
      'Recognize afterload-limited LVAD flow.',
      'Avoid reflexive volume or unauthorized speed changes.',
    ],
    initialPatient: patient({ systemicVascularResistanceDynSecCm5: 2050, preloadPercent: 112 }),
    initialDevice: { ...defaultLvadDevice },
    hiddenFaultIds: ['high-systemic-afterload'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'patient:adjust',
      'patient:set-svr',
      'lvad:authorize-speed',
      'lvad:set-speed',
      'lvad:set-power',
      'team:escalate',
    ],
    criticalErrorIds: ['lvad-unauthorized-speed-change', 'lvad-power-disconnected-by-learner'],
    predictionPrompt: 'What is the leading mechanism?',
    predictionOptions: [
      { id: 'hypertension', label: 'Excess afterload across the pump' },
      { id: 'hypovolemia', label: 'Severe hypovolemia' },
      { id: 'power', label: 'Complete power loss' },
    ],
    correctPredictionId: 'hypertension',
    requiredActionIds: ['inspect:device', 'inspect:arterial', 'patient:set-svr'],
    successCriteria: [
      {
        metric: 'mapMmHg',
        operator: 'at-most',
        value: 95,
        label: 'MAP returns to modeled target range',
      },
      {
        metric: 'deviceFlowLMin',
        operator: 'at-least',
        value: 3.2,
        label: 'Flow improves without speed change',
      },
    ],
    guidedPrompt: 'Compare MAP, filling, speed, flow, and power before changing the pump.',
    debrief: [
      'Continuous-flow LVAD output is afterload sensitive.',
      'Low flow does not automatically mean low volume.',
    ],
    sourceIds: lvadSources,
    evidenceSourceIds: lvadSources,
  },
  {
    id: 'LVAD-02',
    version: '1.0.0',
    kind: 'practice',
    device: 'lvad',
    title: 'Low flow with a failing right ventricle',
    shortTitle: 'RV-limited LVAD',
    presentation:
      'LVAD flow is low, RAP is high, PCWP is low-normal, PAPi is reduced, and pulmonary vascular load is elevated.',
    learningObjectives: [
      'Identify RV-limited LVAD filling.',
      'Reassess both ventricles before changing speed.',
    ],
    initialPatient: patient({
      rightVentricularContractility: 0.36,
      pulmonaryVascularResistanceWU: 6.2,
      preloadPercent: 92,
    }),
    initialDevice: { ...defaultLvadDevice },
    hiddenFaultIds: ['right-ventricular-failure', 'high-pvr'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'patient:adjust',
      'patient:set-rv',
      'patient:set-pvr',
      'lvad:authorize-speed',
      'lvad:set-speed',
      'team:escalate',
    ],
    criticalErrorIds: ['lvad-unauthorized-speed-change', 'lvad-power-disconnected-by-learner'],
    predictionPrompt: 'What is the dominant mechanism?',
    predictionOptions: [
      { id: 'rv-failure', label: 'RV failure limits LVAD preload' },
      { id: 'afterload', label: 'Isolated systemic hypertension' },
      { id: 'thrombosis', label: 'Pump thrombosis with high power' },
    ],
    correctPredictionId: 'rv-failure',
    requiredActionIds: ['inspect:preload', 'patient:set-rv', 'patient:set-pvr', 'team:escalate'],
    successCriteria: [
      { metric: 'papi', operator: 'at-least', value: 1, label: 'PAPi improves' },
      {
        metric: 'deviceFlowLMin',
        operator: 'at-least',
        value: 2.8,
        label: 'LVAD filling and flow improve',
      },
    ],
    guidedPrompt: 'Use RAP, PCWP, PAPi, and the LV size together.',
    debrief: [
      'A durable LVAD still depends on right-sided delivery.',
      'Raising speed cannot create preload and may worsen suction.',
    ],
    sourceIds: lvadSources,
    evidenceSourceIds: lvadSources,
  },
  {
    id: 'LVAD-03',
    version: '1.0.0',
    kind: 'practice',
    device: 'lvad',
    title: 'Controller alarm after power interruption',
    shortTitle: 'Power emergency',
    presentation:
      'The controller reports loss of external power and modeled pump flow falls to zero.',
    learningObjectives: [
      'Recognize a time-critical loss-of-support pattern.',
      'Restore the simulated power path and escalate immediately.',
    ],
    initialPatient: patient({ leftVentricularContractility: 0.32 }),
    initialDevice: { ...defaultLvadDevice, powerConnected: false },
    hiddenFaultIds: ['external-power-loss'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'lvad:set-power',
      'team:escalate',
    ],
    criticalErrorIds: ['lvad-unauthorized-speed-change', 'lvad-power-disconnected-by-learner'],
    predictionPrompt: 'What is the immediate simulated priority?',
    predictionOptions: [
      { id: 'restore-power', label: 'Restore an approved power source and call the LVAD team' },
      { id: 'speed-up', label: 'Increase speed while power is absent' },
      { id: 'observe', label: 'Wait for spontaneous recovery' },
    ],
    correctPredictionId: 'restore-power',
    requiredActionIds: ['inspect:device', 'lvad:set-power', 'team:escalate'],
    successCriteria: [
      {
        metric: 'deviceFlowLMin',
        operator: 'at-least',
        value: 3,
        label: 'Modeled pump flow restored',
      },
      { metric: 'mapMmHg', operator: 'at-least', value: 55, label: 'Perfusion pressure recovers' },
    ],
    guidedPrompt: 'Treat loss of continuous-flow support as time critical.',
    debrief: [
      'Preserve power and use current device emergency procedures.',
      'This simulator does not teach controller exchange or establish readiness for emergency operation.',
    ],
    sourceIds: lvadSources,
    evidenceSourceIds: lvadSources,
  },
] as const

export const mcsCapstoneScenarios: readonly McsScenarioDefinition[] = [
  {
    id: 'CAP-IABP-01',
    version: '1.0.0',
    kind: 'capstone',
    device: 'iabp',
    title: 'Advanced IABP counterpulsation challenge',
    shortTitle: 'IABP capstone',
    presentation:
      'During rapid atrial fibrillation, assisted beats are intermittent, diastolic augmentation is delayed and truncated, and the next systolic pressure is not reduced.',
    learningObjectives: [
      'Integrate rhythm, trigger, assist ratio, and both timing landmarks.',
      'Restore useful counterpulsation without creating systolic impedance.',
    ],
    initialPatient: patient({
      rhythm: 'atrial-fibrillation',
      heartRateBpm: 138,
      leftVentricularContractility: 0.38,
    }),
    initialDevice: {
      ...defaultIabpDevice,
      assistRatio: 3,
      triggerSource: 'internal',
      inflationOffsetMs: 110,
      deflationOffsetMs: -110,
    },
    hiddenFaultIds: ['trigger-mismatch', 'late-inflation', 'early-deflation'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'iabp:set-trigger',
      'iabp:set-ratio',
      'iabp:set-inflation',
      'iabp:set-deflation',
      'team:escalate',
    ],
    criticalErrorIds: ['iabp-late-deflation-created'],
    predictionPrompt: 'Which combined mechanism best explains the contour?',
    predictionOptions: [
      {
        id: 'trigger-plus-timing',
        label: 'Trigger mismatch with late inflation and early deflation',
      },
      { id: 'late-deflation', label: 'Isolated late deflation' },
      { id: 'volume-only', label: 'Preload alone explains every assisted-beat change' },
    ],
    correctPredictionId: 'trigger-plus-timing',
    requiredActionIds: [
      'inspect:arterial',
      'inspect:device',
      'iabp:set-trigger',
      'iabp:set-ratio',
      'iabp:set-inflation',
      'iabp:set-deflation',
    ],
    successCriteria: [
      {
        metric: 'timingQualityPercent',
        operator: 'at-least',
        value: 65,
        label: 'Trigger/timing quality ≥65%',
      },
      { metric: 'mapMmHg', operator: 'at-least', value: 50, label: 'MAP ≥50 mm Hg' },
    ],
    guidedPrompt: '',
    debrief: [
      'Rapid irregular rhythm narrows the counterpulsation window and exposes trigger limitations.',
      'Both inflation and deflation landmarks must be confirmed on the live waveform.',
    ],
    sourceIds: [...commonSources, 'getinge-iabp-current'],
    evidenceSourceIds: [...commonSources, 'getinge-iabp-current'],
  },
  {
    id: 'CAP-IMP-01',
    version: '1.0.0',
    kind: 'capstone',
    device: 'impella',
    title: 'Advanced Impella effective-flow challenge',
    shortTitle: 'Impella capstone',
    presentation:
      'Displayed pump activity persists, but effective flow is disproportionately low with a position warning, hypertension, and a widened gap between gross and effective flow.',
    learningObjectives: [
      'Separate displayed, recirculating, and effective flow.',
      'Resolve placement and patient–pump gradient before escalating support.',
    ],
    initialPatient: patient({
      preloadPercent: 108,
      systemicVascularResistanceDynSecCm5: 1750,
      aorticInsufficiencySeverity: 0.65,
    }),
    initialDevice: impella({ performanceLevel: 6, position: 'too-shallow' }),
    hiddenFaultIds: [
      'impella-too-shallow',
      'high-systemic-afterload',
      'aortic-regurgitant-recirculation',
    ],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'impella:left:set-level',
      'impella:left:set-position',
      'patient:adjust',
      'patient:set-svr',
      'team:escalate',
    ],
    criticalErrorIds: ['impella-escalated-through-suction'],
    predictionPrompt: 'What best explains the ineffective support?',
    predictionOptions: [
      {
        id: 'position-afterload-recirculation',
        label: 'Malposition plus a high gradient and regurgitant recirculation',
      },
      { id: 'suction', label: 'Isolated preload-related suction' },
      { id: 'purge', label: 'Purge pressure alone explains systemic flow' },
    ],
    correctPredictionId: 'position-afterload-recirculation',
    requiredActionIds: [
      'inspect:arterial',
      'inspect:device',
      'impella:left:set-position',
      'patient:set-svr',
      'patient:adjust',
      'team:escalate',
    ],
    successCriteria: [
      {
        metric: 'deviceFlowLMin',
        operator: 'at-least',
        value: 2.4,
        label: 'Device flow ≥2.4 L/min',
      },
      {
        metric: 'recirculatingFlowLMin',
        operator: 'at-most',
        value: 0.5,
        label: 'Recirculation ≤0.5 L/min',
      },
    ],
    guidedPrompt: '',
    debrief: [
      'Gross pump flow and effective systemic flow diverge when blood recirculates.',
      'Position and pressure gradient should be reconciled before increasing support.',
    ],
    sourceIds: [...commonSources, 'fda-impella-cp-labeling'],
    evidenceSourceIds: [...commonSources, 'fda-impella-cp-labeling'],
  },
  {
    id: 'CAP-LVAD-01',
    version: '1.0.0',
    kind: 'capstone',
    device: 'lvad',
    title: 'Advanced durable-LVAD constrained-filling challenge',
    shortTitle: 'LVAD capstone',
    presentation:
      'A continuous-flow LVAD patient develops low flow with rising and converging filling pressures after a bedside procedure; speed and power are unchanged.',
    learningObjectives: [
      'Differentiate constrained filling from hypertension, hypovolemia, and pump thrombosis.',
      'Avoid unauthorized speed changes and escalate definitive evaluation.',
    ],
    initialPatient: patient({
      preloadPercent: 116,
      rightVentricularContractility: 0.7,
      tamponade: true,
    }),
    initialDevice: { ...defaultLvadDevice },
    hiddenFaultIds: ['pericardial-constraint'],
    permittedActionIds: [
      'inspect:arterial',
      'inspect:preload',
      'inspect:device',
      'patient:set-tamponade',
      'lvad:authorize-speed',
      'lvad:set-speed',
      'team:escalate',
    ],
    criticalErrorIds: ['lvad-unauthorized-speed-change', 'lvad-power-disconnected-by-learner'],
    predictionPrompt: 'Which competing low-flow diagnosis best fits the complete pattern?',
    predictionOptions: [
      { id: 'constrained-filling', label: 'Pericardial constraint limits biventricular filling' },
      { id: 'hypertension', label: 'Isolated systemic hypertension' },
      { id: 'thrombosis', label: 'Pump thrombosis with high power' },
    ],
    correctPredictionId: 'constrained-filling',
    requiredActionIds: [
      'inspect:preload',
      'inspect:device',
      'patient:set-tamponade',
      'team:escalate',
    ],
    successCriteria: [
      {
        metric: 'deviceFlowLMin',
        operator: 'at-least',
        value: 3,
        label: 'Modeled pump flow recovers',
      },
      { metric: 'mapMmHg', operator: 'at-least', value: 55, label: 'Perfusion pressure recovers' },
    ],
    guidedPrompt: '',
    debrief: [
      'Tamponade can present as LVAD low flow and requires urgent diagnosis and definitive care.',
      'Speed does not correct external filling constraint and can worsen inflow limitation.',
    ],
    sourceIds: lvadSources,
    evidenceSourceIds: lvadSources,
  },
] as const

export const allMcsScenarios = [...mcsPracticeScenarios, ...mcsCapstoneScenarios] as const
export const mcsScenarioById = new Map(allMcsScenarios.map((scenario) => [scenario.id, scenario]))
