/**
 * Annotated waveform atlas.
 *
 * Every trace here is generated by the same morphology functions the live simulator uses, so a
 * label that points at "the v wave" points at the sample the engine actually produces. Timings
 * and ranges follow Ragosta & Kennedy, Textbook of Clinical Hemodynamics ch. 2, and Whitener,
 * Konoske & Mark, Best Pract Res Clin Anaesthesiol 2014.
 */

import {
  CARDIAC_PHASE,
  NORMAL_RIGHT_ATRIAL_AMPLITUDES,
  NORMAL_WEDGE_AMPLITUDES,
  PULMONARY_ARTERY_SHAPE,
  SYSTEMIC_ARTERIAL_SHAPE,
  pulsatilePressureShape,
  rightAtrialDeviationMmHg,
  ventricularPressureShape,
  wedgeDeviationMmHg,
  type AtrialWaveAmplitudes,
  type PulsatileShapeOptions,
  type VentricularShapeOptions,
} from '../engine/waveformMorphology'

export type WaveformTraceSpec =
  | {
      readonly kind: 'atrial'
      readonly meanMmHg: number
      readonly amplitudes: AtrialWaveAmplitudes
      readonly landmarks: 'right-atrial' | 'wedge'
    }
  | {
      readonly kind: 'ventricular'
      readonly systolicMmHg: number
      readonly endDiastolicMmHg: number
      readonly shape: VentricularShapeOptions
    }
  | {
      readonly kind: 'pulsatile'
      readonly systolicMmHg: number
      readonly diastolicMmHg: number
      readonly shape: PulsatileShapeOptions
    }
  | {
      /** Over-wedged: a wavering line without distinct a and v waves that drifts upward. */
      readonly kind: 'overwedge'
      readonly baselineMmHg: number
    }
  | {
      /** Incomplete balloon occlusion: a mixture of pulmonary artery and wedge waveforms. */
      readonly kind: 'hybrid'
      readonly wedgeMeanMmHg: number
      readonly paSystolicMmHg: number
      readonly paDiastolicMmHg: number
      readonly contamination: number
    }

/** Pressure in mmHg at a given fraction of the cardiac cycle. */
export function waveformValueAt(spec: WaveformTraceSpec, phase: number): number {
  switch (spec.kind) {
    case 'atrial':
      return (
        spec.meanMmHg +
        (spec.landmarks === 'wedge'
          ? wedgeDeviationMmHg(phase, spec.amplitudes)
          : rightAtrialDeviationMmHg(phase, spec.amplitudes))
      )
    case 'ventricular': {
      const { endDiastolicFraction } = spec.shape
      const nadir =
        (spec.endDiastolicMmHg - spec.systolicMmHg * endDiastolicFraction) /
        (1 - endDiastolicFraction)
      return nadir + (spec.systolicMmHg - nadir) * ventricularPressureShape(phase, spec.shape)
    }
    case 'pulsatile':
      return (
        spec.diastolicMmHg +
        (spec.systolicMmHg - spec.diastolicMmHg) * pulsatilePressureShape(phase, spec.shape)
      )
    case 'overwedge':
      // No identifiable a or v waves — only a low-amplitude waver. Harmonics of the cycle keep
      // the line continuous across beats, because this artifact has no cardiac periodicity.
      return (
        spec.baselineMmHg +
        Math.sin(phase * Math.PI * 2) * 1.1 +
        Math.sin(phase * Math.PI * 6 + 1.1) * 0.55 +
        Math.sin(phase * Math.PI * 16 + 0.4) * 0.2
      )
    case 'hybrid': {
      const wedge = spec.wedgeMeanMmHg + wedgeDeviationMmHg(phase, NORMAL_WEDGE_AMPLITUDES)
      const pulmonaryArtery =
        spec.paDiastolicMmHg +
        (spec.paSystolicMmHg - spec.paDiastolicMmHg) *
          pulsatilePressureShape(phase, PULMONARY_ARTERY_SHAPE)
      return wedge * (1 - spec.contamination) + pulmonaryArtery * spec.contamination
    }
  }
}

export interface WaveformAnnotation {
  readonly id: string
  /** Short symbol drawn on the trace, such as a, c, v, x, or y. */
  readonly label: string
  readonly phase: number
  readonly placement: 'above' | 'below'
  readonly description: string
}

export type WaveformAtlasCategory = 'insertion' | 'abnormal' | 'artifact'

export interface WaveformAtlasEntry {
  readonly id: string
  readonly label: string
  readonly shortLabel: string
  readonly category: WaveformAtlasCategory
  /** Catheter position this trace belongs to, when it is part of the insertion sequence. */
  readonly position: 'ra' | 'rv' | 'pa' | 'wedge' | null
  readonly normalRange: string | null
  readonly insertionDepth: string | null
  readonly scaleMaxMmHg: number
  readonly summary: string
  readonly trace: WaveformTraceSpec
  readonly annotations: readonly WaveformAnnotation[]
  readonly recognitionCues: readonly string[]
  readonly pitfall: string | null
  readonly sourceIds: readonly string[]
}

const RA_ANNOTATIONS: readonly WaveformAnnotation[] = [
  {
    id: 'a',
    label: 'a',
    phase: CARDIAC_PHASE.atrialAWave,
    placement: 'above',
    description:
      'Atrial contraction. Follows the P wave on the ECG by about 80 ms. In a normal right atrium the a wave is taller than the v wave.',
  },
  {
    id: 'c',
    label: 'c',
    phase: CARDIAC_PHASE.atrialCWave,
    placement: 'above',
    description:
      'Tricuspid annulus moving toward the atrium at the onset of ventricular systole. Follows the QRS complex, and becomes more obvious when the PR interval is long.',
  },
  {
    id: 'x',
    label: 'x',
    phase: CARDIAC_PHASE.atrialXDescent,
    placement: 'below',
    description:
      'Atrial relaxation and downward movement of the atrioventricular junction during ventricular systole. Persists in atrial fibrillation even though the a wave is lost.',
  },
  {
    id: 'v',
    label: 'v',
    phase: CARDIAC_PHASE.atrialVWave,
    placement: 'above',
    description:
      'Passive venous filling of the atrium while the tricuspid valve is still closed — not ventricular systole itself. Peaks at the end of ventricular systole, at the end of the T wave.',
  },
  {
    id: 'y',
    label: 'y',
    phase: CARDIAC_PHASE.atrialYDescent,
    placement: 'below',
    description:
      'Rapid atrial emptying once the tricuspid valve opens. This is early ventricular diastole, and it accomplishes most of the filling that precedes the a wave.',
  },
]

const WEDGE_ANNOTATIONS: readonly WaveformAnnotation[] = [
  {
    id: 'a',
    label: 'a',
    phase: CARDIAC_PHASE.wedgeAWave,
    placement: 'above',
    description:
      'Left atrial contraction, transmitted backward through the pulmonary bed. It follows the P wave by about 240 ms rather than 80 ms, so it appears to follow the QRS complex. Its peak is the best single estimate of left ventricular end-diastolic pressure.',
  },
  {
    id: 'x',
    label: 'x',
    phase: CARDIAC_PHASE.wedgeXDescent,
    placement: 'below',
    description:
      'Left atrial relaxation. When a large v wave is present, the trough of this descent predicts left ventricular end-diastolic pressure better than the mean does.',
  },
  {
    id: 'v',
    label: 'v',
    phase: CARDIAC_PHASE.wedgeVWave,
    placement: 'above',
    description:
      'Passive pulmonary venous filling of the left atrium. On a wedge tracing the v wave normally exceeds the a wave — the reverse of the right atrium — and peaks after the T wave has already been inscribed.',
  },
  {
    id: 'y',
    label: 'y',
    phase: CARDIAC_PHASE.wedgeYDescent,
    placement: 'below',
    description: 'Rapid left atrial emptying after the mitral valve opens.',
  },
]

export const waveformAtlasEntries: readonly WaveformAtlasEntry[] = [
  {
    id: 'ra-normal',
    label: 'Right atrium / CVP',
    shortLabel: 'RA',
    category: 'insertion',
    position: 'ra',
    normalRange: 'Mean 2–6 mmHg',
    insertionDepth: '20–30 cm from the right internal jugular vein',
    scaleMaxMmHg: 20,
    summary:
      'A low-amplitude venous tracing with three positive waves and two descents. RA and CVP are the same pressure signal here: read at the base of the c wave during end expiration.',
    trace: {
      kind: 'atrial',
      meanMmHg: 4,
      amplitudes: NORMAL_RIGHT_ATRIAL_AMPLITUDES,
      landmarks: 'right-atrial',
    },
    annotations: RA_ANNOTATIONS,
    recognitionCues: [
      'Low amplitude: the whole tracing spans only a few mmHg.',
      'Three positive waves (a, c, v) and two descents (x, y).',
      'The a wave follows the P wave; the c wave follows the QRS complex.',
      'Right atrial pressure sits within a few mmHg of right ventricular end-diastolic pressure.',
      'With controlled positive-pressure ventilation, the slow CVP and arterial envelopes rise during inspiration; end expiration is the trough of that slow swing.',
      'Freeze the tracing, locate the end-expiratory trough, then read at the base of the c wave.',
    ],
    pitfall:
      'An inspiratory peak or a one-beat average taken at an arbitrary respiratory phase can overstate CVP. Level and zero first; wall contact can damp the trace and valve contact can add a misleading spike.',
    sourceIds: ['clinical-hemodynamics-waveforms', 'pac-review-2014', 'cvp-measurement-2017'],
  },
  {
    id: 'rv-normal',
    label: 'Right ventricle',
    shortLabel: 'RV',
    category: 'insertion',
    position: 'rv',
    normalRange: 'Systolic 15–30 mmHg, end-diastolic 0–8 mmHg',
    insertionDepth: '30–40 cm from the right internal jugular vein',
    scaleMaxMmHg: 40,
    summary:
      'The systolic pressure jumps. The identifying feature is not the peak but the diastole: it starts low and slopes upward as the ventricle fills.',
    trace: {
      kind: 'ventricular',
      systolicMmHg: 25,
      endDiastolicMmHg: 5,
      shape: { aWaveFraction: 0, endDiastolicFraction: 0.16 },
    },
    annotations: [
      {
        id: 'upstroke',
        label: 'rapid rise',
        phase: 0.11,
        placement: 'above',
        description: 'Rapid pressure rise during ventricular contraction.',
      },
      {
        id: 'peak',
        label: 'RVSP',
        phase: 0.16,
        placement: 'above',
        description:
          'Peak right ventricular systolic pressure, normally 15–30 mmHg and normally equal to pulmonary artery systolic pressure.',
      },
      {
        id: 'relaxation',
        label: 'rapid fall',
        phase: 0.48,
        placement: 'below',
        description: 'Rapid pressure decay during isovolumic relaxation.',
      },
      {
        id: 'diastole',
        label: 'up-sloping diastole',
        phase: 0.75,
        placement: 'below',
        description:
          'The diastolic phase begins at a low pressure and gradually increases as the ventricle fills. This up-sloping contour is the single most reliable way to tell an RV tracing from a PA tracing.',
      },
      {
        id: 'rvedp',
        label: 'RVEDP',
        phase: 0.985,
        placement: 'below',
        description:
          'Right ventricular end-diastolic pressure, best read at the time of the ECG R wave.',
      },
    ],
    recognitionCues: [
      'Large step up in systolic pressure compared with the right atrium.',
      'Diastole slopes UP — pressure rises through diastole as the ventricle fills.',
      'Low end-diastolic pressure, within a few mmHg of the right atrial mean.',
      'Ventricular ectopy is common while the tip is in the right ventricle.',
    ],
    pitfall:
      'A catheter left in the right ventricle will be mistaken for a pulmonary artery tracing if only the systolic number is read — the systolic pressures are nearly identical. Failing to recognize an RV position risks ventricular arrhythmia and perforation.',
    sourceIds: ['clinical-hemodynamics-waveforms', 'pac-review-2014'],
  },
  {
    id: 'pa-normal',
    label: 'Pulmonary artery',
    shortLabel: 'PA',
    category: 'insertion',
    position: 'pa',
    normalRange: 'Systolic 15–30 mmHg, diastolic 4–12 mmHg, mean 9–19 mmHg',
    insertionDepth: '40–50 cm from the right internal jugular vein',
    scaleMaxMmHg: 40,
    summary:
      'Systolic pressure is unchanged from the right ventricle. Two things announce the pulmonary artery: a diastolic step-up, and a dicrotic notch.',
    trace: {
      kind: 'pulsatile',
      systolicMmHg: 25,
      diastolicMmHg: 10,
      shape: PULMONARY_ARTERY_SHAPE,
    },
    annotations: [
      {
        id: 'peak',
        label: 'PASP',
        phase: CARDIAC_PHASE.pulmonaryArteryPeak,
        placement: 'above',
        description:
          'Peak systolic pressure, occurring at about the same time as the T wave. It should equal right ventricular systolic pressure; a difference implies pulmonic valvular or pulmonary artery stenosis.',
      },
      {
        id: 'notch',
        label: 'dicrotic notch',
        phase: CARDIAC_PHASE.pulmonicDicroticNotch + 0.015,
        placement: 'above',
        description:
          'Pulmonic valve closure. Its appearance confirms the catheter has crossed from the right ventricle into the pulmonary artery.',
      },
      {
        id: 'diastole',
        label: 'down-sloping diastole',
        phase: 0.75,
        placement: 'below',
        description:
          'Pressure continues to fall throughout diastole as blood runs off into the pulmonary bed — the opposite of the up-sloping right ventricular diastole.',
      },
      {
        id: 'padp',
        label: 'PADP',
        phase: 0.985,
        placement: 'below',
        description:
          'Pulmonary artery diastolic pressure. It sits 0–5 mmHg above the mean wedge pressure, and estimates left atrial pressure only when pulmonary vascular resistance is normal.',
      },
    ],
    recognitionCues: [
      'Diastolic STEP-UP compared with the right ventricle, with no change in systolic pressure.',
      'Diastole slopes DOWN throughout.',
      'A dicrotic notch appears on the downstroke.',
      'Marked respiratory swing may be present; read at end expiration.',
    ],
    pitfall:
      'Pulmonary artery diastolic pressure is often used to estimate left atrial pressure, but it is highly inaccurate whenever pulmonary vascular resistance is abnormal.',
    sourceIds: ['clinical-hemodynamics-waveforms', 'pac-review-2014', 'pac-derived-part-2-2021'],
  },
  {
    id: 'wedge-normal',
    label: 'Pulmonary capillary wedge',
    shortLabel: 'Normal wedge',
    category: 'insertion',
    position: 'wedge',
    normalRange: 'Mean 4–12 mmHg',
    insertionDepth: 'Balloon inflated at the pulmonary artery position, not advanced further',
    scaleMaxMmHg: 20,
    summary:
      'The tracing collapses back to an atrial morphology. It is left atrial pressure, read through the pulmonary bed, and it arrives late.',
    trace: {
      kind: 'atrial',
      meanMmHg: 9,
      amplitudes: NORMAL_WEDGE_AMPLITUDES,
      landmarks: 'wedge',
    },
    annotations: WEDGE_ANNOTATIONS,
    recognitionCues: [
      'Amplitude collapses back to a venous, atrial-looking tracing.',
      'No c wave — it does not survive transmission through the pulmonary bed.',
      'The v wave normally EXCEEDS the a wave, the reverse of the right atrium.',
      'Every wave arrives late relative to the ECG; the a wave follows the QRS rather than the P wave.',
      'Mean wedge pressure sits 0–5 mmHg below pulmonary artery diastolic pressure.',
    ],
    pitfall:
      'Confirm a true wedge before believing it: well-defined a and v waves, a wedged-tip saturation within about 5% of the simultaneous systemic arterial saturation (usually at least 95% when the patient is not hypoxemic), and an abrupt return to pulmonary-artery pressure and morphology when the balloon is deflated. In hypoxemia, use paired samples rather than an absolute saturation threshold; low arterial saturation makes oximetry less discriminating.',
    sourceIds: ['clinical-hemodynamics-waveforms', 'pac-review-2014'],
  },
  {
    id: 'wedge-large-v-wave',
    label: 'Large v wave',
    shortLabel: 'Large v',
    category: 'abnormal',
    position: 'wedge',
    normalRange: null,
    insertionDepth: null,
    scaleMaxMmHg: 45,
    summary:
      'A tall systolic c-v wave on the wedge tracing is the hallmark of severe mitral regurgitation, and is also produced by a poorly compliant left atrium or ventricle.',
    trace: {
      kind: 'atrial',
      meanMmHg: 22,
      amplitudes: {
        aWaveMmHg: 4,
        cWaveMmHg: 0,
        xDescentMmHg: 3.5,
        vWaveMmHg: 17,
        yDescentMmHg: 4,
      },
      landmarks: 'wedge',
    },
    annotations: [
      {
        id: 'v',
        label: 'giant v',
        phase: CARDIAC_PHASE.wedgeVWave,
        placement: 'above',
        description:
          'A v wave large enough to dominate the tracing. Because it is a systolic wave that arrives late, the tracing can be mistaken for a pulmonary artery waveform.',
      },
      {
        id: 'x',
        label: 'x',
        phase: CARDIAC_PHASE.wedgeXDescent,
        placement: 'below',
        description:
          'When large v waves are present, the trough of the x descent — not the mean — is the best predictor of left ventricular end-diastolic pressure.',
      },
    ],
    recognitionCues: [
      'A tall systolic wave dominates, and the mean wedge pressure is pulled up with it.',
      'The delay inherent in the wedge tracing makes the v wave appear later in diastole, which can be misread as a mitral gradient. Phase-shifting the wedge tracing to the left corrects this.',
      'Read left ventricular end-diastolic pressure from the x descent trough.',
    ],
    pitfall:
      'The mean wedge pressure overestimates left ventricular filling pressure when a large v wave is present.',
    sourceIds: ['clinical-hemodynamics-waveforms', 'pac-review-2014'],
  },
  {
    id: 'ra-tamponade',
    label: 'Pericardial constraint',
    shortLabel: 'Tamponade',
    category: 'abnormal',
    position: 'ra',
    normalRange: null,
    insertionDepth: null,
    scaleMaxMmHg: 30,
    summary:
      'Elevated right atrial pressure with a preserved x descent and an attenuated or absent y descent.',
    trace: {
      kind: 'atrial',
      meanMmHg: 18,
      amplitudes: {
        aWaveMmHg: 3,
        cWaveMmHg: 1.2,
        xDescentMmHg: 3.2,
        yDescentMmHg: 0.3,
        vWaveMmHg: 2.2,
      },
      landmarks: 'right-atrial',
    },
    annotations: [
      {
        id: 'x',
        label: 'x preserved',
        phase: CARDIAC_PHASE.atrialXDescent,
        placement: 'below',
        description:
          'Systolic atrial filling still occurs, so the x descent is preserved and often prominent.',
      },
      {
        id: 'y',
        label: 'y blunted',
        phase: CARDIAC_PHASE.atrialYDescent,
        placement: 'below',
        description:
          'Rapid early diastolic filling is exactly what the constrained pericardium prevents, so the y descent is attenuated or disappears. This is the finding that distinguishes tamponade.',
      },
    ],
    recognitionCues: [
      'Elevated mean right atrial pressure.',
      'Equalization of diastolic pressures across the cardiac chambers.',
      'Preserved x descent with a blunted or absent y descent.',
      'Low cardiac output and stroke volume; pulsus paradoxus may be present.',
    ],
    pitfall:
      'After cardiac surgery a localized hematoma can compress one chamber selectively, and the classical waveform pattern may not appear at all.',
    sourceIds: ['clinical-hemodynamics-waveforms', 'pac-derived-part-2-2021'],
  },
  {
    id: 'ra-tricuspid-regurgitation',
    label: 'Tricuspid regurgitation',
    shortLabel: 'TR',
    category: 'abnormal',
    position: 'ra',
    normalRange: null,
    insertionDepth: null,
    scaleMaxMmHg: 30,
    summary:
      'A tall systolic c-v wave that obliterates the x descent, giving the right atrial tracing a ventricularized appearance.',
    trace: {
      kind: 'atrial',
      meanMmHg: 14,
      amplitudes: {
        aWaveMmHg: 2,
        cWaveMmHg: 3.4,
        xDescentMmHg: 0.15,
        vWaveMmHg: 9,
        yDescentMmHg: 3.4,
      },
      landmarks: 'right-atrial',
    },
    annotations: [
      {
        id: 'cv',
        label: 'c-v',
        phase: CARDIAC_PHASE.atrialVWave - 0.06,
        placement: 'above',
        description:
          'Regurgitant flow into the lower-pressure atrium during systole fuses the c and v waves into one broad, tall systolic wave.',
      },
      {
        id: 'x',
        label: 'x lost',
        phase: CARDIAC_PHASE.atrialXDescent,
        placement: 'below',
        description:
          'The systolic regurgitant wave obliterates the x descent. Its absence is the diagnostic clue.',
      },
    ],
    recognitionCues: [
      'Broad, tall systolic wave that makes the atrial tracing look ventricular.',
      'The x descent is gone.',
      'Mean right atrial pressure is raised by the regurgitant wave, so it overestimates true right ventricular filling pressure.',
    ],
    pitfall:
      'Read right ventricular end-diastolic pressure from the phasic tracing at the ECG R wave rather than from the displayed mean. Significant tricuspid regurgitation also degrades thermodilution cardiac output, because cold injectate refluxes back into the atrium.',
    sourceIds: ['pac-review-2014', 'pac-derived-part-2-2021'],
  },
  {
    id: 'ra-cannon-a-wave',
    label: 'Cannon a waves',
    shortLabel: 'Cannon a',
    category: 'abnormal',
    position: 'ra',
    normalRange: null,
    insertionDepth: null,
    scaleMaxMmHg: 30,
    summary:
      'Atrial contraction against a closed tricuspid valve, producing intermittent tall, narrow a waves.',
    trace: {
      kind: 'atrial',
      meanMmHg: 8,
      amplitudes: {
        aWaveMmHg: 14,
        cWaveMmHg: 1,
        xDescentMmHg: 1.8,
        vWaveMmHg: 2,
        yDescentMmHg: 2,
      },
      landmarks: 'right-atrial',
    },
    annotations: [
      {
        id: 'a',
        label: 'cannon a',
        phase: CARDIAC_PHASE.atrialAWave,
        placement: 'above',
        description:
          'The atrium contracts while the tricuspid valve is closed, so pressure has nowhere to go but backward into the venous system.',
      },
    ],
    recognitionCues: [
      'Tall, narrow atrial waves that dwarf the rest of the tracing.',
      'Seen whenever atrioventricular dissociation is present — junctional rhythm, complete heart block, ventricular pacing.',
      'They appear at irregular intervals relative to the QRS, because they occur only when a dissociated atrial contraction happens to land against a closed valve.',
      'Cannon waves are larger when the atrium is poorly compliant.',
    ],
    pitfall:
      'A cannon wave is narrow and peaked; a v wave is broad and rounded. Confusing the two leads to a false diagnosis of tricuspid regurgitation. Cannon waves also inflate the mean right atrial pressure and can prompt unnecessary treatment of an apparently high filling pressure.',
    sourceIds: ['pac-review-2014', 'clinical-hemodynamics-waveforms'],
  },
  {
    id: 'ra-atrial-fibrillation',
    label: 'Atrial fibrillation',
    shortLabel: 'AF',
    category: 'abnormal',
    position: 'ra',
    normalRange: null,
    insertionDepth: null,
    scaleMaxMmHg: 20,
    summary:
      'Loss of the a wave with a prominent c wave. The x descent persists even though organized atrial contraction has been lost.',
    trace: {
      kind: 'atrial',
      meanMmHg: 6,
      amplitudes: {
        aWaveMmHg: 0,
        cWaveMmHg: 3.2,
        xDescentMmHg: 1.9,
        vWaveMmHg: 2.4,
        yDescentMmHg: 2.1,
      },
      landmarks: 'right-atrial',
    },
    annotations: [
      {
        id: 'a',
        label: 'no a wave',
        phase: CARDIAC_PHASE.atrialAWave,
        placement: 'above',
        description:
          'Without coordinated atrial contraction there is no a wave, matching the loss of the P wave on the ECG.',
      },
      {
        id: 'c',
        label: 'prominent c',
        phase: CARDIAC_PHASE.atrialCWave,
        placement: 'above',
        description:
          'Atrial volume and pressure are higher at end diastole without an atrial kick, exaggerating the c wave.',
      },
      {
        id: 'x',
        label: 'x persists',
        phase: CARDIAC_PHASE.atrialXDescent,
        placement: 'below',
        description:
          'The x descent survives, because part of it reflects descent of the atrioventricular junction during ventricular systole rather than atrial relaxation.',
      },
    ],
    recognitionCues: [
      'No a wave, and no P wave on the accompanying ECG.',
      'Prominent c wave.',
      'Irregular R-R intervals vary ventricular filling beat to beat, so systolic peaks vary too — a pattern that is easily misread as pulsus paradoxus.',
      'Because gradients vary with every beat, valve-area calculations in atrial fibrillation require averaging at least 10 consecutive beats.',
    ],
    pitfall:
      'A wedge tracing in atrial fibrillation also loses its a wave, so the usual "well-defined a and v waves" check for a true wedge cannot be applied.',
    sourceIds: ['clinical-hemodynamics-waveforms', 'pac-review-2014'],
  },
  {
    id: 'rv-prominent-a-wave',
    label: 'Non-compliant right ventricle',
    shortLabel: 'RV a wave',
    category: 'abnormal',
    position: 'rv',
    normalRange: null,
    insertionDepth: null,
    scaleMaxMmHg: 80,
    summary:
      'An a wave appearing on the right ventricular tracing at end diastole. This is not a normal finding.',
    trace: {
      kind: 'ventricular',
      systolicMmHg: 62,
      endDiastolicMmHg: 14,
      shape: { aWaveFraction: 0.14, endDiastolicFraction: 0.2 },
    },
    annotations: [
      {
        id: 'a',
        label: 'a',
        phase: CARDIAC_PHASE.atrialAWave,
        placement: 'above',
        description:
          'A compliant right ventricle absorbs atrial contraction without a significant pressure rise. An a wave here means the ventricle is stiff.',
      },
      {
        id: 'rvedp',
        label: 'RVEDP',
        phase: 0.99,
        placement: 'below',
        description:
          'End-diastolic pressure is measured just after the a wave and before the systolic upstroke.',
      },
    ],
    recognitionCues: [
      'An a wave is visible on a ventricular tracing at end diastole.',
      'Indicates decreased compliance: pulmonary hypertension, right ventricular hypertrophy, or volume overload.',
      'Systolic pressure is usually elevated as well.',
    ],
    pitfall:
      'When large a waves are present, end-diastolic pressure is the point just after the a wave, not the peak of it.',
    sourceIds: ['clinical-hemodynamics-waveforms'],
  },
  {
    id: 'wedge-overwedged',
    label: 'Over-wedged',
    shortLabel: 'Over-wedge',
    category: 'artifact',
    position: 'wedge',
    normalRange: null,
    insertionDepth: null,
    scaleMaxMmHg: 30,
    summary:
      'A false wedge produced by a catheter tip in a peripheral pulmonary artery with the balloon overinflated.',
    trace: { kind: 'overwedge', baselineMmHg: 12 },
    annotations: [
      {
        id: 'drift',
        label: 'no a or v waves',
        phase: 0.6,
        placement: 'above',
        description:
          'A wavering line with no identifiable wave components. It does not reflect left atrial pressure at all.',
      },
    ],
    recognitionCues: [
      'No identifiable a or v waves — the defining feature.',
      'The trace wavers and drifts upward over seconds rather than settling on a stable mean.',
      'The pressure is often higher than the pulmonary artery diastolic pressure, which is physiologically impossible for a true wedge.',
    ],
    pitfall:
      'This is a potentially fatal warning sign. Pulmonary-artery rupture associated with a balloon-tipped catheter has a reported mortality range of roughly 30–70%. Deflate immediately, stop manipulating or flushing the catheter, and reassess/reposition only under appropriate supervision.',
    sourceIds: ['clinical-hemodynamics-waveforms', 'pac-review-2014'],
  },
  {
    id: 'wedge-hybrid',
    label: 'Incomplete occlusion',
    shortLabel: 'Hybrid',
    category: 'artifact',
    position: 'wedge',
    normalRange: null,
    insertionDepth: null,
    scaleMaxMmHg: 45,
    summary:
      'A mixture of pulmonary artery and wedge waveforms, produced when the balloon does not completely occlude the vessel.',
    trace: {
      kind: 'hybrid',
      wedgeMeanMmHg: 12,
      paSystolicMmHg: 62,
      paDiastolicMmHg: 26,
      contamination: 0.42,
    },
    annotations: [
      {
        id: 'contamination',
        label: 'PA contamination',
        phase: CARDIAC_PHASE.pulmonaryArteryPeak,
        placement: 'above',
        description:
          'Residual pulmonary artery pulsatility rides on top of the wedge tracing and falsely elevates the mean.',
      },
    ],
    recognitionCues: [
      'Occurs particularly in pulmonary hypertension, where the catheter cannot fully occlude the artery.',
      'Hard to detect, because a and v waves may still be visible.',
      'The mean is higher than expected and does not fall by the usual amount from pulmonary artery diastolic pressure.',
      'Paired oximetry can help: a valid occlusion sample should approach the simultaneous systemic arterial saturation; persistent mixed-venous admixture supports incomplete occlusion.',
    ],
    pitfall:
      'This artifact falsely elevates the wedge and can misclassify pulmonary hypertension. Deflate immediately, return to a confirmed PA signal, and reassess catheter position and occlusion under appropriate supervision; do not advance or withdraw solely to chase a number.',
    sourceIds: ['clinical-hemodynamics-waveforms'],
  },
]

export const waveformAtlasById = new Map(waveformAtlasEntries.map((entry) => [entry.id, entry]))

export const insertionSequenceEntries = waveformAtlasEntries.filter(
  (entry) => entry.category === 'insertion',
)

export function waveformAtlasEntriesForPosition(
  position: WaveformAtlasEntry['position'],
): readonly WaveformAtlasEntry[] {
  return waveformAtlasEntries.filter((entry) => entry.position === position)
}

/** Systemic arterial reference trace, used to teach the dicrotic notch and damping artifacts. */
export const arterialReferenceTrace: WaveformTraceSpec = {
  kind: 'pulsatile',
  systolicMmHg: 120,
  diastolicMmHg: 70,
  shape: SYSTEMIC_ARTERIAL_SHAPE,
}
