import { createHash } from 'node:crypto'
import { readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'

// Role and exact-slot artifacts are intentionally regenerated by the reviewed remediation
// overlay. Product identity, source provenance, and unrelated calibrated artifacts remain
// byte-protected so a semantic migration cannot silently rewrite its evidence foundation.
//
// The product/provenance hashes move only with an explicitly reviewed catalog milestone. The
// The 2026-08-20 source-completeness intake extends the reviewed brochure milestone with exact
// owner/manufacturer-backed identities and provenance while preserving all release artifacts.
// Paying that friction deliberately, once per milestone, is the point of this guard.
const PROTECTED_FILE_HASHES = {
  'Preference_card_module/IP_Procedure_Equipment_Catalog_v0_5_with_GUDID_Verification_Backlog.xlsx':
    'fb25b24e4abb1a5225e76d0499f870f680c9cb07633491f1f63e63e2394b5abf',
  'data/ip-preference-cards/generated/catalog-products.json':
    'a5e548a1e36370bb13f7eea17d93dca698a965cbfae418931bd70bffa852f7cc',
  'data/ip-preference-cards/generated/product-sources.json':
    'ded695922f0125a4436cb3649e5aeaaff0f10fb36e6a470ac8a50f45ec1d6370',
  'data/ip-preference-cards/generated/sources.json':
    '1c0d7bafdafdb445aba9360b830bbc85a6ac877c0548709f12078cb504a691c4',
  'data/ip-preference-cards/generated/manufacturers.json':
    'd2221705577c98a697105eb48410d924c04455d76b848730042f75f4e37574ff',
  'data/ip-preference-cards/generated/verification-backlog.json':
    '25ab658850a5df620986d4596d5043f40e46d17132493dd62d7adaffc36c1b38',
  'data/ip-preference-cards/generated/hospital-formulary-staging.json':
    'f8ceb2433694f7ef1d5f65a6e4533fa6c2b1f83659d6ba017abda5fda4908e73',
  'data/ip-preference-cards/seed/openfda-calibration-cohort.json':
    '823969347c7cf85a1b13e10c76ebc9aad2cbcbfc1233b582c29d0670f73141d2',
  'docs/ip-preference-cards/openfda-live-calibration-report.md':
    '7c9a35944211351c63d4f95b28b3178059b4202f4ea545ed95f49982865abdea',
  'scripts/ip-preference-cards/openfda/manufacturer-aliases.ts':
    '6dff7acd53a5825330bfcc984832a3071c369621a6b80a4b88d42f03d28da902',
  'src/features/preference-cards/server/manufacturer-aliases.ts':
    'aad9ff0026583744dc77c71f58395dd48167c04a9c358b7549aa67cd80bfeddd',
  'scripts/ip-preference-cards/openfda/classify-match.ts':
    '863c3bf58f2a7e2fd9ca8b616fcf4a25dcc8526bbf5899024970b3c95a69ff7a',
  'scripts/ip-preference-cards/openfda/query-plan.ts':
    '7fe7af1615adc84ed39b2e12db042bdb3e63d61e01cf95ac808e69e6a6d71f84',
} as const

const OPENFDA_DIRECTORY = 'data/ip-preference-cards/generated/openfda'
const OPENFDA_FILE_COUNT = 48
const OPENFDA_MANIFEST_SHA256 = '4cc03adac07ad4f7e2d455559377017af9f2c9048240e3637ced4d46e9add61c'

function sha256(contents: Buffer | string): string {
  return createHash('sha256').update(contents).digest('hex')
}

function filesUnder(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const filename = path.join(directory, entry.name)
      return entry.isDirectory() ? filesUnder(filename) : [filename]
    })
    .sort()
}

describe('protected preference-card identifiers and provenance', () => {
  it.each(Object.entries(PROTECTED_FILE_HASHES))(
    'keeps %s byte-identical to its recorded baseline',
    (filename, expectedHash) => {
      expect(sha256(readFileSync(filename))).toBe(expectedHash)
    },
  )

  it('keeps the complete OpenFDA proposal, summary, and calibration artifact set unchanged', () => {
    const files = filesUnder(OPENFDA_DIRECTORY)
    const manifest = files
      .map((filename) => `${sha256(readFileSync(filename))}  ${filename}\n`)
      .join('')

    expect(files).toHaveLength(OPENFDA_FILE_COUNT)
    expect(sha256(manifest)).toBe(OPENFDA_MANIFEST_SHA256)
  })
})
