import type {
  HospitalItemType,
  ModifierAction,
  ModifierDefinition,
  OpenHoldStatus,
  ProceduralPhase,
  RecipeSlot,
  Requiredness,
  RescueModule,
  SetupZone,
  TypedCompatibilityRule,
  VerificationState,
} from '../domain/types'

/**
 * Modifier- and rescue-added lines sort after everything the composition produced, so a
 * contingency line never lands in the middle of the base setup. A composed requirement
 * takes either the procedure's own reviewed position or, when the procedure never placed
 * it, a module band above `UNPLACED_REQUIREMENT_SEQUENCE_BASE`; this base clears both.
 */
export const OPERATIONAL_SLOT_SEQUENCE_BASE = 100_000

export const DEMO_ORGANIZATION_ID = '00000000-0000-4000-8000-000000000101'
export const DEMO_SITE_ID = '00000000-0000-4000-8000-000000000102'
export const DEMO_LOCATION_ID = '00000000-0000-4000-8000-000000000103'

export interface DemoHospitalItemSeed {
  id: string
  roleCode: string
  itemType: HospitalItemType
  catalogProductId?: string
  localDescription: string
  localItemNumber?: string
  localUom?: string
  storageLocation?: string
  verificationState: VerificationState
  attributes?: Record<string, string | number | boolean | null>
  kitComponents?: {
    roleCode: string
    inclusion: 'included' | 'optional' | 'excluded'
    quantity: number
  }[]
  rationale: string
  preferenceRank?: number
  substitutionClass?:
    | 'preferred'
    | 'acceptable'
    | 'shortage_substitute'
    | 'backup'
    | 'emergency_only'
    | 'no_substitute'
}

function addedSlot(
  id: string,
  roleCode: string,
  label: string,
  genericRequirement: string,
  requiredness: Requiredness,
  setupZone: SetupZone,
  proceduralPhase: ProceduralPhase,
  openHoldStatus: OpenHoldStatus,
  sequence: number,
  dependencyRule: string | null = null,
): RecipeSlot {
  return {
    id,
    sourceSlotId: null,
    // Operationally authored lines are their own requirement. Keying them by their own id
    // makes them unique by construction, so nothing here can accidentally merge with a
    // module-authored requirement that happens to share a role code.
    requirementKey: id,
    roleCode,
    label,
    genericRequirement,
    requiredness,
    dependencyRule,
    quantityExpression: { op: 'literal', value: 1 },
    selectionMode: 'single',
    setupZone,
    proceduralPhase,
    setupSequence: OPERATIONAL_SLOT_SEQUENCE_BASE + sequence,
    openHoldStatus,
    responsibleRole: null,
    sterileStatus: null,
    allowCustom: true,
    notes: null,
    includedBy: 'Operational seed',
  }
}

function action(
  modifierCode: string,
  sequence: number,
  actionType: ModifierAction['actionType'],
  options: {
    targetSlotId?: string
    targetRoleCode?: string
    payload?: Record<string, unknown>
  } = {},
): ModifierAction {
  return {
    id: `${modifierCode.toLowerCase()}-${sequence}`,
    modifierCode,
    sequence,
    actionType,
    ...(options.targetSlotId ? { targetSlotId: options.targetSlotId } : {}),
    ...(options.targetRoleCode ? { targetRoleCode: options.targetRoleCode } : {}),
    payload: options.payload ?? {},
  }
}

function addSlotAction(modifierCode: string, sequence: number, slot: RecipeSlot): ModifierAction {
  return action(modifierCode, sequence, 'add_slot', { payload: { slot } })
}

export const demoHospitalItemSeeds: DemoHospitalItemSeed[] = [
  {
    id: 'catalog-ebus-scope',
    roleCode: 'EBUS_SCOPE',
    itemType: 'commercial_product',
    catalogProductId: 'PRD-2FFEEB98B2',
    localDescription: 'Demo BF-UC190F linear EBUS bronchoscope',
    localItemNumber: 'DEMO-EBUS-001',
    storageLocation: 'Demo EBUS tower',
    verificationState: 'prototype_visible',
    rationale: 'Explicit prototype-visible catalog mapping for the EBUS golden scenario.',
  },
  {
    id: 'demo-video-stack',
    roleCode: 'VIDEO_PROCESSOR',
    itemType: 'capital_asset',
    localDescription: 'Demo video processor and light-source stack for the active scope platform',
    localItemNumber: 'DEMO-VIDEO-001',
    storageLocation: 'Demo equipment tower',
    verificationState: 'demo_only',
    rationale: 'No reviewed hospital-local processor/platform mapping was supplied.',
  },
  {
    id: 'catalog-ebus-ultrasound',
    roleCode: 'ULTRASOUND_PROCESSOR',
    itemType: 'capital_asset',
    catalogProductId: 'PRD-E04326B8E4',
    localDescription: 'Demo EU-ME2 endoscopic ultrasound center',
    localItemNumber: 'DEMO-US-001',
    storageLocation: 'Demo EBUS tower',
    verificationState: 'prototype_visible',
    rationale: 'Explicit prototype-visible catalog mapping for the EBUS golden scenario.',
  },
  {
    id: 'catalog-ebus-cable',
    roleCode: 'ULTRASOUND_CABLE',
    itemType: 'reusable_instrument',
    catalogProductId: 'PRD-B3B30BCEE7',
    localDescription: 'Demo MAJ-2056 ultrasound cable',
    localItemNumber: 'DEMO-US-CBL-001',
    storageLocation: 'Demo EBUS tower drawer',
    verificationState: 'prototype_visible',
    rationale: 'Explicit prototype-visible catalog mapping for the EBUS golden scenario.',
  },
  {
    id: 'catalog-ebus-needle',
    roleCode: 'EBUS_NEEDLE_FNA',
    itemType: 'commercial_product',
    catalogProductId: 'PRD-2302DA77DA',
    localDescription: 'Demo Expect Pulmonary EBUS-TBNA needle',
    localItemNumber: 'DEMO-EBUS-NDL-001',
    localUom: 'Each',
    storageLocation: 'Demo sampling cabinet',
    verificationState: 'prototype_visible',
    rationale: 'Explicit prototype-visible catalog mapping; no clinical needle-size claim is made.',
  },
  {
    id: 'demo-specimen-bundle',
    roleCode: 'GENERIC_SPECIMEN',
    itemType: 'specimen_or_laboratory_requirement',
    localDescription: 'Demo specimen-labeling and transport bundle',
    localItemNumber: 'DEMO-SPEC-001',
    storageLocation: 'Demo specimen station',
    verificationState: 'demo_only',
    rationale: 'Hospital-local specimen workflow placeholder.',
  },
  {
    id: 'demo-suction',
    roleCode: 'GENERIC_SUCTION',
    itemType: 'room_resource',
    localDescription: 'Demo wall suction setup',
    localItemNumber: 'DEMO-SUCT-001',
    storageLocation: 'Procedure room wall',
    verificationState: 'demo_only',
    rationale: 'Hospital-local room resource placeholder.',
  },
  {
    id: 'demo-rose-station',
    roleCode: 'LOCAL_ROSE_STATION',
    itemType: 'personnel_or_service',
    localDescription: 'Demo cytology/ROSE station and personnel readiness',
    localItemNumber: 'DEMO-ROSE-001',
    storageLocation: 'Demo specimen station',
    verificationState: 'demo_only',
    rationale: 'Local cytology service workflow was not supplied.',
  },
  {
    id: 'demo-cytology-supplies',
    roleCode: 'LOCAL_CYTOLOGY_SUPPLIES',
    itemType: 'specimen_or_laboratory_requirement',
    localDescription: 'Demo slides, fixatives, labels, and cell-block supplies',
    localItemNumber: 'DEMO-CYTO-001',
    storageLocation: 'Demo specimen station',
    verificationState: 'demo_only',
    rationale: 'Local cytology supply workflow was not supplied.',
  },
  {
    id: 'demo-molecular-specimen',
    roleCode: 'LOCAL_MOLECULAR_SPECIMEN_BUNDLE',
    itemType: 'specimen_or_laboratory_requirement',
    localDescription: 'Demo molecular-testing specimen preservation and transport bundle',
    localItemNumber: 'DEMO-NGS-001',
    storageLocation: 'Demo specimen station',
    verificationState: 'demo_only',
    rationale: 'Local molecular-testing workflow was not supplied.',
  },
  {
    id: 'demo-molecular-readiness',
    roleCode: 'LOCAL_MOLECULAR_READINESS',
    itemType: 'protocol_or_readiness_check',
    localDescription: 'Demo pathology adequacy and molecular-testing readiness check',
    localItemNumber: 'DEMO-NGS-CHECK-001',
    verificationState: 'demo_only',
    rationale: 'Local pathology readiness requirements were not supplied.',
  },
  {
    id: 'catalog-therapeutic-scope',
    roleCode: 'FLEX_SCOPE_THERAPEUTIC',
    itemType: 'commercial_product',
    catalogProductId: 'PRD-F60C3305B4',
    localDescription: 'Demo aScope 5 Broncho HD 5.6/2.8 therapeutic bronchoscope',
    localItemNumber: 'DEMO-SCOPE-THER-001',
    storageLocation: 'Demo equipment tower',
    verificationState: 'prototype_visible',
    rationale: 'Explicit prototype-visible catalog mapping for the therapeutic scenario.',
  },
  {
    id: 'catalog-rigid-head',
    roleCode: 'RIGID_BRONCHOSCOPE_HEAD',
    itemType: 'reusable_instrument',
    catalogProductId: 'PRD-5E4F566AA2',
    localDescription: 'Demo DUTAU bronchoscope head',
    localItemNumber: 'DEMO-RIGID-HEAD-001',
    storageLocation: 'Demo rigid tray',
    verificationState: 'prototype_visible',
    rationale: 'Explicit prototype-visible mapping for layout demonstration.',
  },
  {
    id: 'catalog-rigid-barrel',
    roleCode: 'RIGID_BRONCHOSCOPE_BARREL',
    itemType: 'reusable_instrument',
    catalogProductId: 'PRD-9EB174FBB0',
    localDescription: 'Demo rigid tracheoscope barrel fixture',
    localItemNumber: 'DEMO-RIGID-BARREL-001',
    storageLocation: 'Demo rigid tray',
    verificationState: 'prototype_visible',
    rationale: 'Prototype fixture only; it is not clinical size guidance.',
  },
  {
    id: 'catalog-rigid-accessory',
    roleCode: 'RIGID_BRONCHOSCOPE_ACCESSORY',
    itemType: 'reusable_instrument',
    catalogProductId: 'PRD-042B406005',
    localDescription: 'Demo rigid bronchoscope accessory fixture',
    localItemNumber: 'DEMO-RIGID-ACC-001',
    storageLocation: 'Demo rigid tray',
    verificationState: 'prototype_visible',
    rationale: 'Prototype fixture only; full system compatibility remains unverified.',
  },
  {
    id: 'catalog-rigid-forceps',
    roleCode: 'RIGID_FORCEPS',
    itemType: 'reusable_instrument',
    catalogProductId: 'PRD-1894515971',
    localDescription: 'Demo rigid forceps handle fixture',
    localItemNumber: 'DEMO-RIGID-FORCEPS-001',
    storageLocation: 'Demo rigid tray',
    verificationState: 'prototype_visible',
    rationale:
      'Prototype fixture only; a complete matched shaft/head set remains a local decision.',
  },
  {
    id: 'catalog-rigid-suction',
    roleCode: 'RIGID_SUCTION_CATHETER',
    itemType: 'reusable_instrument',
    catalogProductId: 'PRD-07EA3DD76E',
    localDescription: 'Demo rigid suction catheter fixture',
    localItemNumber: 'DEMO-RIGID-SUCT-001',
    storageLocation: 'Demo rigid tray',
    verificationState: 'prototype_visible',
    rationale: 'Explicit prototype-visible mapping for layout demonstration.',
  },
  {
    id: 'demo-rigid-telescope',
    roleCode: 'RIGID_TELESCOPE',
    itemType: 'reusable_instrument',
    localDescription: 'Demo stand-in — rigid telescope',
    localItemNumber: 'DEMO-RIGID-TEL-001',
    storageLocation: 'Demo rigid tray',
    verificationState: 'demo_only',
    rationale: 'All catalog options are hidden.',
  },
  {
    id: 'demo-light-cable',
    roleCode: 'ENDOSCOPY_LIGHT_CABLE',
    itemType: 'reusable_instrument',
    localDescription: 'Demo stand-in — endoscopy light cable',
    localItemNumber: 'DEMO-LIGHT-001',
    storageLocation: 'Demo equipment tower',
    verificationState: 'demo_only',
    rationale: 'All catalog options are hidden.',
  },
  {
    id: 'demo-apc-platform',
    roleCode: 'ENERGY_PLATFORM',
    itemType: 'capital_asset',
    localDescription: 'Demo stand-in — APC energy platform',
    localItemNumber: 'DEMO-APC-PLATFORM-001',
    storageLocation: 'Demo equipment tower',
    verificationState: 'demo_only',
    attributes: { system_family: 'platform-family-a' },
    rationale: 'No approved local APC platform mapping was supplied.',
  },
  {
    id: 'demo-apc-probe-incompatible',
    roleCode: 'APC_PROBE_FLEX',
    itemType: 'hospital_local_disposable',
    localDescription: 'Demo stand-in — intentionally incompatible flexible APC probe fixture',
    localItemNumber: 'DEMO-APC-PROBE-FAIL',
    storageLocation: 'Demo energy cabinet',
    verificationState: 'demo_only',
    attributes: { system_family: 'platform-family-b' },
    rationale: 'Deliberately incompatible test fixture; all catalog options are hidden.',
  },
  {
    id: 'demo-apc-applicator-rigid',
    roleCode: 'APC_APPLICATOR_RIGID',
    itemType: 'reusable_instrument',
    localDescription: 'Demo stand-in — rigid APC applicator',
    localItemNumber: 'DEMO-APC-RIGID-001',
    storageLocation: 'Demo energy cabinet',
    verificationState: 'demo_only',
    rationale: 'All catalog options are hidden.',
  },
  {
    id: 'demo-apc-gas',
    roleCode: 'APC_GAS_ACCESSORY',
    itemType: 'room_resource',
    localDescription: 'Demo stand-in — APC gas supply and accessory set',
    localItemNumber: 'DEMO-APC-GAS-001',
    storageLocation: 'Demo procedure room',
    verificationState: 'demo_only',
    rationale: 'All catalog options are hidden.',
  },
  {
    id: 'demo-energy-cable',
    roleCode: 'ENERGY_CABLE_ADAPTER',
    itemType: 'reusable_instrument',
    localDescription: 'Demo stand-in — energy cable and adapter',
    localItemNumber: 'DEMO-ENERGY-CBL-001',
    storageLocation: 'Demo energy cabinet',
    verificationState: 'demo_only',
    rationale: 'All catalog options are hidden.',
  },
  {
    id: 'demo-fire-readiness',
    roleCode: 'LOCAL_AIRWAY_FIRE_READINESS',
    itemType: 'protocol_or_readiness_check',
    localDescription: 'Demo airway-fire readiness line',
    localItemNumber: 'DEMO-FIRE-CHECK-001',
    verificationState: 'demo_only',
    rationale: 'Local fire-risk readiness policy was not supplied.',
  },
  {
    id: 'catalog-airway-balloon',
    roleCode: 'AIRWAY_BALLOON_DILATOR',
    itemType: 'commercial_product',
    catalogProductId: 'PRD-94E33ED243',
    localDescription: 'Demo CRE pulmonary balloon dilatation catheter fixture',
    localItemNumber: 'DEMO-BALLOON-001',
    storageLocation: 'Demo dilation cabinet',
    verificationState: 'prototype_visible',
    rationale: 'Prototype fixture only; no clinical size recommendation is made.',
  },
  {
    id: 'catalog-guidewire',
    roleCode: 'PULMONARY_GUIDEWIRE',
    itemType: 'commercial_product',
    catalogProductId: 'PRD-602AA2F147',
    localDescription: 'Demo pulmonary guidewire fixture',
    localItemNumber: 'DEMO-WIRE-001',
    storageLocation: 'Demo dilation cabinet',
    verificationState: 'prototype_visible',
    rationale: 'Prototype fixture only; compatibility requires current IFU review.',
  },
  {
    id: 'catalog-inflation-device',
    roleCode: 'INFLATION_DEVICE',
    itemType: 'commercial_product',
    catalogProductId: 'PRD-8A08163BA1',
    localDescription: 'Demo inflation-device fixture',
    localItemNumber: 'DEMO-INFLATE-001',
    storageLocation: 'Demo dilation cabinet',
    verificationState: 'prototype_visible',
    rationale: 'Prototype fixture only; compatibility requires current IFU review.',
  },
  {
    id: 'demo-airway-measurement',
    roleCode: 'LOCAL_AIRWAY_MEASUREMENT',
    itemType: 'protocol_or_readiness_check',
    localDescription: 'Demo airway measurement readiness line — no sizing recommendation',
    localItemNumber: 'DEMO-MEASURE-001',
    verificationState: 'demo_only',
    rationale: 'The prototype does not supply clinical sizing guidance.',
  },
  {
    id: 'demo-airway-stent',
    roleCode: 'AIRWAY_STENT_CONFIGURATION',
    itemType: 'hospital_local_disposable',
    localDescription: 'Demo stand-in — airway stent configuration (no clinical size selected)',
    localItemNumber: 'DEMO-STENT-001',
    storageLocation: 'Demo stent cabinet',
    verificationState: 'demo_only',
    rationale: 'No locally reviewed configuration or clinical size was supplied.',
  },
  {
    id: 'catalog-stent-sizer',
    roleCode: 'AIRWAY_STENT_SIZING_DEVICE',
    itemType: 'commercial_product',
    catalogProductId: 'PRD-513E7E5BCD',
    localDescription: 'Demo airway stent sizing-device fixture',
    localItemNumber: 'DEMO-STENT-SIZER-001',
    storageLocation: 'Demo stent cabinet',
    verificationState: 'prototype_visible',
    rationale: 'Prototype fixture only; no clinical size recommendation is made.',
  },
  {
    id: 'demo-stent-deployment',
    roleCode: 'STENT_DEPLOYMENT_TOOLS',
    itemType: 'instrument_tray',
    localDescription: 'Demo stent deployment/loading and measurement tool set',
    localItemNumber: 'DEMO-STENT-TOOLS-001',
    storageLocation: 'Demo stent cabinet',
    verificationState: 'demo_only',
    rationale: 'No reviewed local stent-system mapping was supplied.',
  },
  {
    id: 'demo-jet-ventilator',
    roleCode: 'JET_VENTILATOR',
    itemType: 'capital_asset',
    localDescription: 'Demo jet ventilator resource',
    localItemNumber: 'DEMO-JET-001',
    storageLocation: 'Demo procedure room',
    verificationState: 'demo_only',
    rationale: 'No reviewed local jet-ventilator mapping was supplied.',
  },
  {
    id: 'demo-jet-accessories',
    roleCode: 'JET_VENT_ACCESSORY',
    itemType: 'room_resource',
    localDescription: 'Demo jet-ventilation tubing, connector, and pressure-source set',
    localItemNumber: 'DEMO-JET-ACC-001',
    storageLocation: 'Demo procedure room',
    verificationState: 'demo_only',
    rationale: 'No reviewed local jet-ventilation accessory mapping was supplied.',
  },
  {
    id: 'demo-manual-ventilation',
    roleCode: 'MANUAL_VENTILATION_BACKUP',
    itemType: 'room_resource',
    localDescription: 'Demo manual-ventilation backup setup',
    localItemNumber: 'DEMO-VENT-BACKUP-001',
    storageLocation: 'Demo airway cart',
    verificationState: 'demo_only',
    rationale: 'Local anesthesia/ventilation equipment mapping was not supplied.',
  },
  {
    id: 'demo-c-arm',
    roleCode: 'C_ARM_RESOURCE',
    itemType: 'room_resource',
    localDescription: 'Demo C-arm resource',
    localItemNumber: 'DEMO-CARM-001',
    storageLocation: 'Demo imaging pool',
    verificationState: 'demo_only',
    rationale: 'Local imaging resource mapping was not supplied.',
  },
  {
    id: 'demo-c-arm-drape',
    roleCode: 'C_ARM_STERILE_DRAPE',
    itemType: 'hospital_local_disposable',
    localDescription: 'Demo C-arm sterile drape',
    localItemNumber: 'DEMO-CARM-DRAPE-001',
    storageLocation: 'Demo imaging cabinet',
    verificationState: 'demo_only',
    rationale: 'Local sterile-drape mapping was not supplied.',
  },
  {
    id: 'demo-radiation-safety',
    roleCode: 'RADIATION_SAFETY_BUNDLE',
    itemType: 'protocol_or_readiness_check',
    localDescription: 'Demo radiation-safety bundle and readiness line',
    localItemNumber: 'DEMO-RAD-001',
    storageLocation: 'Demo imaging pool',
    verificationState: 'demo_only',
    rationale: 'Local radiation-safety workflow was not supplied.',
  },
  {
    id: 'catalog-chest-tube-kit',
    roleCode: 'CHEST_TUBE_SMALL_BORE',
    itemType: 'procedure_kit',
    catalogProductId: 'PRD-B1E837841F',
    localDescription: 'Demo ReSolve thoracostomy tray',
    localItemNumber: 'DEMO-CT-SMALL-001',
    storageLocation: 'Demo pleural cabinet',
    verificationState: 'prototype_visible',
    kitComponents: [
      {
        roleCode: 'LOCAL_CHEST_TUBE_SECUREMENT',
        inclusion: 'included',
        quantity: 1,
      },
    ],
    rationale: 'Explicit prototype fixture with one reviewed demo BOM component.',
  },
  {
    id: 'demo-large-bore-tube',
    roleCode: 'CHEST_TUBE_LARGE_BORE',
    itemType: 'procedure_kit',
    localDescription: 'Demo stand-in — large-bore chest tube set',
    localItemNumber: 'DEMO-CT-LARGE-001',
    storageLocation: 'Demo pleural cabinet',
    verificationState: 'demo_only',
    rationale: 'All catalog options are hidden.',
  },
  {
    id: 'demo-drainage-unit',
    roleCode: 'GENERIC_DRAINAGE_UNIT',
    itemType: 'room_resource',
    localDescription: 'Demo conventional chest drainage unit',
    localItemNumber: 'DEMO-DRAIN-001',
    storageLocation: 'Demo pleural cabinet',
    verificationState: 'demo_only',
    rationale: 'Hospital-local drainage resource placeholder.',
  },
  {
    id: 'demo-digital-drainage',
    roleCode: 'DIGITAL_DRAINAGE_SYSTEM',
    itemType: 'capital_asset',
    localDescription: 'Demo digital pleural drainage system and disposable set',
    localItemNumber: 'DEMO-DIGITAL-DRAIN-001',
    storageLocation: 'Demo pleural equipment pool',
    verificationState: 'demo_only',
    rationale: 'No reviewed local digital-drainage mapping was supplied.',
  },
  {
    id: 'demo-chest-securement',
    roleCode: 'LOCAL_CHEST_TUBE_SECUREMENT',
    itemType: 'hospital_local_disposable',
    localDescription: 'Demo chest-tube securement and dressing pack',
    localItemNumber: 'DEMO-CT-SECURE-001',
    storageLocation: 'Demo pleural cabinet',
    verificationState: 'demo_only',
    rationale: 'Used to prove kit/BOM duplicate suppression.',
  },
  {
    id: 'demo-second-suction',
    roleCode: 'HIGH_CAPACITY_SUCTION_BACKUP',
    itemType: 'room_resource',
    localDescription: 'Demo second high-capacity suction setup',
    localItemNumber: 'DEMO-SUCT-002',
    storageLocation: 'Demo emergency cart',
    verificationState: 'demo_only',
    rationale: 'Local rescue-resource mapping was not supplied.',
    substitutionClass: 'emergency_only',
  },
  {
    id: 'demo-tamponade-balloon',
    roleCode: 'AIRWAY_TAMPONADE_BALLOON_CAPABILITY',
    itemType: 'room_resource',
    localDescription: 'Demo blocker/tamponade balloon capability',
    localItemNumber: 'DEMO-BLOCKER-001',
    storageLocation: 'Demo emergency cart',
    verificationState: 'demo_only',
    rationale: 'Local rescue-resource mapping was not supplied.',
    substitutionClass: 'emergency_only',
  },
  {
    id: 'demo-rigid-backup',
    roleCode: 'RIGID_BRONCHOSCOPY_BACKUP',
    itemType: 'instrument_tray',
    localDescription: 'Demo rigid bronchoscopy backup tray readiness',
    localItemNumber: 'DEMO-RIGID-BACKUP-001',
    storageLocation: 'Demo emergency cart',
    verificationState: 'demo_only',
    rationale: 'Local rescue-resource mapping was not supplied.',
    substitutionClass: 'emergency_only',
  },
]

const roseSlots = [
  addedSlot(
    'OPS-ROSE-STATION',
    'LOCAL_ROSE_STATION',
    'ROSE station and personnel readiness',
    'Local cytology personnel, microscope or telecytology resource, and communication path.',
    'required',
    'specimen_station',
    'pre_room',
    'have_in_room',
    201,
  ),
  addedSlot(
    'OPS-ROSE-SUPPLIES',
    'LOCAL_CYTOLOGY_SUPPLIES',
    'ROSE slides, fixatives, and cell-block supplies',
    'Local cytology supplies and labeling workflow.',
    'required',
    'specimen_station',
    'specimen_handling',
    'open_or_set_up_now',
    202,
  ),
]

const molecularSlots = [
  addedSlot(
    'OPS-MOLECULAR-SPECIMEN',
    'LOCAL_MOLECULAR_SPECIMEN_BUNDLE',
    'Molecular-testing specimen bundle',
    'Local preservation, container, labeling, and transport requirements for molecular testing.',
    'required',
    'specimen_station',
    'specimen_handling',
    'open_or_set_up_now',
    211,
  ),
  addedSlot(
    'OPS-MOLECULAR-READINESS',
    'LOCAL_MOLECULAR_READINESS',
    'Molecular-testing readiness check',
    'Confirm the locally governed pathology adequacy and transport workflow.',
    'required',
    'specimen_station',
    'pre_room',
    'have_in_room',
    212,
  ),
]

const rigidSlots = [
  addedSlot(
    'OPS-RIGID-HEAD',
    'RIGID_BRONCHOSCOPE_HEAD',
    'Rigid bronchoscope head/base',
    'Hospital-local rigid bronchoscope system head or base.',
    'required',
    'equipment_tower',
    'airway_access',
    'open_or_set_up_now',
    301,
  ),
  addedSlot(
    'OPS-RIGID-BARREL',
    'RIGID_BRONCHOSCOPE_BARREL',
    'Rigid tracheoscope/bronchoscope barrel fixture',
    'A locally reviewed rigid barrel configuration; no size is recommended by this module.',
    'required',
    'mayo_stand',
    'airway_access',
    'open_or_set_up_now',
    302,
  ),
  addedSlot(
    'OPS-RIGID-ACCESSORY',
    'RIGID_BRONCHOSCOPE_ACCESSORY',
    'Rigid ventilation elements, ports, and caps',
    'Matched accessories for the local rigid system.',
    'required',
    'mayo_stand',
    'airway_access',
    'open_or_set_up_now',
    303,
  ),
  addedSlot(
    'OPS-RIGID-TELESCOPE',
    'RIGID_TELESCOPE',
    'Rigid telescope',
    'Locally reviewed rigid visualization telescope.',
    'required',
    'mayo_stand',
    'airway_access',
    'open_or_set_up_now',
    304,
  ),
  addedSlot(
    'OPS-RIGID-LIGHT-CABLE',
    'ENDOSCOPY_LIGHT_CABLE',
    'Fiber-optic light cable',
    'Locally compatible light cable.',
    'required',
    'equipment_tower',
    'pre_room',
    'have_in_room',
    305,
  ),
  addedSlot(
    'OPS-RIGID-FORCEPS',
    'RIGID_FORCEPS',
    'Rigid forceps set',
    'Matched rigid handle, shaft, and head set.',
    'required',
    'mayo_stand',
    'therapeutic',
    'open_or_set_up_now',
    306,
  ),
  addedSlot(
    'OPS-RIGID-SUCTION',
    'RIGID_SUCTION_CATHETER',
    'Rigid suction catheter',
    'Locally reviewed rigid suction catheter.',
    'required',
    'mayo_stand',
    'therapeutic',
    'open_or_set_up_now',
    307,
  ),
]

const apcSlots = [
  addedSlot(
    'OPS-APC-PLATFORM',
    'ENERGY_PLATFORM',
    'APC energy platform',
    'Locally approved APC generator/platform.',
    'required',
    'equipment_tower',
    'pre_room',
    'have_in_room',
    321,
  ),
  addedSlot(
    'OPS-APC-PROBE',
    'APC_PROBE_FLEX',
    'Flexible APC probe',
    'Probe compatible with the selected platform and working channel.',
    'required',
    'mayo_stand',
    'therapeutic',
    'hold_unopened',
    322,
  ),
  addedSlot(
    'OPS-APC-RIGID',
    'APC_APPLICATOR_RIGID',
    'Rigid APC applicator',
    'Applicator compatible with the selected platform and rigid system.',
    'required',
    'mayo_stand',
    'therapeutic',
    'hold_unopened',
    323,
  ),
  addedSlot(
    'OPS-APC-GAS',
    'APC_GAS_ACCESSORY',
    'APC gas supply and accessories',
    'Locally governed gas source and connections.',
    'required',
    'equipment_tower',
    'pre_room',
    'have_in_room',
    324,
  ),
  addedSlot(
    'OPS-APC-CABLE',
    'ENERGY_CABLE_ADAPTER',
    'APC cable or adapter',
    'Matched cable or adapter for the selected platform and applicator.',
    'required',
    'equipment_tower',
    'pre_room',
    'have_in_room',
    325,
  ),
  addedSlot(
    'OPS-APC-FIRE',
    'LOCAL_AIRWAY_FIRE_READINESS',
    'Airway-fire readiness line',
    'Local airway-fire risk readiness and equipment check.',
    'required',
    'room_capital_equipment',
    'pre_room',
    'have_in_room',
    326,
  ),
]

const jetSlots = [
  addedSlot(
    'OPS-JET-VENTILATOR',
    'JET_VENTILATOR',
    'Jet ventilator',
    'Locally approved jet-ventilation capital asset.',
    'required',
    'room_capital_equipment',
    'pre_room',
    'have_in_room',
    341,
  ),
  addedSlot(
    'OPS-JET-ACCESSORY',
    'JET_VENT_ACCESSORY',
    'Jet-ventilation tubing and connector set',
    'Locally matched jet-ventilation accessories and pressure source.',
    'required',
    'equipment_tower',
    'airway_access',
    'have_in_room',
    342,
  ),
  addedSlot(
    'OPS-MANUAL-VENT',
    'MANUAL_VENTILATION_BACKUP',
    'Manual-ventilation backup',
    'Local manual-ventilation backup setup.',
    'required',
    'emergency_cart',
    'rescue_or_contingency',
    'emergency_pull',
    343,
  ),
]

const fluoroscopySlots = [
  addedSlot(
    'OPS-CARM',
    'C_ARM_RESOURCE',
    'C-arm resource',
    'Booked and ready C-arm resource.',
    'required',
    'room_capital_equipment',
    'pre_room',
    'have_in_room',
    351,
  ),
  addedSlot(
    'OPS-CARM-DRAPE',
    'C_ARM_STERILE_DRAPE',
    'C-arm sterile drape',
    'Locally compatible sterile C-arm drape.',
    'required',
    'sterile_field',
    'pre_induction_or_sedation',
    'hold_unopened',
    352,
  ),
  addedSlot(
    'OPS-RADIATION',
    'RADIATION_SAFETY_BUNDLE',
    'Radiation-safety resources',
    'Local radiation PPE, signage, dosimetry, and readiness workflow.',
    'required',
    'room_capital_equipment',
    'pre_room',
    'have_in_room',
    353,
  ),
]

const stentSlots = [
  addedSlot(
    'OPS-STENT-CONFIG',
    'AIRWAY_STENT_CONFIGURATION',
    'Airway stent configuration',
    'Locally approved stent configuration selected outside this educational prototype.',
    'required',
    'back_table',
    'therapeutic',
    'hold_unopened',
    361,
  ),
  addedSlot(
    'OPS-STENT-TOOLS',
    'STENT_DEPLOYMENT_TOOLS',
    'Stent deployment/loading and measurement tools',
    'Matched deployment, loading, measurement, and retrieval tools.',
    'required',
    'mayo_stand',
    'therapeutic',
    'hold_unopened',
    362,
  ),
  addedSlot(
    'OPS-STENT-BACKUP',
    'AIRWAY_STENT_BACKUP',
    'Backup stent size/configuration',
    'Locally selected backup configuration; this module provides no size guidance.',
    'backup',
    'back_table',
    'rescue_or_contingency',
    'hold_unopened',
    363,
  ),
]

const bleedingRescueModule: RescueModule = {
  code: 'MAJOR_AIRWAY_BLEEDING',
  name: 'Major-airway-bleeding equipment readiness',
  description: 'Reusable equipment-readiness module; it is not a clinical management protocol.',
  slots: [
    addedSlot(
      'RESCUE-BLEED-SUCTION',
      'HIGH_CAPACITY_SUCTION_BACKUP',
      'Second high-capacity suction setup',
      'Independent second suction source, tubing, and canister readiness.',
      'emergency_only',
      'emergency_cart',
      'rescue_or_contingency',
      'emergency_pull',
      901,
    ),
    addedSlot(
      'RESCUE-BLEED-SCOPE',
      'FLEX_SCOPE_THERAPEUTIC',
      'Large-channel backup bronchoscope',
      'Locally selected backup therapeutic bronchoscope.',
      'emergency_only',
      'emergency_cart',
      'rescue_or_contingency',
      'hold_unopened',
      902,
    ),
    addedSlot(
      'RESCUE-BLEED-BALLOON',
      'AIRWAY_TAMPONADE_BALLOON_CAPABILITY',
      'Blocker/tamponade balloon capability',
      'Locally mapped blocker or tamponade balloon capability.',
      'emergency_only',
      'emergency_cart',
      'rescue_or_contingency',
      'emergency_pull',
      903,
    ),
    addedSlot(
      'RESCUE-BLEED-RIGID',
      'RIGID_BRONCHOSCOPY_BACKUP',
      'Rigid bronchoscopy backup readiness',
      'Local rigid bronchoscopy backup tray and team readiness.',
      'emergency_only',
      'emergency_cart',
      'rescue_or_contingency',
      'emergency_pull',
      904,
    ),
    addedSlot(
      'RESCUE-BLEED-VENT',
      'MANUAL_VENTILATION_BACKUP',
      'Ventilation/lung-isolation backup',
      'Locally mapped ventilation and lung-isolation backup readiness.',
      'emergency_only',
      'emergency_cart',
      'rescue_or_contingency',
      'emergency_pull',
      905,
    ),
  ],
}

const chestSecurementSlot = addedSlot(
  'OPS-CHEST-SECUREMENT',
  'LOCAL_CHEST_TUBE_SECUREMENT',
  'Chest-tube securement and dressing pack',
  'Local securement and dressing supplies kept separate for BOM evaluation.',
  'required',
  'back_table',
  'post_procedure',
  'open_or_set_up_now',
  401,
)

export const operationalModifiers: ModifierDefinition[] = [
  {
    code: 'ROSE',
    name: 'Rapid on-site evaluation',
    groupCode: 'sampling',
    description: 'Adds local cytology supplies, personnel, and station readiness.',
    appliesTo: 'EBUS / peripheral / diagnostic',
    releaseState: 'mvp',
    active: true,
    preview: ['Adds 2 local cytology requirements'],
    conflictsWith: [],
    actions: roseSlots.map((slot, index) => addSlotAction('ROSE', 100 + index, slot)),
  },
  {
    code: 'SPEC_MOLECULAR',
    name: 'Molecular testing / NGS',
    groupCode: 'sampling',
    description: 'Adds local specimen preservation, transport, and adequacy readiness.',
    appliesTo: 'EBUS / peripheral / biopsy',
    releaseState: 'mvp',
    active: true,
    preview: ['Adds 2 specimen-workflow requirements'],
    conflictsWith: [],
    actions: molecularSlots.map((slot, index) =>
      addSlotAction('SPEC_MOLECULAR', 110 + index, slot),
    ),
  },
  {
    code: 'RIGID_AIRWAY',
    name: 'Rigid bronchoscopy',
    groupCode: 'anesthesia_airway',
    description: 'Adds the rigid airway system and holds the flexible scope as backup.',
    appliesTo: 'Therapeutic bronchoscopy / stent / foreign body',
    releaseState: 'mvp',
    active: true,
    preview: ['Adds 7 rigid-airway requirements', 'Changes flexible scope to backup'],
    conflictsWith: [],
    actions: [
      action('RIGID_AIRWAY', 200, 'set_requiredness', {
        targetRoleCode: 'FLEX_SCOPE_THERAPEUTIC',
        payload: { value: 'backup' },
      }),
      action('RIGID_AIRWAY', 201, 'set_open_hold_status', {
        targetRoleCode: 'FLEX_SCOPE_THERAPEUTIC',
        payload: { value: 'hold_unopened' },
      }),
      ...rigidSlots.map((slot, index) => addSlotAction('RIGID_AIRWAY', 210 + index, slot)),
      action('RIGID_AIRWAY', 219, 'require_room_capability', {
        payload: { capability: 'rigid_bronchoscopy' },
      }),
    ],
  },
  {
    code: 'APC',
    name: 'Argon plasma coagulation',
    groupCode: 'therapeutic',
    description: 'Adds APC platform, applicators, gas, cable, and safety readiness.',
    appliesTo: 'Therapeutic / rigid',
    releaseState: 'mvp',
    active: true,
    preview: ['Adds 6 requirements', 'Adds 1 blocking compatibility check'],
    conflictsWith: [],
    actions: [
      ...apcSlots.map((slot, index) => addSlotAction('APC', 230 + index, slot)),
      action('APC', 239, 'validate_compatibility', {
        payload: { ruleId: 'RULE-APC-PLATFORM-FAMILY' },
      }),
    ],
  },
  {
    code: 'BALLOON_DILATION',
    name: 'Balloon dilation',
    groupCode: 'therapeutic',
    description: 'Promotes the balloon, guidewire, and inflation requirements.',
    appliesTo: 'Airway stenosis / CAO',
    releaseState: 'mvp',
    active: true,
    preview: ['Promotes 3 requirements', 'Adds 1 compatibility check'],
    conflictsWith: [],
    actions: [
      ...['AIRWAY_BALLOON_DILATOR', 'PULMONARY_GUIDEWIRE', 'INFLATION_DEVICE'].map(
        (roleCode, index) =>
          action('BALLOON_DILATION', 250 + index, 'set_requiredness', {
            targetRoleCode: roleCode,
            payload: { value: 'required' },
          }),
      ),
      addSlotAction(
        'BALLOON_DILATION',
        255,
        addedSlot(
          'OPS-AIRWAY-MEASUREMENT',
          'LOCAL_AIRWAY_MEASUREMENT',
          'Airway measurement readiness',
          'Local measurement workflow; this module provides no sizing recommendation.',
          'required',
          'back_table',
          'therapeutic',
          'have_in_room',
          331,
        ),
      ),
      action('BALLOON_DILATION', 259, 'validate_compatibility', {
        payload: { ruleId: 'RULE-BALLOON-WORKING-CHANNEL' },
      }),
    ],
  },
  {
    code: 'STENT_PLACE',
    name: 'Stent placement',
    groupCode: 'therapeutic',
    description: 'Adds generic stent, deployment, measurement, and backup requirements.',
    appliesTo: 'CAO / stenosis / fistula',
    releaseState: 'mvp',
    active: true,
    preview: ['Adds 3 requirements', 'Promotes sizing tools', 'Flags unmapped backup size'],
    conflictsWith: [],
    actions: [
      ...stentSlots.map((slot, index) => addSlotAction('STENT_PLACE', 270 + index, slot)),
      action('STENT_PLACE', 275, 'set_requiredness', {
        targetRoleCode: 'AIRWAY_STENT_SIZING_DEVICE',
        payload: { value: 'required' },
      }),
      action('STENT_PLACE', 276, 'raise_warning', {
        targetSlotId: 'OPS-STENT-BACKUP',
        payload: {
          code: 'backup_stent_unmapped',
          message:
            'Backup stent size/configuration is not locally mapped; no clinical size is inferred.',
        },
      }),
    ],
  },
  {
    code: 'JET_VENT',
    name: 'Jet ventilation',
    groupCode: 'anesthesia_airway',
    description: 'Adds jet ventilation equipment and manual-ventilation backup.',
    appliesTo: 'Rigid bronchoscopy',
    releaseState: 'mvp',
    active: true,
    preview: ['Adds 3 ventilation requirements'],
    conflictsWith: [],
    actions: [
      ...jetSlots.map((slot, index) => addSlotAction('JET_VENT', 290 + index, slot)),
      action('JET_VENT', 295, 'require_room_capability', {
        payload: { capability: 'jet_ventilation' },
      }),
    ],
  },
  {
    code: 'FLUOROSCOPY',
    name: 'Fluoroscopy',
    groupCode: 'imaging_navigation',
    description: 'Adds C-arm, sterile drape, and radiation-safety resources.',
    appliesTo: 'Peripheral, stent, TBLC, pleural',
    releaseState: 'mvp',
    active: true,
    preview: ['Adds 3 imaging requirements'],
    conflictsWith: [],
    actions: [
      ...fluoroscopySlots.map((slot, index) => addSlotAction('FLUOROSCOPY', 310 + index, slot)),
      action('FLUOROSCOPY', 315, 'require_room_capability', {
        payload: { capability: 'fluoroscopy' },
      }),
    ],
  },
  {
    code: 'HIGH_BLEED_RISK',
    name: 'High bleeding risk',
    groupCode: 'risk_rescue',
    description: 'Appends the major-airway-bleeding equipment-readiness module.',
    appliesTo: 'Biopsy / tumor debulking / TBLC',
    releaseState: 'mvp',
    active: true,
    preview: ['Adds major-airway-bleeding rescue module'],
    conflictsWith: [],
    actions: [
      action('HIGH_BLEED_RISK', 330, 'add_rescue_module', {
        payload: { code: 'MAJOR_AIRWAY_BLEEDING' },
      }),
    ],
  },
  {
    code: 'TECH_CHEST_TUBE_SMALL_BORE',
    name: 'Small-bore Seldinger technique',
    groupCode: 'pleural',
    description: 'Selects the small-bore kit branch.',
    appliesTo: 'Chest tube',
    releaseState: 'mvp',
    active: true,
    preview: ['Promotes small-bore kit', 'Adds one BOM-managed requirement'],
    conflictsWith: ['TECH_CHEST_TUBE_LARGE_BORE'],
    actions: [
      action('TECH_CHEST_TUBE_SMALL_BORE', 400, 'set_requiredness', {
        targetRoleCode: 'CHEST_TUBE_SMALL_BORE',
        payload: { value: 'required' },
      }),
      action('TECH_CHEST_TUBE_SMALL_BORE', 401, 'remove_slot', {
        targetRoleCode: 'CHEST_TUBE_LARGE_BORE',
      }),
      action('TECH_CHEST_TUBE_SMALL_BORE', 402, 'remove_slot', {
        targetRoleCode: 'CHEST_TUBE_SURGICAL',
      }),
      addSlotAction('TECH_CHEST_TUBE_SMALL_BORE', 403, chestSecurementSlot),
    ],
  },
  {
    code: 'TECH_CHEST_TUBE_LARGE_BORE',
    name: 'Large-bore technique',
    groupCode: 'pleural',
    description: 'Selects the large-bore branch using an explicit demo stand-in.',
    appliesTo: 'Chest tube',
    releaseState: 'mvp',
    active: true,
    preview: ['Promotes large-bore kit', 'Adds one separate securement requirement'],
    conflictsWith: ['TECH_CHEST_TUBE_SMALL_BORE'],
    actions: [
      action('TECH_CHEST_TUBE_LARGE_BORE', 410, 'set_requiredness', {
        targetRoleCode: 'CHEST_TUBE_LARGE_BORE',
        payload: { value: 'required' },
      }),
      action('TECH_CHEST_TUBE_LARGE_BORE', 411, 'remove_slot', {
        targetRoleCode: 'CHEST_TUBE_SMALL_BORE',
      }),
      action('TECH_CHEST_TUBE_LARGE_BORE', 412, 'remove_slot', {
        targetRoleCode: 'CHEST_TUBE_SURGICAL',
      }),
      addSlotAction('TECH_CHEST_TUBE_LARGE_BORE', 413, chestSecurementSlot),
    ],
  },
  {
    code: 'DIGITAL_DRAINAGE',
    name: 'Digital pleural drainage',
    groupCode: 'pleural',
    description: 'Replaces the conventional drainage-system role with a digital system.',
    appliesTo: 'Chest tube / PAL / thoracoscopy',
    releaseState: 'phase_1_1',
    active: true,
    preview: ['Replaces 1 drainage requirement'],
    conflictsWith: [],
    actions: [
      action('DIGITAL_DRAINAGE', 420, 'replace_role', {
        targetRoleCode: 'GENERIC_DRAINAGE_UNIT',
        payload: {
          roleCode: 'DIGITAL_DRAINAGE_SYSTEM',
          label: 'Digital pleural drainage system',
          genericRequirement: 'Local digital drainage capital asset and compatible disposable set.',
        },
      }),
    ],
  },
]

export const rescueModules: RescueModule[] = [bleedingRescueModule]

// The deliberately-failing APC fixture rule now lives in __fixtures__/test-compatibility-rules.ts
// so a real card is never blocked just to exercise a test path.
export const typedCompatibilityRules: TypedCompatibilityRule[] = [
  {
    id: 'RULE-BALLOON-WORKING-CHANNEL',
    sourceRoleCode: 'AIRWAY_BALLOON_DILATOR',
    targetRoleCode: 'FLEX_SCOPE_THERAPEUTIC',
    sourceAttribute: 'delivery_system_od_mm',
    targetAttribute: 'min_working_channel_mm',
    operator: 'lte',
    expectedValue: null,
    unit: 'mm',
    severity: 'blocking',
    message:
      'The selected balloon delivery-system outer diameter exceeds the selected scope working channel.',
    missingValueMessage:
      'Balloon-to-scope dimensional compatibility is unknown and requires current product/IFU review.',
    active: true,
    modifierCodes: ['BALLOON_DILATION'],
    evidenceSourceId: null,
  },
]
