'use client'

import { useState } from 'react'

import { waveformAtlasEntries, type WaveformAtlasCategory } from '../content/waveformAtlas'
import { WaveformAtlasFigure } from './WaveformAtlasFigure'
import styles from './icu-hemodynamics.module.css'

const categoryLabels: Record<WaveformAtlasCategory, string> = {
  insertion: 'Advancement sequence',
  abnormal: 'Abnormal patterns',
  artifact: 'False wedge patterns',
}

const categoryOrder: readonly WaveformAtlasCategory[] = ['insertion', 'abnormal', 'artifact']

interface WaveformAtlasPanelProps {
  /** Entry shown when the panel first renders. */
  readonly initialEntryId?: string
  /** Restrict the atlas to a subset, for a station that only needs part of it. */
  readonly onlyCategories?: readonly WaveformAtlasCategory[]
  /** Restrict the atlas to specific entries while preserving the supplied order. */
  readonly onlyEntryIds?: readonly string[]
  /** Combine the selected entries into one explicitly labeled tab list. */
  readonly tablistLabel?: string
  readonly heading?: string
}

export function WaveformAtlasPanel({
  initialEntryId = 'ra-normal',
  onlyCategories,
  onlyEntryIds,
  tablistLabel,
  heading = 'Waveform atlas',
}: WaveformAtlasPanelProps) {
  const [selectedId, setSelectedId] = useState(initialEntryId)
  const categories = onlyCategories ?? categoryOrder
  const visibleEntries = waveformAtlasEntries
    .filter(
      (entry) =>
        categories.includes(entry.category) &&
        (onlyEntryIds === undefined || onlyEntryIds.includes(entry.id)),
    )
    .sort((left, right) =>
      onlyEntryIds === undefined
        ? 0
        : onlyEntryIds.indexOf(left.id) - onlyEntryIds.indexOf(right.id),
    )
  const selected = visibleEntries.find((entry) => entry.id === selectedId) ?? visibleEntries[0]
  if (!selected) {
    throw new Error('WaveformAtlasPanel requires at least one visible atlas entry.')
  }
  const entryGroups = tablistLabel
    ? [{ id: 'selected-entries', label: tablistLabel, entries: visibleEntries }]
    : categories.map((category) => ({
        id: category,
        label: categoryLabels[category],
        entries: visibleEntries.filter((entry) => entry.category === category),
      }))

  return (
    <section className={styles.atlasPanel} aria-labelledby="waveform-atlas-heading">
      <header className={styles.atlasPanelHeader}>
        <div>
          <span>Recognize before you interpret</span>
          <h3 id="waveform-atlas-heading">{heading}</h3>
        </div>
      </header>

      {entryGroups.map((group) => {
        if (group.entries.length === 0) return null
        return (
          <div key={group.id} className={styles.atlasCategory}>
            <h4>{group.label}</h4>
            <div className={styles.atlasTabs} role="tablist" aria-label={group.label}>
              {group.entries.map((entry) => (
                <button
                  key={entry.id}
                  type="button"
                  role="tab"
                  aria-selected={entry.id === selected.id}
                  onClick={() => setSelectedId(entry.id)}
                >
                  {entry.shortLabel}
                </button>
              ))}
            </div>
          </div>
        )
      })}

      <div className={styles.atlasDetail}>
        <p className={styles.atlasSummary}>{selected.summary}</p>
        <WaveformAtlasFigure entry={selected} />

        <div className={styles.atlasDetailGrid}>
          <div>
            <h4>What identifies it</h4>
            <ul>
              {selected.recognitionCues.map((cue) => (
                <li key={cue}>{cue}</li>
              ))}
            </ul>
          </div>
          {selected.pitfall ? (
            <div className={styles.atlasPitfall}>
              <h4>How this becomes misleading</h4>
              <p>{selected.pitfall}</p>
            </div>
          ) : null}
        </div>
      </div>

      <p className={styles.atlasBoundary} role="note">
        Qualitative educational rendering generated by the same model that drives the live monitor.
        It is not a calibrated device trace, and bedside monitors filter and damp differently.
      </p>
    </section>
  )
}
