export const CANDIDATE_DISPLAY_LABELS = {
  "es": {
    "Bronchus intermedius": "Bronquio intermedio",
    "LB1+2": "LB1+2",
    "LB1+2a": "LB1+2a",
    "LB1+2b": "LB1+2b",
    "LB1+2c": "LB1+2c",
    "LB10": "LB10",
    "LB10a": "LB10a",
    "LB10b": "LB10b",
    "LB10c": "LB10c",
    "LB3": "LB3",
    "LB3a": "LB3a",
    "LB3a+b trunk": "Tronco LB3a+b",
    "LB3b": "LB3b",
    "LB3c": "LB3c",
    "LB4": "LB4",
    "LB4a": "LB4a",
    "LB4b": "LB4b",
    "LB5": "LB5",
    "LB5a": "LB5a",
    "LB5b": "LB5b",
    "LB6": "LB6",
    "LB6 trunk distal to LB6c, proximal to LB6a/LB6b bifurcation": "Tronco LB6 distal a LB6c, proximal a la bifurcación LB6a/LB6b",
    "LB6a": "LB6a",
    "LB6b": "LB6b",
    "LB6c": "LB6c",
    "LB7+8": "LB7+8",
    "LB7+8a": "LB7+8a",
    "LB7+8b": "LB7+8b",
    "LB9": "LB9",
    "LB9a": "LB9a",
    "LB9b": "LB9b",
    "LLL basal trunk (distal to LB6)": "Tronco basal del lóbulo inferior izquierdo (distal a LB6)",
    "LLL bronchus origin": "Origen del bronquio del lóbulo inferior izquierdo",
    "LUL bronchus origin": "Origen del bronquio del lóbulo superior izquierdo",
    "Left main bronchus": "Bronquio principal izquierdo",
    "Lingular bronchus origin": "Origen del bronquio lingular",
    "RB1": "RB1",
    "RB1a": "RB1a",
    "RB1b": "RB1b",
    "RB2": "RB2",
    "RB2a": "RB2a",
    "RB2b": "RB2b",
    "RB3": "RB3",
    "RB3a": "RB3a",
    "RB3a trunk proximal to RB3a1/RB3a2/RB3a3 branching": "Tronco RB3a proximal a las ramas RB3a1/RB3a2/RB3a3",
    "RB3b": "RB3b",
    "RB4": "RB4",
    "RB4a": "RB4a",
    "RB4b": "RB4b",
    "RB5": "RB5",
    "RB5a": "RB5a",
    "RB5b": "RB5b",
    "RB6": "RB6",
    "RB6a": "RB6a",
    "RB6a+b orifice": "Orificio RB6a+b",
    "RB6b": "RB6b",
    "RB6c": "RB6c",
    "RB7": "RB7",
    "RB7a": "RB7a",
    "RB7b": "RB7b",
    "RLL basal trunk (between RB6 and RB7 origin)": "Tronco basal del lóbulo inferior derecho (entre los orígenes de RB6 y RB7)",
    "RLL basal trunk (between RB7 and RB8 origin)": "Tronco basal del lóbulo inferior derecho (entre los orígenes de RB7 y RB8)",
    "RLL bronchus origin": "Origen del bronquio del lóbulo inferior derecho",
    "RML bronchus origin": "Origen del bronquio del lóbulo medio derecho",
    "RUL bronchus origin": "Origen del bronquio del lóbulo superior derecho",
    "Right main bronchus": "Bronquio principal derecho",
    "Upper division bronchus (LB1+2+3) origin": "Origen del bronquio de la división superior (LB1+2+3)"
  },
  "zh-CN": {
    "Bronchus intermedius": "中间支气管",
    "LB1+2": "LB1+2",
    "LB1+2a": "LB1+2a",
    "LB1+2b": "LB1+2b",
    "LB1+2c": "LB1+2c",
    "LB10": "LB10",
    "LB10a": "LB10a",
    "LB10b": "LB10b",
    "LB10c": "LB10c",
    "LB3": "LB3",
    "LB3a": "LB3a",
    "LB3a+b trunk": "LB3a+b 干",
    "LB3b": "LB3b",
    "LB3c": "LB3c",
    "LB4": "LB4",
    "LB4a": "LB4a",
    "LB4b": "LB4b",
    "LB5": "LB5",
    "LB5a": "LB5a",
    "LB5b": "LB5b",
    "LB6": "LB6",
    "LB6 trunk distal to LB6c, proximal to LB6a/LB6b bifurcation": "LB6 干，位于 LB6c 远端、LB6a/LB6b 分叉近端",
    "LB6a": "LB6a",
    "LB6b": "LB6b",
    "LB6c": "LB6c",
    "LB7+8": "LB7+8",
    "LB7+8a": "LB7+8a",
    "LB7+8b": "LB7+8b",
    "LB9": "LB9",
    "LB9a": "LB9a",
    "LB9b": "LB9b",
    "LLL basal trunk (distal to LB6)": "左下叶基底干（LB6 远端）",
    "LLL bronchus origin": "左下叶支气管起点",
    "LUL bronchus origin": "左上叶支气管起点",
    "Left main bronchus": "左主支气管",
    "Lingular bronchus origin": "舌段支气管起点",
    "RB1": "RB1",
    "RB1a": "RB1a",
    "RB1b": "RB1b",
    "RB2": "RB2",
    "RB2a": "RB2a",
    "RB2b": "RB2b",
    "RB3": "RB3",
    "RB3a": "RB3a",
    "RB3a trunk proximal to RB3a1/RB3a2/RB3a3 branching": "RB3a 干，位于 RB3a1/RB3a2/RB3a3 分支近端",
    "RB3b": "RB3b",
    "RB4": "RB4",
    "RB4a": "RB4a",
    "RB4b": "RB4b",
    "RB5": "RB5",
    "RB5a": "RB5a",
    "RB5b": "RB5b",
    "RB6": "RB6",
    "RB6a": "RB6a",
    "RB6a+b orifice": "RB6a+b 开口",
    "RB6b": "RB6b",
    "RB6c": "RB6c",
    "RB7": "RB7",
    "RB7a": "RB7a",
    "RB7b": "RB7b",
    "RLL basal trunk (between RB6 and RB7 origin)": "右下叶基底干（RB6 与 RB7 起点之间）",
    "RLL basal trunk (between RB7 and RB8 origin)": "右下叶基底干（RB7 与 RB8 起点之间）",
    "RLL bronchus origin": "右下叶支气管起点",
    "RML bronchus origin": "右中叶支气管起点",
    "RUL bronchus origin": "右上叶支气管起点",
    "Right main bronchus": "右主支气管",
    "Upper division bronchus (LB1+2+3) origin": "上区支气管（LB1+2+3）起点"
  }
} as const;
