import { McsPumpCutaway } from './McsPumpCutaway'
import { useState } from 'react'
import { McsPathwayTour, McsCirculationSketch } from './McsPathwayTour'
import type { McsIntroduction } from '../../content/introductorySteps'
import type { McsSimulationState } from '../../engine/types'
import { activePathways } from '../teaching/selectors'
import { PathwayGraphic } from '../teaching/shared'
import { McsCapturedResults } from './McsCapturedResults'
import styles from './mcs-stage.module.css'

export function McsIntroTeaching({
  introduction,
  state,
  before,
}: {
  introduction: McsIntroduction
  state: McsSimulationState
  before: McsSimulationState | null
}) {
  const [parameter, setParameter] = useState(0)
  return (
    <section className={styles.block} data-intro-teaching={introduction.id}>
      <p className={styles.kicker}>Concept and guided example</p>
      <h3>{introduction.title}</h3>
      {introduction.paragraphs.map((text) => (
        <p key={text}>{text}</p>
      ))}
      {introduction.id === 'orientation' ? <McsCirculationSketch /> : null}
      {introduction.visual === 'signals' ? (
        <dl className={styles.definitionList} data-measurement-tour>
          <dt>Pressure · mm Hg</dt>
          <dd>
            The arterial trace and MAP represent pressure at a measurement site. Here they are
            generated by the circulation model. Pressure does not measure flow.
          </dd>
          <dt>Blood flow · L/min</dt>
          <dd>
            Concurrent native forward flow is modeled ejection during support. Pump flow is a
            simulated device estimate. Effective systemic flow reconciles the represented routes and
            recirculation; it is not a measured bedside cardiac output.
          </dd>
          <dt>Oxygen delivery</dt>
          <dd>
            Blood flow multiplied by arterial oxygen content, expressed as oxygen per minute.
            Content depends mainly on hemoglobin and arterial oxygen saturation. The model does not
            calculate a full oxygen transport balance; its SvO2 value is a flow-linked teaching
            surrogate.
          </dd>
          <dt>Clinical perfusion assessment</dt>
          <dd>
            Mentation, urine output, skin perfusion and lactate trend require patient observations
            and context. These organ responses are not simulated here.
          </dd>
        </dl>
      ) : null}
      {introduction.visual === 'pathways' ? <McsPathwayTour /> : null}
      {introduction.id === 'inlet-outlet' ? <McsPumpCutaway /> : null}
      {introduction.visual === 'impella'
        ? activePathways(state).map((pathway) => (
            <PathwayGraphic key={pathway.id} pathway={pathway} />
          ))
        : null}
      {introduction.visual === 'lvad' ? (
        <div data-controller-tour>
          <div role="group" aria-label="Controller quantity tour">
            {[
              'Speed',
              'Estimated pump flow',
              'Electrical pump power',
              'Pulsatility index',
              'Patient assessment',
              'Cardiac power output',
            ].map((label, index) => (
              <button
                type="button"
                key={label}
                aria-pressed={parameter === index}
                onClick={() => setParameter(index)}
              >
                {label}
              </button>
            ))}
          </div>
          <dl className={styles.definitionList} data-parameter={parameter}>
            {parameter === 0 ? (
              <>
                <dt>Speed · {state.device.kind === 'lvad' ? state.device.speedRpm : '—'} rpm</dt>
                <dd>The prescribed rotation setting. It does not set an invariant flow.</dd>
              </>
            ) : null}
            {parameter === 1 ? (
              <>
                <dt>Estimated pump flow · {state.metrics.deviceFlowLMin.toFixed(2)} L/min</dt>
                <dd>
                  In this model, generated from speed and loading. Clinical estimation methods
                  depend on the device; this is not a flow-probe reading.
                </dd>
              </>
            ) : null}
            {parameter === 2 ? (
              <>
                <dt>Electrical pump power · {state.metrics.pumpPowerW?.toFixed(1)} W</dt>
                <dd>
                  Represents pump electrical demand. Here it is derived from modeled flow, speed and
                  the power-fault term.
                </dd>
              </>
            ) : null}
            {parameter === 3 ? (
              <>
                <dt>Pulsatility index · {state.metrics.pulsatilityIndex?.toFixed(1)}</dt>
                <dd>
                  A unitless controller parameter related to pulsatility. Here it is an authored
                  function of native flow, pump flow and preload, not a measured clinical PI or
                  flow-estimator input.
                </dd>
              </>
            ) : null}
            {parameter === 4 ? (
              <>
                <dt>Separate patient assessment</dt>
                <dd>
                  Blood pressure, filling pressures, echocardiography and clinical perfusion
                  findings supply information beyond the controller. Modeled LV volume (mL)
                  illustrates unloading; it is neither pressure nor a bedside volume measurement.
                </dd>
              </>
            ) : null}
            {parameter === 5 ? (
              <>
                <dt>
                  Calculated cardiac power output · {state.metrics.cardiacPowerOutputW.toFixed(2)} W
                </dt>
                <dd>
                  MAP × modeled effective systemic flow / 451. It is a pressure–flow product,
                  distinct from pump electrical power and oxygen delivery.
                </dd>
              </>
            ) : null}
          </dl>
        </div>
      ) : null}
      {before &&
      (introduction.id === 'unloading-example' || introduction.id === 'afterload-example') ? (
        <McsCapturedResults
          before={before}
          after={state}
          providedExample={state.actionIds.length === 0}
          signals={
            introduction.visual === 'impella'
              ? [
                  {
                    key: 'leftDeviceFlowLMin',
                    label: 'Pump estimate',
                    unit: 'L/min',
                    digits: 2,
                    level: 'device-display',
                  },
                  {
                    key: 'lvedvMl',
                    label: 'Modeled LV volume',
                    unit: 'mL',
                    digits: 0,
                    level: 'volume',
                  },
                  {
                    key: 'pcwpMmHg',
                    label: 'Wedge pressure',
                    unit: 'mm Hg',
                    digits: 0,
                    level: 'pressure',
                  },
                ]
              : [
                  {
                    key: 'deviceFlowLMin',
                    label: 'Pump estimate',
                    unit: 'L/min',
                    digits: 2,
                    level: 'device-display',
                  },
                  {
                    key: 'pumpPowerW',
                    label: 'Electrical pump power',
                    unit: 'W',
                    digits: 1,
                    level: 'device-display',
                  },
                  {
                    key: 'mapMmHg',
                    label: 'Mean arterial pressure',
                    unit: 'mm Hg',
                    digits: 0,
                    level: 'pressure',
                  },
                ]
          }
        />
      ) : null}
      <p className={styles.footnote}>
        Teaching revision: September 2026 · draft for faculty review. Device principles follow the
        section’s references; response magnitudes and observation intervals are authored simulation
        behavior.
      </p>
    </section>
  )
}
