import type { McsIntroduction } from '../../content/introductorySteps'
import type { McsSimulationState } from '../../engine/types'
import { activePathways, mcsComparisonPathways } from '../teaching/selectors'
import { PathwayGraphic } from '../teaching/shared'
import { McsCapturedResults } from './McsCapturedResults'
import styles from './mcs-stage.module.css'

export function McsIntroTeaching({
  introduction,
  state,
  before,
}: {
  introduction: McsIntroduction
  state: McsSimulationState
  before: McsSimulationState | null
}) {
  return (
    <section className={styles.block} data-intro-teaching={introduction.id}>
      <p className={styles.kicker}>Concept and guided example · not independent credit</p>
      <h3>{introduction.title}</h3>
      {introduction.paragraphs.map((text) => (
        <p key={text}>{text}</p>
      ))}
      {introduction.visual === 'signals' ? (
        <dl className={styles.definitionList} data-measurement-tour>
          <dt>Pressure · mm Hg</dt>
          <dd>
            The arterial trace and MAP represent pressure at a measurement site. Here they are
            generated by the circulation model. Pressure does not measure flow.
          </dd>
          <dt>Blood flow · L/min</dt>
          <dd>
            Concurrent native forward flow is modeled ejection during support. Pump flow is a
            simulated device estimate. Effective systemic flow reconciles the represented routes and
            recirculation; it is not a measured bedside cardiac output.
          </dd>
          <dt>Oxygen delivery</dt>
          <dd>
            Blood flow multiplied by arterial oxygen content, expressed as oxygen per minute.
            Content depends mainly on hemoglobin and arterial oxygen saturation. The model does not
            calculate a full oxygen transport balance; its SvO2 value is a flow-linked teaching
            surrogate.
          </dd>
          <dt>Clinical perfusion assessment</dt>
          <dd>
            Mentation, urine output, skin perfusion and lactate trend require patient observations
            and context. These organ responses are not simulated here.
          </dd>
        </dl>
      ) : null}
      {introduction.visual === 'pathways' ? (
        <div data-annotated-pathway-comparison>
          <PathwayGraphic pathway={mcsComparisonPathways.iabp} />
          <PathwayGraphic pathway={mcsComparisonPathways.impellaLeft} />
          <PathwayGraphic pathway={mcsComparisonPathways.lvad} />
          <p>
            Parallel flow account: concurrent native forward flow + left-pump flow − represented
            recirculation = modeled effective systemic flow, within the engine’s numeric clamps.
            These teaching quantities are not independently measured clinical components.
          </p>
        </div>
      ) : null}
      {introduction.visual === 'impella'
        ? activePathways(state).map((pathway) => (
            <PathwayGraphic key={pathway.id} pathway={pathway} />
          ))
        : null}
      {introduction.visual === 'lvad' ? (
        <dl className={styles.definitionList} data-controller-tour>
          <dt>Speed · {state.device.kind === 'lvad' ? state.device.speedRpm : '—'} rpm</dt>
          <dd>The prescribed rotation setting. It does not set an invariant flow.</dd>
          <dt>Estimated pump flow · {state.metrics.deviceFlowLMin.toFixed(2)} L/min</dt>
          <dd>
            In this model, generated from speed and loading. Clinical estimation methods depend on
            the device; this is not a flow-probe reading.
          </dd>
          <dt>Electrical pump power · {state.metrics.pumpPowerW?.toFixed(1)} W</dt>
          <dd>
            Represents pump electrical demand. Here it is derived from modeled flow, speed and the
            power-fault term.
          </dd>
          <dt>Pulsatility index · {state.metrics.pulsatilityIndex?.toFixed(1)}</dt>
          <dd>
            A unitless controller parameter related to pulsatility. Here it is an authored function
            of native flow, pump flow and preload, not a measured clinical PI or flow-estimator
            input.
          </dd>
          <dt>Separate patient assessment</dt>
          <dd>
            Blood pressure, filling pressures, echocardiography and clinical perfusion findings
            supply information beyond the controller. Modeled LV volume (mL) illustrates unloading;
            it is neither pressure nor a bedside volume measurement.
          </dd>
          <dt>
            Calculated cardiac power output · {state.metrics.cardiacPowerOutputW.toFixed(2)} W
          </dt>
          <dd>
            MAP × modeled effective systemic flow / 451. It is a pressure–flow product, distinct
            from pump electrical power and oxygen delivery.
          </dd>
        </dl>
      ) : null}
      {before &&
      (introduction.id === 'unloading-example' || introduction.id === 'afterload-example') ? (
        <McsCapturedResults
          before={before}
          after={state}
          signals={
            introduction.visual === 'impella'
              ? [
                  {
                    key: 'leftDeviceFlowLMin',
                    label: 'Pump estimate',
                    unit: 'L/min',
                    digits: 2,
                    level: 'device-display',
                  },
                  {
                    key: 'lvedvMl',
                    label: 'Modeled LV volume',
                    unit: 'mL',
                    digits: 0,
                    level: 'volume',
                  },
                  {
                    key: 'pcwpMmHg',
                    label: 'Wedge pressure',
                    unit: 'mm Hg',
                    digits: 0,
                    level: 'pressure',
                  },
                ]
              : [
                  {
                    key: 'deviceFlowLMin',
                    label: 'Pump estimate',
                    unit: 'L/min',
                    digits: 2,
                    level: 'device-display',
                  },
                  {
                    key: 'pumpPowerW',
                    label: 'Electrical pump power',
                    unit: 'W',
                    digits: 1,
                    level: 'device-display',
                  },
                  {
                    key: 'mapMmHg',
                    label: 'Mean arterial pressure',
                    unit: 'mm Hg',
                    digits: 0,
                    level: 'pressure',
                  },
                ]
          }
        />
      ) : null}
      <p className={styles.footnote}>
        Teaching revision: September 2026 · draft for faculty review. Device principles follow the
        section’s references; response magnitudes and observation intervals are authored simulation
        behavior.
      </p>
    </section>
  )
}
