import manifestJson from '../../../../public/models/rigid-bronchoscopy/v2/asset-manifest.json'

import { resolveModuleAssetPath } from '@/lib/module-assets'

/**
 * The v2 manifest is generated by scripts/rigid-bronchoscopy/build-v2-assets.py.
 * Runtime code resolves assets by semantic id so a rebuilt content hash cannot
 * leave a stale filename embedded in the teaching scene.
 */
export const rigidBronchoscopyV2Manifest = manifestJson

export type RigidV2AssetRecord = (typeof manifestJson.assets)[number]

export function getRigidV2AssetRecord(assetId: string): RigidV2AssetRecord {
  const asset = manifestJson.assets.find((candidate) => candidate.id === assetId)
  if (!asset) {
    throw new Error(`Rigid bronchoscopy v2 manifest is missing asset: ${assetId}`)
  }
  return asset
}

export function getRigidV2AssetPath(assetId: string): string {
  return resolveModuleAssetPath(getRigidV2AssetRecord(assetId).path)
}

export const RIGID_V2_WORLD_UNITS_PER_MILLIMETER =
  rigidBronchoscopyV2Manifest.presentation.worldUnitsPerMillimeter
export const RIGID_V2_ASSET_SCALE_WORLD_UNITS_PER_METER =
  rigidBronchoscopyV2Manifest.presentation.assetScaleWorldUnitsPerMeter

export const RIGID_V2_ASSET_IDS = {
  airwayCutaway: 'anatomy-central-airway-cutaway',
  airwayFull: 'anatomy-central-airway-full',
  anesthesiaCircuitHose: 'accessory-anesthesia-circuit-hose',
  assemblyKit: 'efer-rigid-bronchoscopy-assembly-kit',
  jetHose: 'accessory-jet-ventilation-hose',
  opticalForcepsCap: 'cap-bs2319-3-optical-forceps',
  telescopeInstrumentCap2mm: 'cap-bs2309-3-telescope-plus-2mm-instrument',
  telescopeInstrumentCap4mm: 'cap-bs2311-3-telescope-plus-4mm-instrument',
  stentIntroducer: 'tool-stent-introducer',
} as const
